name = "gwf-evta"
schema_version = "2.0.0.dev1"
advanced = false
multi = true
ftype = "EVTA"

[blocks.options.readasarrays]
block = "options"
description = "indicates that array-based input will be used for the Evapotranspiration Package.  This keyword must be specified to use array-based input.  When READASARRAYS is specified, values must be provided for every cell within a model layer, even those cells that have an IDOMAIN value less than one.  Values assigned to cells with IDOMAIN values less than one are not used and have no effect on simulation results."
default = true
reader = "urword"
optional = false
longname = "use array-based input"
type = "keyword"

[blocks.options.fixed_cell]
block = "options"
description = "indicates that evapotranspiration will not be reassigned to a cell underlying the cell specified in the list if the specified cell is inactive."
reader = "urword"
optional = true
longname = "if cell is dry do not apply evapotranspiration to underlying cell"
type = "keyword"

[blocks.options.auxiliary]
shape = "(naux)"
block = "options"
description = "defines an array of one or more auxiliary variable names.  There is no limit on the number of auxiliary variables that can be provided on this line; however, lists of information provided in subsequent blocks must have a column of data for each auxiliary variable name defined here.   The number of auxiliary variables detected on this line determines the value for naux.  Comments cannot be provided anywhere on this line as they will be interpreted as auxiliary variable names.  Auxiliary variables may not be used by the package, but they will be available for use by other parts of the program.  The program will terminate with an error if auxiliary variables are specified on more than one line in the options block."
reader = "urword"
optional = true
longname = "keyword to specify aux variables"
type = "string"

[blocks.options.auxmultname]
block = "options"
description = "name of auxiliary variable to be used as multiplier of evapotranspiration rate."
reader = "urword"
optional = true
longname = "name of auxiliary variable for multiplier"
type = "string"

[blocks.options.print_input]
block = "options"
description = "keyword to indicate that the list of evapotranspiration information will be written to the listing file immediately after it is read."
reader = "urword"
optional = true
longname = "print input to listing file"
mf6internal = "iprpak"
type = "keyword"

[blocks.options.print_flows]
block = "options"
description = "keyword to indicate that the list of evapotranspiration flow rates will be printed to the listing file for every stress period time step in which 'BUDGET PRINT' is specified in Output Control.  If there is no Output Control option and 'PRINT_FLOWS' is specified, then flow rates are printed for the last time step of each stress period."
reader = "urword"
optional = true
longname = "print evapotranspiration rates to listing file"
mf6internal = "iprflow"
type = "keyword"

[blocks.options.save_flows]
block = "options"
description = "keyword to indicate that evapotranspiration flow terms will be written to the file specified with 'BUDGET FILEOUT' in Output Control."
reader = "urword"
optional = true
longname = "save CHD flows to budget file"
mf6internal = "ipakcb"
type = "keyword"

[blocks.options.tas_filerecord]
block = "options"
reader = "urword"
optional = true
type = "record"

[blocks.options.tas_filerecord.children.tas6]
block = "options"
description = "keyword to specify that record corresponds to a time-array-series file."
reader = "urword"
optional = false
longname = "head keyword"
type = "keyword"

[blocks.options.tas_filerecord.children.filein]
block = "options"
description = "keyword to specify that an input filename is expected next."
reader = "urword"
optional = false
longname = "file keyword"
type = "keyword"

[blocks.options.tas_filerecord.children.tas6_filename]
block = "options"
description = "defines a time-array-series file defining a time-array series that can be used to assign time-varying values. See the Time-Variable Input section for instructions on using the time-array series capability."
reader = "urword"
optional = false
longname = "file name of time series information"
type = "string"

[blocks.options.obs_filerecord]
block = "options"
reader = "urword"
optional = true
type = "record"

[blocks.options.obs_filerecord.children.obs6]
block = "options"
description = "keyword to specify that record corresponds to an observations file."
reader = "urword"
optional = false
longname = "obs keyword"
type = "keyword"

[blocks.options.obs_filerecord.children.filein]
block = "options"
description = "keyword to specify that an input filename is expected next."
reader = "urword"
optional = false
longname = "file keyword"
type = "keyword"

[blocks.options.obs_filerecord.children.obs6_filename]
block = "options"
description = "name of input file to define observations for the EVT package. See the 'Observation utility' section for instructions for preparing observation input files. Table {#2} lists observation type(s) supported by the EVT package."
reader = "urword"
optional = false
longname = "obs6 input filename"
type = "string"

[blocks.options.export_array_netcdf]
block = "options"
description = "keyword that specifies input gridded arrays should be written to the model output NetCDF file with attributes that support using the generated file as a MODFLOW 6 simulation input.  This option only has an effect when an output model NetCDF file is configured and the simulation is run in VALIDATE mode, otherwise it is ignored."
reader = "urword"
optional = true
mf6internal = "export_nc"
longname = "export array variables to netcdf output files."
extended = true
type = "keyword"

[blocks.period.ievt]
shape = "(nper, ncol*nrow; ncpl)"
block = "period"
description = "IEVT is the layer number that defines the layer in each vertical column where evapotranspiration is applied. If IEVT is omitted, evapotranspiration by default is applied to cells in layer 1.  If IEVT is specified, it must be specified as the first variable in the PERIOD block or MODFLOW will terminate with an error."
reader = "readarray"
numeric_index = true
optional = true
netcdf = true
longname = "layer number for evapotranspiration"
type = "integer"

[blocks.period.surface]
shape = "(nper, ncol*nrow; ncpl)"
block = "period"
description = "is the elevation of the ET surface ($L$)."
default = "0."
reader = "readarray"
netcdf = true
longname = "evapotranspiration surface"
type = "double"

[blocks.period.rate]
shape = "(nper, ncol*nrow; ncpl)"
block = "period"
description = "is the maximum ET flux rate ($LT^{-1}$)."
default = "1.e-3"
reader = "readarray"
time_series = true
netcdf = true
longname = "evapotranspiration surface"
type = "double"

[blocks.period.depth]
shape = "(nper, ncol*nrow; ncpl)"
block = "period"
description = "is the ET extinction depth ($L$)."
default = "1.0"
reader = "readarray"
netcdf = true
longname = "extinction depth"
type = "double"

[blocks.period.aux]
shape = "(nper, ncol*nrow; ncpl)"
block = "period"
description = "is an array of values for auxiliary variable AUX(IAUX), where iaux is a value from 1 to NAUX, and AUX(IAUX) must be listed as part of the auxiliary variables.  A separate array can be specified for each auxiliary variable.  If an array is not specified for an auxiliary variable, then a value of zero is assigned.  If the value specified here for the auxiliary variable is the same as auxmultname, then the evapotranspiration rate will be multiplied by this array."
reader = "readarray"
time_series = true
netcdf = true
longname = "evapotranspiration auxiliary variable iaux"
mf6internal = "auxvar"
type = "double"
