name = "gwf-hfb"
schema_version = "2.0.0.dev1"
advanced = false
multi = false
ftype = "HFB"

[blocks.options.print_input]
block = "options"
description = "keyword to indicate that the list of hydraulic flow barriers will be written to the listing file immediately after it is read."
reader = "urword"
optional = true
longname = "model print input to listing file"
type = "keyword"

[blocks.dimensions.maxhfb]
block = "dimensions"
description = "integer value specifying the maximum number of hydraulic flow barriers that will be entered in this input file.  The value of MAXHFB is used to allocate memory for the hydraulic flow barriers."
reader = "urword"
optional = false
mf6internal = "maxbound"
longname = "maximum number of barriers"
type = "integer"

[blocks.period.cellid1]
shape = "(nper, ncelldim)"
block = "period"
description = "identifier for the first cell.  For a structured grid that uses the DIS input file, CELLID1 is the layer, row, and column numbers of the cell.   For a grid that uses the DISV input file, CELLID1 is the layer number and CELL2D number for the two cells.  If the model uses the unstructured discretization (DISU) input file, then CELLID1 is the node numbers for the cell.  The barrier is located between cells designated as CELLID1 and CELLID2.  For models that use the DIS and DISV grid types, the layer number for CELLID1 and CELLID2 must be the same.  For all grid types, cells must be horizontally or vertically adjacent."
reader = "urword"
longname = "first cell adjacent to barrier"
type = "integer"

[blocks.period.cellid2]
shape = "(nper, ncelldim)"
block = "period"
description = "identifier for the second cell. See CELLID1 for description of how to specify."
reader = "urword"
longname = "second cell adjacent to barrier"
type = "integer"

[blocks.period.hydchr]
shape = "(nper)"
block = "period"
description = "is the hydraulic characteristic of the hydraulic-flow barrier. The hydraulic characteristic is the barrier hydraulic conductivity divided by the width of the hydraulic-flow barrier. If the hydraulic characteristic is negative, then the absolute value of HYDCHR acts as a multiplier to the conductance between the two model cells specified as containing the barrier. For example, if the value for HYDCHR was specified as -1.5, the conductance calculated for the two cells would be multiplied by 1.5."
reader = "urword"
longname = "barrier hydraulic characteristic"
type = "double"
