name = "gwf-oc"
schema_version = "2.0.0.dev1"
advanced = false
multi = false
ftype = "OC"

[blocks.options.budget_filerecord]
block = "options"
reader = "urword"
optional = true
mf6internal = "budfilerec"
type = "record"

[blocks.options.budget_filerecord.children.budget]
block = "options"
description = "keyword to specify that record corresponds to the budget."
reader = "urword"
optional = false
longname = "budget keyword"
type = "keyword"

[blocks.options.budget_filerecord.children.fileout]
block = "options"
description = "keyword to specify that an output filename is expected next."
reader = "urword"
optional = false
longname = "file keyword"
type = "keyword"

[blocks.options.budget_filerecord.children.budgetfile]
block = "options"
description = "name of the output file to write budget information."
reader = "urword"
optional = false
longname = "file keyword"
type = "string"

[blocks.options.budgetcsv_filerecord]
block = "options"
reader = "urword"
optional = true
mf6internal = "budcsvfilerec"
type = "record"

[blocks.options.budgetcsv_filerecord.children.budgetcsv]
block = "options"
description = "keyword to specify that record corresponds to the budget CSV."
reader = "urword"
optional = false
longname = "budget keyword"
type = "keyword"

[blocks.options.budgetcsv_filerecord.children.fileout]
block = "options"
description = "keyword to specify that an output filename is expected next."
reader = "urword"
optional = false
longname = "file keyword"
type = "keyword"

[blocks.options.budgetcsv_filerecord.children.budgetcsvfile]
block = "options"
description = "name of the comma-separated value (CSV) output file to write budget summary information.  A budget summary record will be written to this file for each time step of the simulation."
reader = "urword"
optional = false
longname = "file keyword"
type = "string"

[blocks.options.head_filerecord]
block = "options"
reader = "urword"
optional = true
mf6internal = "headfilerec"
type = "record"

[blocks.options.head_filerecord.children.head]
block = "options"
description = "keyword to specify that record corresponds to head."
reader = "urword"
optional = false
longname = "head keyword"
type = "keyword"

[blocks.options.head_filerecord.children.fileout]
block = "options"
description = "keyword to specify that an output filename is expected next."
reader = "urword"
optional = false
longname = "file keyword"
type = "keyword"

[blocks.options.head_filerecord.children.headfile]
block = "options"
description = "name of the output file to write head information."
reader = "urword"
optional = false
longname = "file keyword"
type = "string"

[blocks.options.headprintrecord]
block = "options"
reader = "urword"
optional = true
mf6internal = "headprintrec"
type = "record"

[blocks.options.headprintrecord.children.head]
block = "options"
description = "keyword to specify that record corresponds to head."
reader = "urword"
optional = false
longname = "head keyword"
type = "keyword"

[blocks.options.headprintrecord.children.print_format]
block = "options"
description = "keyword to specify format for printing to the listing file."
reader = "urword"
optional = false
longname = "keyword to indicate that a print format follows"
type = "keyword"

[blocks.period.saverecord]
shape = "(nper)"
block = "period"
reader = "urword"
optional = true
type = "record"

[blocks.period.saverecord.children.save]
block = "period"
description = "keyword to indicate that information will be saved this stress period."
reader = "urword"
optional = false
longname = "keyword to save"
type = "keyword"

[blocks.period.saverecord.children.rtype]
block = "period"
description = "type of information to save or print.  Can be BUDGET or HEAD."
reader = "urword"
optional = false
longname = "record type"
type = "string"

[blocks.period.saverecord.children.ocsetting]
block = "period"
description = "specifies the steps for which the data will be saved."
reader = "urword"
type = "union"

[blocks.period.saverecord.children.ocsetting.children.all]
block = "period"
description = "keyword to indicate save for all time steps in period."
reader = "urword"
type = "keyword"

[blocks.period.saverecord.children.ocsetting.children.first]
block = "period"
description = "keyword to indicate save for first step in period. This keyword may be used in conjunction with other keywords to print or save results for multiple time steps."
reader = "urword"
type = "keyword"

[blocks.period.saverecord.children.ocsetting.children.last]
block = "period"
description = "keyword to indicate save for last step in period. This keyword may be used in conjunction with other keywords to print or save results for multiple time steps."
reader = "urword"
type = "keyword"

[blocks.period.saverecord.children.ocsetting.children.frequency]
block = "period"
description = "save at the specified time step frequency. This keyword may be used in conjunction with other keywords to print or save results for multiple time steps."
reader = "urword"
type = "integer"

[blocks.period.saverecord.children.ocsetting.children.steps]
shape = "(<nstp)"
block = "period"
description = "save for each step specified in STEPS. This keyword may be used in conjunction with other keywords to print or save results for multiple time steps."
reader = "urword"
type = "integer"

[blocks.period.printrecord]
shape = "(nper)"
block = "period"
reader = "urword"
optional = true
type = "record"

[blocks.period.printrecord.children.print]
block = "period"
description = "keyword to indicate that information will be printed this stress period."
reader = "urword"
optional = false
longname = "keyword to save"
type = "keyword"

[blocks.period.printrecord.children.rtype]
block = "period"
description = "type of information to save or print.  Can be BUDGET or HEAD."
reader = "urword"
optional = false
longname = "record type"
type = "string"

[blocks.period.printrecord.children.ocsetting]
block = "period"
description = "specifies the steps for which the data will be saved."
reader = "urword"
type = "union"

[blocks.period.printrecord.children.ocsetting.children.all]
block = "period"
description = "keyword to indicate save for all time steps in period."
reader = "urword"
type = "keyword"

[blocks.period.printrecord.children.ocsetting.children.first]
block = "period"
description = "keyword to indicate save for first step in period. This keyword may be used in conjunction with other keywords to print or save results for multiple time steps."
reader = "urword"
type = "keyword"

[blocks.period.printrecord.children.ocsetting.children.last]
block = "period"
description = "keyword to indicate save for last step in period. This keyword may be used in conjunction with other keywords to print or save results for multiple time steps."
reader = "urword"
type = "keyword"

[blocks.period.printrecord.children.ocsetting.children.frequency]
block = "period"
description = "save at the specified time step frequency. This keyword may be used in conjunction with other keywords to print or save results for multiple time steps."
reader = "urword"
type = "integer"

[blocks.period.printrecord.children.ocsetting.children.steps]
shape = "(<nstp)"
block = "period"
description = "save for each step specified in STEPS. This keyword may be used in conjunction with other keywords to print or save results for multiple time steps."
reader = "urword"
type = "integer"
