name = "gwt-ssm"
schema_version = "2.0.0.dev1"
advanced = false
multi = false
ftype = "SSM"

[blocks.options.print_flows]
block = "options"
description = "keyword to indicate that the list of SSM flow rates will be printed to the listing file for every stress period time step in which 'BUDGET PRINT' is specified in Output Control.  If there is no Output Control option and 'PRINT_FLOWS' is specified, then flow rates are printed for the last time step of each stress period."
reader = "urword"
optional = true
longname = "print calculated flows to listing file"
type = "keyword"

[blocks.options.save_flows]
block = "options"
description = "keyword to indicate that SSM flow terms will be written to the file specified with 'BUDGET FILEOUT' in Output Control."
reader = "urword"
optional = true
longname = "save calculated flows to budget file"
type = "keyword"

[blocks.sources.sources]
block = "sources"
reader = "urword"
optional = false
longname = "package list"
type = "list"

[blocks.sources.sources.children.sources]
block = "sources"
reader = "urword"
optional = false
longname = "package list"
type = "record"

[blocks.sources.sources.children.sources.children.pname]
block = "sources"
description = "name of the flow package for which an auxiliary variable contains a source concentration.  If this flow package is represented using an advanced transport package (SFT, LKT, MWT, or UZT), then the advanced transport package will override SSM terms specified here."
reader = "urword"
mf6internal = "pname_sources"
longname = "package name"
type = "string"

[blocks.sources.sources.children.sources.children.srctype]
block = "sources"
description = "keyword indicating how concentration will be assigned for sources and sinks.  Keyword must be specified as either AUX or AUXMIXED.  For both options the user must provide an auxiliary variable in the corresponding flow package.  The auxiliary variable must have the same name as the AUXNAME value that follows.  If the AUX keyword is specified, then the auxiliary variable specified by the user will be assigned as the concentration value for groundwater sources (flows with a positive sign).  For negative flow rates (sinks), groundwater will be withdrawn from the cell at the simulated concentration of the cell.  The AUXMIXED option provides an alternative method for how to determine the concentration of sinks.  If the cell concentration is larger than the user-specified auxiliary concentration, then the concentration of groundwater withdrawn from the cell will be assigned as the user-specified concentration.  Alternatively, if the user-specified auxiliary concentration is larger than the cell concentration, then groundwater will be withdrawn at the cell concentration.  Thus, the AUXMIXED option is designed to work with the Evapotranspiration (EVT) and Recharge (RCH) Packages where water may be withdrawn at a concentration that is less than the cell concentration."
optional = false
reader = "urword"
longname = "source type"
type = "string"

[blocks.sources.sources.children.sources.children.auxname]
block = "sources"
description = "name of the auxiliary variable in the package PNAME.  This auxiliary variable must exist and be specified by the user in that package.  The values in this auxiliary variable will be used to set the concentration associated with the flows for that boundary package."
reader = "urword"
optional = false
longname = "auxiliary variable name"
type = "string"

[blocks.fileinput.fileinput]
block = "fileinput"
reader = "urword"
optional = true
type = "list"

[blocks.fileinput.fileinput.children.fileinput]
block = "fileinput"
reader = "urword"
optional = true
type = "record"

[blocks.fileinput.fileinput.children.fileinput.children.pname]
block = "sources"
description = "name of the flow package for which an auxiliary variable contains a source concentration.  If this flow package is represented using an advanced transport package (SFT, LKT, MWT, or UZT), then the advanced transport package will override SSM terms specified here."
reader = "urword"
mf6internal = "pname_sources"
longname = "package name"
type = "string"

[blocks.fileinput.fileinput.children.fileinput.children.spc6]
block = "fileinput"
description = "keyword to specify that record corresponds to a source sink mixing input file."
reader = "urword"
optional = false
longname = "head keyword"
type = "keyword"

[blocks.fileinput.fileinput.children.fileinput.children.filein]
block = "fileinput"
description = "keyword to specify that an input filename is expected next."
reader = "urword"
optional = false
longname = "file keyword"
type = "keyword"

[blocks.fileinput.fileinput.children.fileinput.children.spc6_filename]
block = "fileinput"
description = "character string that defines the path and filename for the file containing source and sink input data for the flow package. The SPC6_FILENAME file is a flexible input file that allows concentrations to be specified by stress period and with time series. Instructions for creating the SPC6_FILENAME input file are provided in the next section on file input for boundary concentrations."
reader = "urword"
optional = false
longname = "spc file name"
type = "string"

[blocks.fileinput.fileinput.children.fileinput.children.mixed]
block = "fileinput"
description = "keyword to specify that these stress package boundaries will have the mixed condition.  The MIXED condition is described in the SOURCES block for AUXMIXED.  The MIXED condition allows for water to be withdrawn at a concentration that is less than the cell concentration.  It is intended primarily for representing evapotranspiration."
reader = "urword"
optional = true
longname = "mixed keyword"
type = "keyword"
