name = "gwt-dis"
schema_version = "2.0.0.dev1"
advanced = false
multi = false
ftype = "DIS"
subcomponents = [
    "utl-ncf",
]

[blocks.options.length_units]
block = "options"
description = "is the length units used for this model.  Values can be 'FEET', 'METERS', or 'CENTIMETERS'.  If not specified, the default is 'UNKNOWN'."
reader = "urword"
optional = true
longname = "model length units"
type = "string"

[blocks.options.nogrb]
block = "options"
description = "keyword to deactivate writing of the binary grid file."
reader = "urword"
optional = true
longname = "do not write binary grid file"
type = "keyword"

[blocks.options.grb_filerecord]
block = "options"
reader = "urword"
optional = true
type = "record"

[blocks.options.grb_filerecord.children.grb6]
block = "options"
description = "keyword to specify that record corresponds to a binary grid file."
reader = "urword"
optional = false
longname = "grb keyword"
type = "keyword"

[blocks.options.grb_filerecord.children.fileout]
block = "options"
description = "keyword to specify that an output filename is expected next."
reader = "urword"
optional = false
longname = "file keyword"
type = "keyword"

[blocks.options.grb_filerecord.children.grb6_filename]
block = "options"
description = "defines a binary grid output file. If this option is not provided, the output file will have the same name as the discretization input file, plus extension '.grb'."
reader = "urword"
optional = false
longname = "file name of GRB information"
type = "string"

[blocks.options.xorigin]
block = "options"
description = "x-position of the lower-left corner of the model grid.  A default value of zero is assigned if not specified.  The value for XORIGIN does not affect the model simulation, but it is written to the binary grid file so that postprocessors can locate the grid in space."
reader = "urword"
optional = true
longname = "x-position of the model grid origin"
type = "double"

[blocks.options.yorigin]
block = "options"
description = "y-position of the lower-left corner of the model grid.  If not specified, then a default value equal to zero is used.  The value for YORIGIN does not affect the model simulation, but it is written to the binary grid file so that postprocessors can locate the grid in space."
reader = "urword"
optional = true
longname = "y-position of the model grid origin"
type = "double"

[blocks.options.angrot]
block = "options"
description = "counter-clockwise rotation angle (in degrees) of the lower-left corner of the model grid.  If not specified, then a default value of 0.0 is assigned.  The value for ANGROT does not affect the model simulation, but it is written to the binary grid file so that postprocessors can locate the grid in space."
reader = "urword"
optional = true
longname = "rotation angle"
type = "double"

[blocks.options.export_array_ascii]
block = "options"
description = "keyword that specifies input griddata arrays should be written to layered ascii output files."
reader = "urword"
optional = true
mf6internal = "export_ascii"
longname = "export array variables to layered ascii files."
type = "keyword"

[blocks.options.export_array_netcdf]
block = "options"
description = "keyword that specifies input gridded arrays should be written to the model output NetCDF file with attributes that support using the generated file as a MODFLOW 6 simulation input.  This option only has an effect when an output model NetCDF file is configured and the simulation is run in VALIDATE mode, otherwise it is ignored."
reader = "urword"
optional = true
mf6internal = "export_nc"
longname = "export array variables to netcdf output files."
extended = true
type = "keyword"

[blocks.options.crs]
shape = "lenbigline"
block = "options"
description = "is a real-world coordinate reference system (CRS) for the model, for example, an EPSG integer code (e.g. 26915), authority string (i.e. epsg:26915), or Open Geospatial Consortium Well-Known Text (WKT) specification. Limited to 5000 characters. The entry for CRS does not affect the model simulation, but it is written to the binary grid file so that postprocessors can locate the grid in space."
reader = "urword"
optional = true
developmode = true
longname = "CRS user input string"
type = "string"

[blocks.options.ncf_filerecord]
block = "options"
reader = "urword"
optional = true
type = "record"

[blocks.options.ncf_filerecord.children.ncf6]
block = "options"
description = "keyword to specify that record corresponds to a NetCDF configuration (NCF) file."
reader = "urword"
optional = false
longname = "ncf keyword"
extended = true
type = "keyword"

[blocks.options.ncf_filerecord.children.filein]
block = "options"
description = "keyword to specify that an input filename is expected next."
reader = "urword"
optional = false
longname = "file keyword"
type = "keyword"

[blocks.options.ncf_filerecord.children.ncf6_filename]
block = "options"
description = "defines a NetCDF configuration (NCF) input file."
reader = "urword"
optional = false
longname = "file name of NCF information"
extended = true
type = "string"

[blocks.dimensions.nlay]
block = "dimensions"
description = "is the number of layers in the model grid."
default = "1"
reader = "urword"
optional = false
longname = "number of layers"
type = "integer"

[blocks.dimensions.nrow]
block = "dimensions"
description = "is the number of rows in the model grid."
default = "2"
reader = "urword"
optional = false
longname = "number of rows"
type = "integer"

[blocks.dimensions.ncol]
block = "dimensions"
description = "is the number of columns in the model grid."
default = "2"
reader = "urword"
optional = false
longname = "number of columns"
type = "integer"

[blocks.griddata.delr]
shape = "(ncol)"
block = "griddata"
description = "is the column spacing in the row direction."
default = "1.0"
reader = "readarray"
netcdf = true
longname = "spacing along a row"
type = "double"

[blocks.griddata.delc]
shape = "(nrow)"
block = "griddata"
description = "is the row spacing in the column direction."
default = "1.0"
reader = "readarray"
netcdf = true
longname = "spacing along a column"
type = "double"

[blocks.griddata.top]
shape = "(ncol, nrow)"
block = "griddata"
description = "is the top elevation for each cell in the top model layer."
default = "1.0"
reader = "readarray"
netcdf = true
longname = "cell top elevation"
type = "double"

[blocks.griddata.botm]
shape = "(ncol, nrow, nlay)"
block = "griddata"
description = "is the bottom elevation for each cell."
default = "0."
reader = "readarray"
netcdf = true
layered = true
longname = "cell bottom elevation"
type = "double"

[blocks.griddata.idomain]
shape = "(ncol, nrow, nlay)"
block = "griddata"
description = "is an optional array that characterizes the existence status of a cell.  If the IDOMAIN array is not specified, then all model cells exist within the solution.  If the IDOMAIN value for a cell is 0, the cell does not exist in the simulation.  Input and output values will be read and written for the cell, but internal to the program, the cell is excluded from the solution.  If the IDOMAIN value for a cell is 1, the cell exists in the simulation.  If the IDOMAIN value for a cell is -1, the cell does not exist in the simulation.  Furthermore, the first existing cell above will be connected to the first existing cell below.  This type of cell is referred to as a 'vertical pass through' cell."
reader = "readarray"
layered = true
netcdf = true
optional = true
longname = "idomain existence array"
type = "integer"
