name = "olf-sto"
schema_version = "2.0.0.dev1"
advanced = false
multi = false
ftype = "STO"

[blocks.options.save_flows]
block = "options"
description = "keyword to indicate that cell-by-cell flow terms will be written to the file specified with 'BUDGET SAVE FILE' in Output Control."
reader = "urword"
optional = true
longname = "keyword to save NPF flows"
mf6internal = "ipakcb"
type = "keyword"

[blocks.options.export_array_ascii]
block = "options"
description = "keyword that specifies input grid arrays, which already support the layered keyword, should be written to layered ascii output files."
reader = "urword"
optional = true
mf6internal = "export_ascii"
longname = "export array variables to layered ascii files."
type = "keyword"

[blocks.period.steady-state]
shape = "(nper)"
block = "period"
description = "keyword to indicate that stress period IPER is steady-state. Steady-state conditions will apply until the TRANSIENT keyword is specified in a subsequent BEGIN PERIOD block."
reader = "urword"
optional = true
longname = "steady state indicator"
mf6internal = "steady_state"
type = "keyword"

[blocks.period.transient]
shape = "(nper)"
block = "period"
description = "keyword to indicate that stress period IPER is transient. Transient conditions will apply until the STEADY-STATE keyword is specified in a subsequent BEGIN PERIOD block."
reader = "urword"
optional = true
longname = "transient indicator"
type = "keyword"
