name = "olf-nam"
schema_version = "2.0.0.dev1"
advanced = false
multi = false
ftype = "NAM"

[blocks.options.list]
block = "options"
description = "is name of the listing file to create for this OLF model.  If not specified, then the name of the list file will be the basename of the OLF model name file and the '.lst' extension.  For example, if the OLF name file is called 'my.model.nam' then the list file will be called 'my.model.lst'."
reader = "urword"
optional = true
longname = "name of listing file"
type = "string"

[blocks.options.print_input]
block = "options"
description = "keyword to indicate that the list of all model stress package information will be written to the listing file immediately after it is read."
reader = "urword"
optional = true
longname = "print input to listing file"
type = "keyword"

[blocks.options.print_flows]
block = "options"
description = "keyword to indicate that the list of all model package flow rates will be printed to the listing file for every stress period time step in which 'BUDGET PRINT' is specified in Output Control.  If there is no Output Control option and 'PRINT_FLOWS' is specified, then flow rates are printed for the last time step of each stress period."
reader = "urword"
optional = true
longname = "print calculated flows to listing file"
type = "keyword"

[blocks.options.save_flows]
block = "options"
description = "keyword to indicate that all model package flow terms will be written to the file specified with 'BUDGET FILEOUT' in Output Control."
reader = "urword"
optional = true
longname = "save flows for all packages to budget file"
type = "keyword"

[blocks.options.newtonoptions]
block = "options"
description = "none"
reader = "urword"
optional = true
longname = "newton keyword and options"
type = "record"

[blocks.options.newtonoptions.children.newton]
block = "options"
description = "keyword that activates the Newton-Raphson formulation for surface water flow between connected reaches and stress packages that support calculation of Newton-Raphson terms."
reader = "urword"
longname = "keyword to activate Newton-Raphson formulation"
type = "keyword"

[blocks.options.newtonoptions.children.under_relaxation]
block = "options"
description = "keyword that indicates whether the surface water stage in a reach will be under-relaxed when water levels fall below the bottom of the model below any given cell. By default, Newton-Raphson UNDER_RELAXATION is not applied."
reader = "urword"
optional = true
longname = "keyword to activate Newton-Raphson UNDER_RELAXATION option"
type = "keyword"

[blocks.packages.packages]
block = "packages"
reader = "urword"
optional = false
longname = "package list"
type = "list"

[blocks.packages.packages.children.packages]
block = "packages"
reader = "urword"
optional = false
longname = "package list"
type = "record"

[blocks.packages.packages.children.packages.children.ftype]
block = "packages"
description = "is the file type, which must be one of the following character values shown in table~ref{table:ftype-olf}. Ftype may be entered in any combination of uppercase and lowercase."
reader = "urword"
longname = "package type"
type = "string"

[blocks.packages.packages.children.packages.children.fname]
block = "packages"
description = "is the name of the file containing the package input.  The path to the file should be included if the file is not located in the folder where the program was run."
reader = "urword"
longname = "file name"
type = "string"

[blocks.packages.packages.children.packages.children.pname]
block = "packages"
description = "is the user-defined name for the package. PNAME is restricted to 16 characters.  No spaces are allowed in PNAME.  PNAME character values are read and stored by the program for stress packages only.  These names may be useful for labeling purposes when multiple stress packages of the same type are located within a single OLF Model.  If PNAME is specified for a stress package, then PNAME will be used in the flow budget table in the listing file; it will also be used for the text entry in the cell-by-cell budget file.  PNAME is case insensitive and is stored in all upper case letters."
reader = "urword"
optional = true
longname = "user name for package"
type = "string"
