name = "prt-oc"
schema_version = "2.0.0.dev1"
advanced = false
multi = false
ftype = "OC"

[blocks.options.budget_filerecord]
block = "options"
reader = "urword"
optional = true
mf6internal = "budfilerec"
type = "record"

[blocks.options.budget_filerecord.children.budget]
block = "options"
description = "keyword to specify that record corresponds to the budget."
reader = "urword"
optional = false
longname = "budget keyword"
type = "keyword"

[blocks.options.budget_filerecord.children.fileout]
block = "options"
description = "keyword to specify that an output filename is expected next."
reader = "urword"
optional = false
longname = "file keyword"
type = "keyword"

[blocks.options.budget_filerecord.children.budgetfile]
block = "options"
description = "name of the output file to write budget information."
reader = "urword"
optional = false
longname = "file keyword"
type = "string"

[blocks.options.budgetcsv_filerecord]
block = "options"
reader = "urword"
optional = true
mf6internal = "budcsvfilerec"
type = "record"

[blocks.options.budgetcsv_filerecord.children.budgetcsv]
block = "options"
description = "keyword to specify that record corresponds to the budget CSV."
reader = "urword"
optional = false
longname = "budget keyword"
type = "keyword"

[blocks.options.budgetcsv_filerecord.children.fileout]
block = "options"
description = "keyword to specify that an output filename is expected next."
reader = "urword"
optional = false
longname = "file keyword"
type = "keyword"

[blocks.options.budgetcsv_filerecord.children.budgetcsvfile]
block = "options"
description = "name of the comma-separated value (CSV) output file to write budget summary information.  A budget summary record will be written to this file for each time step of the simulation."
reader = "urword"
optional = false
longname = "file keyword"
type = "string"

[blocks.options.track_filerecord]
block = "options"
reader = "urword"
optional = true
mf6internal = "trackfilerec"
type = "record"

[blocks.options.track_filerecord.children.track]
block = "options"
description = "keyword to specify that record corresponds to a binary track file.  Each PRT Model's OC Package may have only one binary track output file."
reader = "urword"
optional = false
longname = "track keyword"
type = "keyword"

[blocks.options.track_filerecord.children.fileout]
block = "options"
description = "keyword to specify that an output filename is expected next."
reader = "urword"
optional = false
longname = "file keyword"
type = "keyword"

[blocks.options.track_filerecord.children.trackfile]
block = "options"
description = "name of the binary output file to write tracking information."
reader = "urword"
optional = false
longname = "file keyword"
type = "string"

[blocks.options.trackcsv_filerecord]
block = "options"
reader = "urword"
optional = true
mf6internal = "trackcsvfilerec"
type = "record"

[blocks.options.trackcsv_filerecord.children.trackcsv]
block = "options"
description = "keyword to specify that record corresponds to a CSV track file.  Each PRT Model's OC Package may have only one CSV track file."
reader = "urword"
optional = false
longname = "track keyword"
type = "keyword"

[blocks.options.trackcsv_filerecord.children.fileout]
block = "options"
description = "keyword to specify that an output filename is expected next."
reader = "urword"
optional = false
longname = "file keyword"
type = "keyword"

[blocks.options.trackcsv_filerecord.children.trackcsvfile]
block = "options"
description = "name of the comma-separated value (CSV) file to write tracking information."
reader = "urword"
optional = false
longname = "file keyword"
type = "string"

[blocks.options.track_release]
block = "options"
description = "keyword to indicate that particle tracking output is to be written when a particle is released"
reader = "urword"
optional = true
longname = "track release"
type = "keyword"

[blocks.options.track_exit]
block = "options"
description = "keyword to indicate that particle tracking output is to be written when a particle exits a grid feature (e.g. model, cell)"
reader = "urword"
optional = true
longname = "track domain exits"
type = "keyword"

[blocks.options.track_subfeature_exit]
block = "options"
description = "keyword to indicate that particle tracking output is to be written when a particle exits a sub-grid-scale feature. Such features are considered implementation details of the tracking algorithm employed for particular grid types, and reporting for exit events from such features is disabled by default."
reader = "urword"
optional = true
mf6internal = "track_subf_exit"
longname = "track cell exits"
type = "keyword"

[blocks.options.track_timestep]
block = "options"
description = "keyword to indicate that particle tracking output is to be written at the end of each time step"
reader = "urword"
optional = true
longname = "track timestep ends"
type = "keyword"

[blocks.options.track_terminate]
block = "options"
description = "keyword to indicate that particle tracking output is to be written when a particle terminates for any reason"
reader = "urword"
optional = true
longname = "track termination"
type = "keyword"

[blocks.options.track_weaksink]
block = "options"
description = "keyword to indicate that particle tracking output is to be written when a particle exits a weak sink (a cell which removes some but not all inflow from adjacent cells)"
reader = "urword"
optional = true
longname = "track weaksink exits"
type = "keyword"

[blocks.options.track_usertime]
block = "options"
description = "keyword to indicate that particle tracking output is to be written at user-specified times, provided as double precision values in the TRACKTIMES block."
reader = "urword"
optional = true
longname = "track user-specified times"
type = "keyword"

[blocks.options.track_dropped]
block = "options"
description = "keyword to indicate that particle tracking output is to be written when a particle is dropped to the water table via DRY_TRACKING_METHOD DROP."
reader = "urword"
optional = true
longname = "track drops to water table"
type = "keyword"

[blocks.options.track_timesrecord]
block = "options"
reader = "urword"
optional = true
mf6internal = "ttimesrec"
removed = "6.6.0"
type = "record"

[blocks.options.track_timesrecord.children.track_times]
block = "options"
description = "keyword indicating tracking times will follow"
reader = "urword"
removed = "6.6.0"
type = "keyword"

[blocks.options.track_timesrecord.children.times]
shape = "(any1d)"
block = "options"
description = "times to track, relative to the beginning of the simulation."
reader = "urword"
repeating = true
longname = "tracking times"
removed = "6.6.0"
type = "double"

[blocks.options.track_timesfilerecord]
block = "options"
reader = "urword"
optional = true
mf6internal = "ttimesfilerec"
removed = "6.6.0"
type = "record"

[blocks.options.track_timesfilerecord.children.track_timesfile]
block = "options"
description = "keyword indicating tracking times file name will follow"
reader = "urword"
removed = "6.6.0"
type = "keyword"

[blocks.options.track_timesfilerecord.children.timesfile]
block = "options"
description = "name of the tracking times file"
reader = "urword"
optional = false
longname = "file keyword"
removed = "6.6.0"
type = "string"

[blocks.options.dev_dump_event_trace]
block = "options"
description = "print a verbose particle tracking event trace to standard output"
reader = "urword"
optional = true
mf6internal = "dev_dump_evtrace"
longname = "print particle tracking events"
type = "keyword"

[blocks.options.scratch_buffer]
block = "options"
description = "keyword to stage track events in a temporary (scratch) file instead of an in-memory buffer. Particle tracking results calculated during a time step are buffered, and output is deferred, until successful completion of the time step. By default, results are buffered in memory. However, for simulations in which a very large number of track events is generated during a time step, memory limits can be exceeded. In such cases, the SCRATCH_BUFFER option can be invoked to buffer results in a scratch file until successful completion of the time step. Buffering in a scratch file is typically slower than buffering in memory."
reader = "urword"
optional = true
longname = "buffer track events in scratch file instead of memory"
type = "keyword"

[blocks.dimensions.ntracktimes]
block = "dimensions"
description = "is the number of user-specified particle tracking times in the TRACKTIMES block."
reader = "urword"
optional = true
longname = "number of particle tracking times"
type = "integer"

[blocks.tracktimes.tracktimes]
shape = "(ntracktimes)"
block = "tracktimes"
reader = "urword"
optional = true
type = "list"

[blocks.tracktimes.tracktimes.children.tracktimes]
shape = "(ntracktimes)"
block = "tracktimes"
reader = "urword"
optional = true
type = "record"

[blocks.tracktimes.tracktimes.children.tracktimes.children.time]
block = "tracktimes"
description = "real value that defines the tracking time with respect to the simulation start time."
reader = "urword"
optional = false
longname = "release time"
type = "double"

[blocks.period.saverecord]
shape = "(nper)"
block = "period"
reader = "urword"
optional = true
type = "record"

[blocks.period.saverecord.children.save]
block = "period"
description = "keyword to indicate that information will be saved this stress period."
reader = "urword"
optional = false
longname = "keyword to save"
type = "keyword"

[blocks.period.saverecord.children.rtype]
block = "period"
description = "type of information to save or print.  Can only be BUDGET."
reader = "urword"
optional = false
longname = "record type"
type = "string"

[blocks.period.saverecord.children.ocsetting]
block = "period"
description = "specifies the steps for which the data will be saved."
reader = "urword"
type = "union"

[blocks.period.saverecord.children.ocsetting.children.all]
block = "period"
description = "keyword to indicate save for all time steps in period."
reader = "urword"
type = "keyword"

[blocks.period.saverecord.children.ocsetting.children.first]
block = "period"
description = "keyword to indicate save for first step in period. This keyword may be used in conjunction with other keywords to print or save results for multiple time steps."
reader = "urword"
type = "keyword"

[blocks.period.saverecord.children.ocsetting.children.last]
block = "period"
description = "keyword to indicate save for last step in period. This keyword may be used in conjunction with other keywords to print or save results for multiple time steps."
reader = "urword"
type = "keyword"

[blocks.period.saverecord.children.ocsetting.children.frequency]
block = "period"
description = "save at the specified time step frequency. This keyword may be used in conjunction with other keywords to print or save results for multiple time steps."
reader = "urword"
type = "integer"

[blocks.period.saverecord.children.ocsetting.children.steps]
shape = "(<nstp)"
block = "period"
description = "save for each step specified in STEPS. This keyword may be used in conjunction with other keywords to print or save results for multiple time steps."
reader = "urword"
type = "integer"

[blocks.period.printrecord]
shape = "(nper)"
block = "period"
reader = "urword"
optional = true
type = "record"

[blocks.period.printrecord.children.print]
block = "period"
description = "keyword to indicate that information will be printed this stress period."
reader = "urword"
optional = false
longname = "keyword to save"
type = "keyword"

[blocks.period.printrecord.children.rtype]
block = "period"
description = "type of information to save or print.  Can only be BUDGET."
reader = "urword"
optional = false
longname = "record type"
type = "string"

[blocks.period.printrecord.children.ocsetting]
block = "period"
description = "specifies the steps for which the data will be saved."
reader = "urword"
type = "union"

[blocks.period.printrecord.children.ocsetting.children.all]
block = "period"
description = "keyword to indicate save for all time steps in period."
reader = "urword"
type = "keyword"

[blocks.period.printrecord.children.ocsetting.children.first]
block = "period"
description = "keyword to indicate save for first step in period. This keyword may be used in conjunction with other keywords to print or save results for multiple time steps."
reader = "urword"
type = "keyword"

[blocks.period.printrecord.children.ocsetting.children.last]
block = "period"
description = "keyword to indicate save for last step in period. This keyword may be used in conjunction with other keywords to print or save results for multiple time steps."
reader = "urword"
type = "keyword"

[blocks.period.printrecord.children.ocsetting.children.frequency]
block = "period"
description = "save at the specified time step frequency. This keyword may be used in conjunction with other keywords to print or save results for multiple time steps."
reader = "urword"
type = "integer"

[blocks.period.printrecord.children.ocsetting.children.steps]
shape = "(<nstp)"
block = "period"
description = "save for each step specified in STEPS. This keyword may be used in conjunction with other keywords to print or save results for multiple time steps."
reader = "urword"
type = "integer"
