name = "sim-tdis"
schema_version = "2.0.0.dev1"
advanced = false
multi = false
ftype = "TDIS"

[blocks.options.time_units]
block = "options"
description = "is the time units of the simulation.  This is a text string that is used as a label within model output files.  Values for time_units may be 'unknown',  'seconds', 'minutes', 'hours', 'days', or 'years'.  The default time unit is 'unknown'."
reader = "urword"
optional = true
longname = "time unit"
type = "string"

[blocks.options.start_date_time]
block = "options"
description = "is the starting date and time of the simulation.  This is a text string that is used as a label within the simulation list file.  The value has no effect on the simulation.  The recommended format for the starting date and time is described at https://www.w3.org/TR/NOTE-datetime."
reader = "urword"
optional = true
longname = "starting date and time"
type = "string"

[blocks.options.ats_filerecord]
block = "options"
reader = "urword"
optional = true
type = "record"

[blocks.options.ats_filerecord.children.ats6]
block = "options"
description = "keyword to specify that record corresponds to an adaptive time step (ATS) input file.  The behavior of ATS and a description of the input file is provided separately."
reader = "urword"
optional = false
longname = "ats keyword"
type = "keyword"

[blocks.options.ats_filerecord.children.filein]
block = "options"
description = "keyword to specify that an input filename is expected next."
reader = "urword"
optional = false
longname = "file keyword"
type = "keyword"

[blocks.options.ats_filerecord.children.ats6_filename]
block = "options"
description = "defines an adaptive time step (ATS) input file defining ATS controls.  Records in the ATS file can be used to override the time step behavior for selected stress periods."
reader = "urword"
optional = false
longname = "file name of adaptive time series information"
type = "string"

[blocks.dimensions.nper]
block = "dimensions"
description = "is the number of stress periods for the simulation."
default = "1"
reader = "urword"
optional = false
longname = "number of stress periods"
type = "integer"

[blocks.perioddata.perioddata]
block = "perioddata"
default = "((1.0, 1, 1.0),)"
reader = "urword"
optional = false
longname = "stress period time information"
type = "list"

[blocks.perioddata.perioddata.children.perioddata]
block = "perioddata"
default = "((1.0, 1, 1.0),)"
reader = "urword"
optional = false
longname = "stress period time information"
type = "record"

[blocks.perioddata.perioddata.children.perioddata.children.perlen]
block = "perioddata"
description = "is the length of a stress period."
reader = "urword"
optional = false
longname = "length of stress period"
type = "double"

[blocks.perioddata.perioddata.children.perioddata.children.nstp]
block = "perioddata"
description = "is the number of time steps in a stress period."
reader = "urword"
optional = false
longname = "number of time steps"
type = "integer"

[blocks.perioddata.perioddata.children.perioddata.children.tsmult]
block = "perioddata"
description = "is the multiplier for the length of successive time steps. The length of a time step is calculated by multiplying the length of the previous time step by TSMULT. The length of the first time step, $Delta t_1$, is related to PERLEN, NSTP, and TSMULT by the relation $Delta t_1= perlen frac{tsmult - 1}{tsmult^{nstp}-1}$."
reader = "urword"
optional = false
longname = "number of time steps"
type = "double"
