name = "utl-ts"
schema_version = "2.0.0.dev1"
parent = "parent_package"
advanced = false
multi = true
ftype = "TS"

[blocks.attributes.time_series_namerecord]
block = "attributes"
description = "xxx"
reader = "urword"
optional = false
type = "record"

[blocks.attributes.time_series_namerecord.children.names]
block = "attributes"
description = "xxx"
other_names = "name"
reader = "urword"
optional = false
type = "keyword"

[blocks.attributes.time_series_namerecord.children.time_series_names]
shape = "(any1d)"
block = "attributes"
description = "Name by which a package references a particular time-array series. The name must be unique among all time-array series used in a package."
reader = "urword"
optional = false
type = "string"

[blocks.attributes.interpolation_methodrecord]
block = "attributes"
description = "xxx"
reader = "urword"
optional = true
type = "record"

[blocks.attributes.interpolation_methodrecord.children.methods]
block = "attributes"
description = " xxx"
reader = "urword"
optional = false
type = "keyword"

[blocks.attributes.interpolation_methodrecord.children.interpolation_method]
shape = "(time_series_names)"
block = "attributes"
description = "Interpolation method, which is either STEPWISE or LINEAR."
valid = "stepwise linear linearend"
reader = "urword"
optional = false
type = "string"

[blocks.attributes.interpolation_methodrecord_single]
block = "attributes"
description = "xxx"
reader = "urword"
optional = true
type = "record"

[blocks.attributes.method]
block = "attributes"
description = " xxx"
reader = "urword"
optional = false
type = "keyword"

[blocks.attributes.interpolation_method_single]
block = "attributes"
description = "Interpolation method, which is either STEPWISE or LINEAR."
valid = "stepwise linear linearend"
reader = "urword"
optional = false
type = "string"

[blocks.attributes.sfacrecord]
block = "attributes"
description = "xxx"
reader = "urword"
optional = true
type = "record"

[blocks.attributes.sfacrecord.children.sfacs]
block = "attributes"
description = " xxx"
reader = "urword"
optional = false
type = "keyword"

[blocks.attributes.sfacrecord.children.sfacval]
shape = "(<time_series_name)"
block = "attributes"
description = "Scale factor, which will multiply all array values in time series. SFAC is an optional attribute; if omitted, SFAC = 1.0."
reader = "urword"
optional = false
type = "double"

[blocks.attributes.sfacrecord_single]
block = "attributes"
description = "xxx"
reader = "urword"
optional = true
type = "record"

[blocks.attributes.sfacrecord_single.children.sfacval]
shape = "(<time_series_name)"
block = "attributes"
description = "Scale factor, which will multiply all array values in time series. SFAC is an optional attribute; if omitted, SFAC = 1.0."
reader = "urword"
optional = false
type = "double"

[blocks.attributes.sfac]
block = "attributes"
description = " xxx"
reader = "urword"
optional = false
type = "keyword"

[blocks.timeseries.timeseries]
block = "timeseries"
description = "xxx"
reader = "urword"
optional = false
type = "list"

[blocks.timeseries.timeseries.children.timeseries]
block = "timeseries"
description = "xxx"
reader = "urword"
optional = false
type = "record"

[blocks.timeseries.timeseries.children.timeseries.children.ts_time]
block = "timeseries"
description = "A numeric time relative to the start of the simulation, in the time unit used in the simulation. Times must be strictly increasing."
reader = "urword"
optional = false
repeating = false
type = "double"

[blocks.timeseries.timeseries.children.timeseries.children.ts_array]
shape = "(time_series_names)"
block = "timeseries"
description = "A 2-D array of numeric, floating-point values, or a constant value, readable by the U2DREL array-reading utility."
reader = "urword"
optional = false
type = "double"
