name = "utl-tvk"
schema_version = "2.0.0.dev1"
parent = "parent_package"
advanced = false
multi = false
ftype = "TVK"

[blocks.options.print_input]
block = "options"
description = "keyword to indicate that information for each change to the hydraulic conductivity in a cell will be written to the model listing file."
reader = "urword"
optional = true
longname = "print input to listing file"
type = "keyword"

[blocks.options.ts_filerecord]
block = "options"
reader = "urword"
optional = true
type = "record"

[blocks.options.ts_filerecord.children.ts6]
block = "options"
description = "keyword to specify that record corresponds to a time-series file."
reader = "urword"
optional = false
longname = "head keyword"
type = "keyword"

[blocks.options.ts_filerecord.children.filein]
block = "options"
description = "keyword to specify that an input filename is expected next."
reader = "urword"
optional = false
longname = "file keyword"
type = "keyword"

[blocks.options.ts_filerecord.children.ts6_filename]
block = "options"
description = "defines a time-series file defining time series that can be used to assign time-varying values. See the 'Time-Variable Input' section for instructions on using the time-series capability."
reader = "urword"
optional = false
longname = "file name of time series information"
type = "string"

[blocks.period.tvksetting]
shape = "(nper, nnodes)"
block = "period"
description = "line of information that is parsed into a property name keyword and values.  Property name keywords that can be used to start the TVKSETTING string include: K, K22, and K33."
reader = "urword"
type = "union"

[blocks.period.tvksetting.children.k]
block = "period"
description = "is the new value to be assigned as the cell's hydraulic conductivity from the start of the specified stress period, as per K in the NPF package.  If the OPTIONS block includes a TS6 entry (see the 'Time-Variable Input' section), values can be obtained from a time series by entering the time-series name in place of a numeric value."
reader = "urword"
time_series = true
longname = "hydraulic conductivity (L/T)"
type = "double"

[blocks.period.tvksetting.children.k22]
block = "period"
description = "is the new value to be assigned as the cell's hydraulic conductivity of the second ellipsoid axis (or the ratio of K22/K if the K22OVERK NPF package option is specified) from the start of the specified stress period, as per K22 in the NPF package.  For an unrotated case this is the hydraulic conductivity in the y direction.  If the OPTIONS block includes a TS6 entry (see the 'Time-Variable Input' section), values can be obtained from a time series by entering the time-series name in place of a numeric value."
reader = "urword"
time_series = true
longname = "hydraulic conductivity of second ellipsoid axis (L/T)"
type = "double"

[blocks.period.tvksetting.children.k33]
block = "period"
description = "is the new value to be assigned as the cell's hydraulic conductivity of the third ellipsoid axis (or the ratio of K33/K if the K33OVERK NPF package option is specified) from the start of the specified stress period, as per K33 in the NPF package.  For an unrotated case, this is the vertical hydraulic conductivity.  If the OPTIONS block includes a TS6 entry (see the 'Time-Variable Input' section), values can be obtained from a time series by entering the time-series name in place of a numeric value."
reader = "urword"
time_series = true
longname = "hydraulic conductivity of third ellipsoid axis (L/T)"
type = "double"
