[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "modflow-devtools"
description = "Python tools for MODFLOW development"
authors = [
    {name = "Joseph D. Hughes", email = "modflow@usgs.gov"},
    {name = "Michael Reno", email = "mreno@ucar.edu"},
    {name = "Mike Taves", email = "mwtoews@gmail.com"},
    {name = "Wes Bonelli", email = "wbonelli@ucar.edu"},
]
maintainers = [
    {name = "Joseph D. Hughes", email = "modflow@usgs.gov"},
]
keywords = [
    "MODFLOW",
    "development",
    "utilities",
    "groundwater",
    "hydrogeology"
]
readme = "README.md"
license = {text = "CC0"}
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Science/Research",
    "License :: CC0 1.0 Universal (CC0 1.0) Public Domain Dedication",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Topic :: Scientific/Engineering :: Hydrology"
]
requires-python = ">=3.11"
dynamic = ["version"]

[project.optional-dependencies]
build = [
    "build",
    "twine"
]
lint = [
    "codespell[toml]",
    "ruff",
    "mypy"
]
test = [
    "modflow-devtools[lint]",
    "coverage",
    "flaky",
    "filelock",
    "meson!=0.63.0",
    "ninja",
    "numpy",
    "pandas",
    "pytest!=8.1.0",
    "pytest-cov",
    "pytest-dotenv",
    "pytest-xdist",
    "PyYaml",
    "syrupy <5.0.0"
]
docs = [
    "sphinx",
    "sphinx-rtd-theme",
    "myst-parser"
]
# deprecated
dfn = [
    "boltons",
    "pooch",
    "pyaml",
    "pydantic",
    "tomli",
    "tomli-w"
]
# deprecated
models = [
    "boltons",
    "filelock",
    "pooch",
    "pyaml",
    "pydantic",
    "tomli",
    "tomli-w"
]
# prefer ecosystem to dfn/models separately
ecosystem = ["modflow-devtools[dfn,models]"]
dev = ["modflow-devtools[lint,test,docs,dfn,models]"]

[dependency-groups]
build = [
    "build",
    "twine"
]
lint = [
    "codespell[toml]",
    "ruff",
    "mypy",
]
test = [
    "modflow-devtools[lint]",
    "coverage",
    "flaky",
    "filelock",
    "meson!=0.63.0",
    "ninja",
    "numpy",
    "pandas",
    "pytest!=8.1.0",
    "pytest-cov",
    "pytest-dotenv",
    "pytest-xdist",
    "PyYaml",
    "syrupy <5.0.0"
]
docs = [
    "sphinx",
    "sphinx-rtd-theme",
    "myst-parser"
]
# deprecated
dfn = [
    "boltons",
    "pooch",
    "pyaml",
    "pydantic",
    "tomli",
    "tomli-w"
]
# deprecated
models = [
    "boltons",
    "filelock",
    "pooch",
    "pyaml",
    "pydantic",
    "tomli",
    "tomli-w"
]
# prefer ecosystem to dfn/models separately
ecosystem = [
    {include-group = "dfn"},
    {include-group = "models"},
]
dev = [
    {include-group = "build"},
    {include-group = "lint"},
    {include-group = "test"},
    {include-group = "docs"},
    {include-group = "dfn"},
    {include-group = "models"},
]

[project.urls]
"Documentation" = "https://modflow-devtools.readthedocs.io/en/latest/"
"Bug Tracker" = "https://github.com/MODFLOW-ORG/modflow-devtools/issues"
"Source Code" = "https://github.com/MODFLOW-ORG/modflow-devtools"

[project.scripts]
mf = "modflow_devtools.cli:main"

[tool.hatch.build.targets.sdist]
only-include = ["modflow_devtools"]
core-metadata-version = "2.4"

[tool.hatch.build.targets.wheel]
packages = ["modflow_devtools"]
core-metadata-version = "2.4"

[tool.hatch.build]
include = [
    "modflow_devtools/dfn/*.toml",
    "modflow_devtools/registry/*"
]

[tool.hatch.version]
path = "modflow_devtools/__init__.py"

[tool.codespell]
skip = "cliff.toml,./modflow_devtools/registry/**,./docs/_build/**,./autotest/temp/**,./build/**,./autotest/dfns/__snapshots__/**"
ignore-words-list = [
    "nam",
    "wel",
    "gage",
    "sav",
    "registr",
]

[tool.ruff]
line-length = 100

[tool.ruff.lint]
select = [
    "C4",   # flake8 comprehensions
    "D409", # pydocstyle - section-underline-matches-section-length
    "E", "W", # pycodestyle
    "F",    # Pyflakes
    "I",    # isort 
    "PTH",  # flake8-use-pathlib
    "RUF",  # Ruff-specific rules
    "UP",   # pyupgrade
]

[tool.ruff.lint.per-file-ignores]
"modflow_devtools/zip.py" = ["PTH"]

[tool.pytest.ini_options]
addopts = ["--import-mode=importlib"]

[tool.mypy]
mypy_path = "modflow_devtools"
ignore_missing_imports = true
warn_unreachable = true
