__author__ = "Joseph D. Hughes"
__date__ = "Feb 15, 2023"
__version__ = "0.1.7"
__maintainer__ = "Joseph D. Hughes"
__email__ = "jdhughes@usgs.gov"
__status__ = "Production"
__description__ = """Python tools for MODFLOW development and testing."""
