__author__ = "Joseph D. Hughes"
__date__ = "Feb 19, 2024"
__version__ = "1.5.0.dev0"
__maintainer__ = "Joseph D. Hughes"
__email__ = "jdhughes@usgs.gov"
__status__ = "Production"
__description__ = """Python tools for MODFLOW development and testing."""
