type = "package"
schema_version = "2.0.0.dev3"
name = "prt-fmi"
parent = "prt-nam"

[blocks.options.fields.save_flows]
type = "keyword"
longname = "save cell-by-cell flows to budget file"
description = "keyword to indicate that FMI flow terms will be written to the file specified with 'BUDGET FILEOUT' in Output Control."
optional = true

[blocks.packagedata.fields.gwfhead]
type = "file"
longname = "gwf head file"
optional = true
direction = "in"

[blocks.packagedata.fields.gwfbudget]
type = "file"
longname = "gwf budget file"
optional = true
direction = "in"

[blocks.packagedata.fields.gwfgrid]
type = "file"
longname = "gwf grid file"
optional = true
direction = "in"
