type = "package"
schema_version = "2.0.0.dev3"
name = "swf-ic"
parent = "swf-nam"

[dims.nodes]
set_in = "ar"

[blocks.options.fields.export_array_ascii]
type = "keyword"
longname = "export array variables to layered ascii files."
description = "keyword that specifies input griddata arrays should be written to layered ascii output files."
optional = true

[blocks.griddata.fields.strt]
type = "array"
longname = "starting concentration"
description = "is the initial (starting) stage---that is, stage at the beginning of the SWF Model simulation.  STRT must be specified for all SWF Model simulations. One value is read for every model reach."
default = 0.0
dtype = "double"
layered = true
shape = [
    "nodes",
]

[memory.export_ascii]
set_in = "ar"
source = "export_array_ascii"
type = "logical"

[memory.strt]
type = "array"
set_in = "ar"
source = "strt"
dtype = "double"
shape = [
    "nodes",
]
