type = "package"
schema_version = "2.0.0.dev3"
name = "utl-tvs"
parent = "package"
subtype = "utility"

[blocks.options.fields.disable_storage_change_integration]
type = "keyword"
longname = "deactivate storage change integration"
description = "keyword that deactivates inclusion of storage derivative terms in the STO package matrix formulation.  In the absence of this keyword (the default), the groundwater storage formulation will be modified to correctly adjust heads based on transient variations in stored water volumes arising from changes to SS and SY properties."
optional = true

[blocks.options.fields.print_input]
type = "keyword"
longname = "print input to listing file"
description = "keyword to indicate that information for each change to a storage property in a cell will be written to the model listing file."
optional = true

[blocks.options.fields.ts_filerecord]
type = "record"
optional = true

[blocks.options.fields.ts_filerecord.fields.ts6]
type = "keyword"
longname = "head keyword"
description = "keyword to specify that record corresponds to a time-series file."

[blocks.options.fields.ts_filerecord.fields.ts6_filename]
type = "file"
longname = "file name of time series information"
description = "defines a time-series file defining time series that can be used to assign time-varying values. See the 'Time-Variable Input' section for instructions on using the time-series capability."
tagged = false
direction = "in"

[blocks.period.fields.perioddata]
type = "list"

[blocks.period.fields.perioddata.item]
type = "record"

[blocks.period.fields.perioddata.item.fields.cellid]
type = "array"
longname = "cell identifier"
description = "is the cell identifier, and depends on the type of grid that is used for the simulation.  For a structured grid that uses the DIS input file, CELLID is the layer, row, and column.   For a grid that uses the DISV input file, CELLID is the layer and CELL2D number.  If the model uses the unstructured discretization (DISU) input file, CELLID is the node number for the cell."
tagged = false
dtype = "integer"
shape = [
    "ncelldim",
]

[blocks.period.fields.perioddata.item.fields.tvssetting]
type = "union"
description = "line of information that is parsed into a property name keyword and values.  Property name keywords that can be used to start the TVSSETTING string include: SS and SY."

[blocks.period.fields.perioddata.item.fields.tvssetting.arms.ss]
type = "double"
longname = "specific storage"
description = "is the new value to be assigned as the cell's specific storage (or storage coefficient if the STORAGECOEFFICIENT STO package option is specified) from the start of the specified stress period, as per SS in the STO package.  Specific storage values must be greater than or equal to 0.  If the OPTIONS block includes a TS6 entry (see the 'Time-Variable Input' section), values can be obtained from a time series by entering the time-series name in place of a numeric value."
time_series = true

[blocks.period.fields.perioddata.item.fields.tvssetting.arms.sy]
type = "double"
longname = "specific yield"
description = "is the new value to be assigned as the cell's specific yield from the start of the specified stress period, as per SY in the STO package.  Specific yield values must be greater than or equal to 0.  If the OPTIONS block includes a TS6 entry (see the 'Time-Variable Input' section), values can be obtained from a time series by entering the time-series name in place of a numeric value."
time_series = true

[blocks.period.header]
name = "iper"
type = "integer"
longname = "stress period number"
description = "integer value specifying the starting stress period number for which the data specified in the PERIOD block apply.  IPER must be less than or equal to NPER in the TDIS Package and greater than zero.  The IPER value assigned to a stress period block must be greater than the IPER value assigned for the previous PERIOD block.  The information specified in the PERIOD block will continue to apply for all subsequent stress periods, unless the program encounters another PERIOD block."
tagged = false
