name = "chf-evp"
schema_version = "2"
multi = true
subtype = "stress"

[blocks.options]
name = "options"

[blocks.options.fields.auxiliary]
name = "auxiliary"
longname = "keyword to specify aux variables"
description = "defines an array of one or more auxiliary variable names.  there is no limit on the number of auxiliary variables that can be provided on this line; however, lists of information provided in subsequent blocks must have a column of data for each auxiliary variable name defined here.   the number of auxiliary variables detected on this line determines the value for naux.  comments cannot be provided anywhere on this line as they will be interpreted as auxiliary variable names.  auxiliary variables may not be used by the package, but they will be available for use by other parts of the program.  the program will terminate with an error if auxiliary variables are specified on more than one line in the options block."
optional = true
dtype = "string"

[blocks.options.fields.auxmultname]
name = "auxmultname"
longname = "name of auxiliary variable for multiplier"
description = "name of auxiliary variable to be used as multiplier of evaporation."
optional = true
tagged = false

[blocks.options.fields.boundnames]
name = "boundnames"
description = "keyword to indicate that boundary names may be provided with the list of evaporation cells."
optional = true

[blocks.options.fields.print_input]
name = "print_input"
longname = "print input to listing file"
description = "keyword to indicate that the list of evaporation information will be written to the listing file immediately after it is read."
optional = true

[blocks.options.fields.print_flows]
name = "print_flows"
longname = "print evaporation rates to listing file"
description = "keyword to indicate that the list of evaporation flow rates will be printed to the listing file for every stress period time step in which 'budget print' is specified in output control.  if there is no output control option and 'print_flows' is specified, then flow rates are printed for the last time step of each stress period."
optional = true

[blocks.options.fields.save_flows]
name = "save_flows"
longname = "save evaporation to budget file"
description = "keyword to indicate that evaporation flow terms will be written to the file specified with 'budget fileout' in output control."
optional = true

[blocks.options.fields.ts_filerecord]
name = "ts_filerecord"
optional = true

[blocks.options.fields.ts_filerecord.fields.ts6]
name = "ts6"
longname = "head keyword"
description = "keyword to specify that record corresponds to a time-series file."

[blocks.options.fields.ts_filerecord.fields.filein]
name = "filein"
longname = "file keyword"
description = "keyword to specify that an input filename is expected next."

[blocks.options.fields.ts_filerecord.fields.ts6_filename]
name = "ts6_filename"
longname = "file name of time series information"
description = "defines a time-series file defining time series that can be used to assign time-varying values. see the 'time-variable input' section for instructions on using the time-series capability."
tagged = false
case_sensitive = true

[blocks.options.fields.obs_filerecord]
name = "obs_filerecord"
optional = true

[blocks.options.fields.obs_filerecord.fields.obs6]
name = "obs6"
longname = "obs keyword"
description = "keyword to specify that record corresponds to an observations file."

[blocks.options.fields.obs_filerecord.fields.filein]
name = "filein"
longname = "file keyword"
description = "keyword to specify that an input filename is expected next."

[blocks.options.fields.obs_filerecord.fields.obs6_filename]
name = "obs6_filename"
longname = "obs6 input filename"
description = "name of input file to define observations for the evp package. see the 'observation utility' section for instructions for preparing observation input files. table {#2} lists observation type(s) supported by the evp package."
tagged = false
case_sensitive = true

[blocks.dimensions]
name = "dimensions"

[blocks.dimensions.fields.maxbound]
name = "maxbound"
longname = "maximum number of evaporation cells"
description = "integer value specifying the maximum number of evaporation cells that will be specified for use during any stress period."
tagged = false

[blocks.period]
name = "period"

[blocks.period.fields.stress_period_data]
name = "stress_period_data"

[blocks.period.fields.stress_period_data.item]
name = "stress_period_data"

[blocks.period.fields.stress_period_data.item.fields.cellid]
name = "cellid"
longname = "cell identifier"
description = "is the cell identifier, and depends on the type of grid that is used for the simulation.  for a structured grid that uses the dis input file, cellid is the layer, row, and column.   for a grid that uses the disv input file, cellid is the layer and cell2d number.  if the model uses the unstructured discretization (disu) input file, cellid is the node number for the cell."
dtype = "integer"
shape = [
    "ncelldim",
]

[blocks.period.fields.stress_period_data.item.fields.evaporation]
name = "evaporation"
longname = "evaporation rate"
description = "is the evaporation flux rate ($lt^{-1}$).  this rate is multiplied inside the program by the water surface area of the cell to calculate the volumetric evaporation rate. if the options block includes a timeseriesfile entry (see the 'time-variable input' section), values can be obtained from a time series by entering the time-series name in place of a numeric value."
tagged = false
time_series = true

[blocks.period.fields.stress_period_data.item.fields.aux]
name = "aux"
longname = "auxiliary variables"
description = "represents the values of the auxiliary variables for each evaporation. the values of auxiliary variables must be present for each evaporation. the values must be specified in the order of the auxiliary variables specified in the options block.  if the package supports time series and the options block includes a timeseriesfile entry (see the 'time-variable input' section), values can be obtained from a time series by entering the time-series name in place of a numeric value."
optional = true
dtype = "double"
shape = [
    "auxiliary",
]
time_series = true

[blocks.period.fields.stress_period_data.item.fields.boundname]
name = "boundname"
longname = "evaporation name"
description = "name of the evaporation cell.  boundname is an ascii character variable that can contain as many as 40 characters.  if boundname contains spaces in it, then the entire name must be enclosed within single quotes."
optional = true
tagged = false

[dims.maxbound]
field = "maxbound"
scope = "chf"

[dims.auxiliary]
field = "auxiliary"
scope = "component"
