name = "exg-chfgwf"
schema_version = "2"
multi = true
subtype = "exchange"

[blocks.options]
name = "options"

[blocks.options.fields.print_input]
name = "print_input"
longname = "keyword to print input to list file"
description = "keyword to indicate that the list of exchange entries will be echoed to the listing file immediately after it is read."
optional = true

[blocks.options.fields.print_flows]
name = "print_flows"
longname = "keyword to print chfgwf flows to list file"
description = "keyword to indicate that the list of exchange flow rates will be printed to the listing file for every stress period in which 'save budget' is specified in output control."
optional = true

[blocks.options.fields.fixed_conductance]
name = "fixed_conductance"
longname = "keyword to indicate conductance is fixed"
description = "keyword to indicate that the product of the bedleak and cfact input variables in the exchangedata block represents conductance.  this conductance is fixed and does not change as a function of head in the surface water and groundwater models."
optional = true

[blocks.options.fields.obs_filerecord]
name = "obs_filerecord"
optional = true

[blocks.options.fields.obs_filerecord.fields.obs6]
name = "obs6"
longname = "obs keyword"
description = "keyword to specify that record corresponds to an observations file."

[blocks.options.fields.obs_filerecord.fields.filein]
name = "filein"
longname = "file keyword"
description = "keyword to specify that an input filename is expected next."

[blocks.options.fields.obs_filerecord.fields.obs6_filename]
name = "obs6_filename"
longname = "obs6 input filename"
description = "is the file name of the observations input file for this exchange. see the 'observation utility' section for instructions for preparing observation input files. table ref{table:gwf-obstypetable} lists observation type(s) supported by the swf-gwf package."
tagged = false
case_sensitive = true

[blocks.dimensions]
name = "dimensions"

[blocks.dimensions.fields.nexg]
name = "nexg"
longname = "number of exchanges"
description = "keyword and integer value specifying the number of swf-gwf exchanges."
tagged = false

[blocks.exchangedata]
name = "exchangedata"

[blocks.exchangedata.fields.exchangedata]
name = "exchangedata"
longname = "exchange data"

[blocks.exchangedata.fields.exchangedata.item]
name = "exchangedata"

[blocks.exchangedata.fields.exchangedata.item.fields.cellidm1]
name = "cellidm1"
longname = "cellid of cell in surface water model"
description = "is the cellid of the cell in model 1, which must be the surface water model. for a structured grid that uses the dis input file, cellidm1 is the layer, row, and column numbers of the cell.   for a grid that uses the disv input file, cellidm1 is the layer number and cell2d number for the two cells.  if the model uses the unstructured discretization (disu) input file, then cellidm1 is the node number for the cell."
tagged = false

[blocks.exchangedata.fields.exchangedata.item.fields.cellidm2]
name = "cellidm2"
longname = "cellid of cell in groundwater model"
description = "is the cellid of the cell in model 2, which must be the groundwater model. for a structured grid that uses the dis input file, cellidm2 is the layer, row, and column numbers of the cell.   for a grid that uses the disv input file, cellidm2 is the layer number and cell2d number for the two cells.  if the model uses the unstructured discretization (disu) input file, then cellidm2 is the node number for the cell."
tagged = false

[blocks.exchangedata.fields.exchangedata.item.fields.bedleak]
name = "bedleak"
longname = "bed leakance"
description = "is the leakance between the surface water and groundwater.  bedleak has dimensions of 1/t and is equal to the hydraulic conductivity of the bed sediments divided by the thickness of the bed sediments."
tagged = false

[blocks.exchangedata.fields.exchangedata.item.fields.cfact]
name = "cfact"
longname = "factor used for conductance calculation"
description = "is the factor used for the conductance calculation.  the definition for this parameter depends the type of surface water model and whether or not the fixed_conductance option is specified.  if the fixed_conductance option is specified, then the hydraulic conductance is calculated as the product of bedleak and cfact.  in this case, the conductance is fixed and does not change as a function of the calculated surface water and groundwater head.  if the fixed_conductance option is not specified, then the definition of cfact depends on whether the surface water model represents one-dimensional channel flow or two-dimensional overland flow.  if the surface water model represents one-dimensional channel flow, then cfact is the length of the channel cell in the groundwater model cell.  if the surface water model represents two-dimensional overland flow, then cfact is the intersection area of the overland flow cell and the underlying groundwater model cell."
tagged = false

[dims.nexg]
field = "nexg"
scope = "component"
