name = "exg-gwfgwf"
schema_version = "2"
multi = true
subtype = "exchange"

[blocks.options]
name = "options"

[blocks.options.fields.auxiliary]
name = "auxiliary"
longname = "keyword to specify aux variables"
description = "an array of auxiliary variable names.  there is no limit on the number of auxiliary variables that can be provided. most auxiliary variables will not be used by the gwf-gwf exchange, but they will be available for use by other parts of the program.  if an auxiliary variable with the name 'angldegx' is found, then this information will be used as the angle (provided in degrees) between the connection face normal and the x axis, where a value of zero indicates that a normal vector points directly along the positive x axis.  the connection face normal is a normal vector on the cell face shared between the cell in model 1 and the cell in model 2 pointing away from the model 1 cell.  additional information on 'angldegx' and when it is required is provided in the description of the disu package.  if an auxiliary variable with the name 'cdist' is found, then this information will be used in the calculation of specific discharge within model cells connected by the exchange.  for a horizontal connection, cdist should be specified as the horizontal distance between the cell centers, and should not include the vertical component.  for vertical connections, cdist should be specified as the difference in elevation between the two cell centers.  both angldegx and cdist are required if specific discharge is calculated for either of the groundwater models."
optional = true
dtype = "string"

[blocks.options.fields.boundnames]
name = "boundnames"
description = "keyword to indicate that boundary names may be provided with the list of gwf exchange cells."
optional = true

[blocks.options.fields.print_input]
name = "print_input"
longname = "keyword to print input to list file"
description = "keyword to indicate that the list of exchange entries will be echoed to the listing file immediately after it is read."
optional = true

[blocks.options.fields.print_flows]
name = "print_flows"
longname = "keyword to print gwfgwf flows to list file"
description = "keyword to indicate that the list of exchange flow rates will be printed to the listing file for every stress period in which 'save budget' is specified in output control."
optional = true

[blocks.options.fields.save_flows]
name = "save_flows"
longname = "keyword to save gwfgwf flows"
description = "keyword to indicate that cell-by-cell flow terms will be written to the budget file for each model provided that the output control for the models are set up with the 'budget save file' option."
optional = true

[blocks.options.fields.cell_averaging]
name = "cell_averaging"
longname = "conductance weighting option"
description = "is a keyword and text keyword to indicate the method that will be used for calculating the conductance for horizontal cell connections.  the text value for cell_averaging can be 'harmonic', 'logarithmic', or 'amt-lmk', which means 'arithmetic-mean thickness and logarithmic-mean hydraulic conductivity'. if the user does not specify a value for cell_averaging, then the harmonic-mean method will be used."
optional = true
tagged = false
valid = [
    "h",
    "a",
    "r",
    "m",
    "o",
    "n",
    "i",
    "c",
    " ",
    "l",
    "o",
    "g",
    "a",
    "r",
    "i",
    "t",
    "h",
    "m",
    "i",
    "c",
    " ",
    "a",
    "m",
    "t",
    "-",
    "l",
    "m",
    "k",
]

[blocks.options.fields.cvoptions]
name = "cvoptions"
longname = "vertical conductance options"
description = "none"
optional = true

[blocks.options.fields.cvoptions.fields.variablecv]
name = "variablecv"
longname = "keyword to activate variablecv option"
description = "keyword to indicate that the vertical conductance will be calculated using the saturated thickness and properties of the overlying cell and the thickness and properties of the underlying cell.  if the dewatered keyword is also specified, then the vertical conductance is calculated using only the saturated thickness and properties of the overlying cell if the head in the underlying cell is below its top.  if these keywords are not specified, then the default condition is to calculate the vertical conductance at the start of the simulation using the initial head and the cell properties.  the vertical conductance remains constant for the entire simulation."

[blocks.options.fields.cvoptions.fields.dewatered]
name = "dewatered"
longname = "keyword to activate dewatered option"
description = "if the dewatered keyword is specified, then the vertical conductance is calculated using only the saturated thickness and properties of the overlying cell if the head in the underlying cell is below its top."
optional = true

[blocks.options.fields.newton]
name = "newton"
longname = "keyword to activate newton-raphson"
description = "keyword that activates the newton-raphson formulation for groundwater flow between connected, convertible groundwater cells. cells will not dry when this option is used."
optional = true

[blocks.options.fields.xt3d]
name = "xt3d"
longname = "keyword to activate xt3d"
description = "keyword that activates the xt3d formulation between the cells connected with this gwf-gwf exchange."
optional = true

[blocks.options.fields.gnc_filerecord]
name = "gnc_filerecord"
optional = true

[blocks.options.fields.gnc_filerecord.fields.gnc6]
name = "gnc6"
longname = "gnc6 keyword"
description = "keyword to specify that record corresponds to a ghost-node correction file."

[blocks.options.fields.gnc_filerecord.fields.filein]
name = "filein"
longname = "file keyword"
description = "keyword to specify that an input filename is expected next."

[blocks.options.fields.gnc_filerecord.fields.gnc6_filename]
name = "gnc6_filename"
longname = "gnc6 input filename"
description = "is the file name for ghost node correction input file.  information for the ghost nodes are provided in the file provided with these keywords.  the format for specifying the ghost nodes is the same as described for the gnc package of the gwf model.  this includes specifying options, dimensions, and gncdata blocks.  the order of the ghost nodes must follow the same order as the order of the cells in the exchangedata block.  for the gncdata, noden and all of the nodej values are assumed to be located in model 1, and nodem is assumed to be in model 2."
tagged = false
case_sensitive = true

[blocks.options.fields.mvr_filerecord]
name = "mvr_filerecord"
optional = true

[blocks.options.fields.mvr_filerecord.fields.mvr6]
name = "mvr6"
longname = "obs keyword"
description = "keyword to specify that record corresponds to a mover file."

[blocks.options.fields.mvr_filerecord.fields.filein]
name = "filein"
longname = "file keyword"
description = "keyword to specify that an input filename is expected next."

[blocks.options.fields.mvr_filerecord.fields.mvr6_filename]
name = "mvr6_filename"
longname = "mvr6 input filename"
description = "is the file name of the water mover input file to apply to this exchange.  information for the water mover are provided in the file provided with these keywords.  the format for specifying the water mover information is the same as described for the water mover (mvr) package of the gwf model, with two exceptions.  first, in the packages block, the model name must be included as a separate string before each package.  second, the appropriate model name must be included before package name 1 and package name 2 in the begin period block.  this allows providers and receivers to be located in both models listed as part of this exchange."
tagged = false
case_sensitive = true

[blocks.options.fields.obs_filerecord]
name = "obs_filerecord"
optional = true

[blocks.options.fields.obs_filerecord.fields.obs6]
name = "obs6"
longname = "obs keyword"
description = "keyword to specify that record corresponds to an observations file."

[blocks.options.fields.obs_filerecord.fields.filein]
name = "filein"
longname = "file keyword"
description = "keyword to specify that an input filename is expected next."

[blocks.options.fields.obs_filerecord.fields.obs6_filename]
name = "obs6_filename"
longname = "obs6 input filename"
description = "is the file name of the observations input file for this exchange. see the 'observation utility' section for instructions for preparing observation input files. table ref{table:gwf-obstypetable} lists observation type(s) supported by the gwf-gwf package."
tagged = false
case_sensitive = true

[blocks.options.fields.dev_interfacemodel_on]
name = "dev_interfacemodel_on"
longname = "activate interface model on exchange"
description = "activates the interface model mechanism for calculating the coefficients at (and possibly near) the exchange. this keyword should only be used for development purposes."
optional = true

[blocks.dimensions]
name = "dimensions"

[blocks.dimensions.fields.nexg]
name = "nexg"
longname = "number of exchanges"
description = "keyword and integer value specifying the number of gwf-gwf exchanges."
tagged = false

[blocks.exchangedata]
name = "exchangedata"

[blocks.exchangedata.fields.exchangedata]
name = "exchangedata"
longname = "exchange data"

[blocks.exchangedata.fields.exchangedata.item]
name = "exchangedata"

[blocks.exchangedata.fields.exchangedata.item.fields.cellidm1]
name = "cellidm1"
longname = "cellid of first cell"
description = "is the cellid of the cell in model 1 as specified in the simulation name file. for a structured grid that uses the dis input file, cellidm1 is the layer, row, and column numbers of the cell.   for a grid that uses the disv input file, cellidm1 is the layer number and cell2d number for the two cells.  if the model uses the unstructured discretization (disu) input file, then cellidm1 is the node number for the cell."
tagged = false

[blocks.exchangedata.fields.exchangedata.item.fields.cellidm2]
name = "cellidm2"
longname = "cellid of second cell"
description = "is the cellid of the cell in model 2 as specified in the simulation name file. for a structured grid that uses the dis input file, cellidm2 is the layer, row, and column numbers of the cell.   for a grid that uses the disv input file, cellidm2 is the layer number and cell2d number for the two cells.  if the model uses the unstructured discretization (disu) input file, then cellidm2 is the node number for the cell."
tagged = false

[blocks.exchangedata.fields.exchangedata.item.fields.ihc]
name = "ihc"
longname = "integer flag for connection type"
description = "is an integer flag indicating the direction between node n and all of its m connections. if ihc = 0 then the connection is vertical.  if ihc = 1 then the connection is horizontal. if ihc = 2 then the connection is horizontal for a vertically staggered grid."
tagged = false

[blocks.exchangedata.fields.exchangedata.item.fields.cl1]
name = "cl1"
longname = "connection distance"
description = "is the distance between the center of cell 1 and the its shared face with cell 2."
tagged = false

[blocks.exchangedata.fields.exchangedata.item.fields.cl2]
name = "cl2"
longname = "connection distance"
description = "is the distance between the center of cell 2 and the its shared face with cell 1."
tagged = false

[blocks.exchangedata.fields.exchangedata.item.fields.hwva]
name = "hwva"
longname = "horizontal cell width or area for vertical flow"
description = "is the horizontal width of the flow connection between cell 1 and cell 2 if ihc $>$ 0, or it is the area perpendicular to flow of the vertical connection between cell 1 and cell 2 if ihc = 0."
tagged = false

[blocks.exchangedata.fields.exchangedata.item.fields.aux]
name = "aux"
longname = "auxiliary variables"
description = "represents the values of the auxiliary variables for each gwfgwf exchange. the values of auxiliary variables must be present for each exchange. the values must be specified in the order of the auxiliary variables specified in the options block."
optional = true
dtype = "double"
shape = [
    "auxiliary",
]

[blocks.exchangedata.fields.exchangedata.item.fields.boundname]
name = "boundname"
longname = "exchange boundname"
description = "name of the gwf exchange cell.  boundname is an ascii character variable that can contain as many as 40 characters.  if boundname contains spaces in it, then the entire name must be enclosed within single quotes."
optional = true
tagged = false

[dims.nexg]
field = "nexg"
scope = "component"

[dims.auxiliary]
field = "auxiliary"
scope = "component"
