name = "exg-gwtgwt"
schema_version = "2"
multi = true
subtype = "exchange"

[blocks.options]
name = "options"

[blocks.options.fields.gwfmodelname1]
name = "gwfmodelname1"
longname = "keyword to specify name of first corresponding gwf model"
description = "keyword to specify name of first corresponding gwf model.  in the simulation name file, the gwt6-gwt6 entry contains names for gwt models (exgmnamea and exgmnameb).  the gwt model with the name exgmnamea must correspond to the gwf model with the name gwfmodelname1."
tagged = false

[blocks.options.fields.gwfmodelname2]
name = "gwfmodelname2"
longname = "keyword to specify name of second corresponding gwf model"
description = "keyword to specify name of second corresponding gwf model.  in the simulation name file, the gwt6-gwt6 entry contains names for gwt models (exgmnamea and exgmnameb).  the gwt model with the name exgmnameb must correspond to the gwf model with the name gwfmodelname2."
tagged = false

[blocks.options.fields.auxiliary]
name = "auxiliary"
longname = "keyword to specify aux variables"
description = "an array of auxiliary variable names.  there is no limit on the number of auxiliary variables that can be provided. most auxiliary variables will not be used by the gwt-gwt exchange, but they will be available for use by other parts of the program.  if an auxiliary variable with the name 'angldegx' is found, then this information will be used as the angle (provided in degrees) between the connection face normal and the x axis, where a value of zero indicates that a normal vector points directly along the positive x axis.  the connection face normal is a normal vector on the cell face shared between the cell in model 1 and the cell in model 2 pointing away from the model 1 cell.  additional information on 'angldegx' is provided in the description of the disu package.  angldegx must be specified if dispersion is simulated in the connected gwt models."
optional = true
dtype = "string"

[blocks.options.fields.boundnames]
name = "boundnames"
description = "keyword to indicate that boundary names may be provided with the list of gwt exchange cells."
optional = true

[blocks.options.fields.print_input]
name = "print_input"
longname = "keyword to print input to list file"
description = "keyword to indicate that the list of exchange entries will be echoed to the listing file immediately after it is read."
optional = true

[blocks.options.fields.print_flows]
name = "print_flows"
longname = "keyword to print gwfgwf flows to list file"
description = "keyword to indicate that the list of exchange flow rates will be printed to the listing file for every stress period in which 'save budget' is specified in output control."
optional = true

[blocks.options.fields.save_flows]
name = "save_flows"
longname = "keyword to save gwfgwf flows"
description = "keyword to indicate that cell-by-cell flow terms will be written to the budget file for each model provided that the output control for the models are set up with the 'budget save file' option."
optional = true

[blocks.options.fields.adv_scheme]
name = "adv_scheme"
longname = "advective scheme"
description = "scheme used to solve the advection term.  can be upstream, central, or tvd.  if not specified, upstream weighting is the default weighting scheme."
optional = true
tagged = false
valid = [
    "u",
    "p",
    "s",
    "t",
    "r",
    "e",
    "a",
    "m",
    " ",
    "c",
    "e",
    "n",
    "t",
    "r",
    "a",
    "l",
    " ",
    "t",
    "v",
    "d",
]

[blocks.options.fields.dsp_xt3d_off]
name = "dsp_xt3d_off"
longname = "deactivate xt3d"
description = "deactivate the xt3d method for the dispersive flux and use the faster and less accurate approximation for this exchange."
optional = true

[blocks.options.fields.dsp_xt3d_rhs]
name = "dsp_xt3d_rhs"
longname = "xt3d on right-hand side"
description = "add xt3d dispersion terms to right-hand side, when possible, for this exchange."
optional = true

[blocks.options.fields.mvt_filerecord]
name = "mvt_filerecord"
optional = true

[blocks.options.fields.mvt_filerecord.fields.mvt6]
name = "mvt6"
longname = "obs keyword"
description = "keyword to specify that record corresponds to a transport mover file."

[blocks.options.fields.mvt_filerecord.fields.filein]
name = "filein"
longname = "file keyword"
description = "keyword to specify that an input filename is expected next."

[blocks.options.fields.mvt_filerecord.fields.mvt6_filename]
name = "mvt6_filename"
longname = "mvt6 input filename"
description = "is the file name of the transport mover input file to apply to this exchange.  information for the transport mover are provided in the file provided with these keywords."
tagged = false
case_sensitive = true

[blocks.options.fields.obs_filerecord]
name = "obs_filerecord"
optional = true

[blocks.options.fields.obs_filerecord.fields.obs6]
name = "obs6"
longname = "obs keyword"
description = "keyword to specify that record corresponds to an observations file."

[blocks.options.fields.obs_filerecord.fields.filein]
name = "filein"
longname = "file keyword"
description = "keyword to specify that an input filename is expected next."

[blocks.options.fields.obs_filerecord.fields.obs6_filename]
name = "obs6_filename"
longname = "obs6 input filename"
description = "is the file name of the observations input file for this exchange. see the 'observation utility' section for instructions for preparing observation input files. table ref{table:gwt-obstypetable} lists observation type(s) supported by the gwt-gwt package."
tagged = false
case_sensitive = true

[blocks.options.fields.dev_interfacemodel_on]
name = "dev_interfacemodel_on"
longname = "activate interface model on exchange"
description = "activates the interface model mechanism for calculating the coefficients at (and possibly near) the exchange. this keyword should only be used for development purposes."
optional = true

[blocks.dimensions]
name = "dimensions"

[blocks.dimensions.fields.nexg]
name = "nexg"
longname = "number of exchanges"
description = "keyword and integer value specifying the number of gwt-gwt exchanges."
tagged = false

[blocks.exchangedata]
name = "exchangedata"

[blocks.exchangedata.fields.exchangedata]
name = "exchangedata"
longname = "exchange data"

[blocks.exchangedata.fields.exchangedata.item]
name = "exchangedata"

[blocks.exchangedata.fields.exchangedata.item.fields.cellidm1]
name = "cellidm1"
longname = "cellid of first cell"
description = "is the cellid of the cell in model 1 as specified in the simulation name file. for a structured grid that uses the dis input file, cellidm1 is the layer, row, and column numbers of the cell.   for a grid that uses the disv input file, cellidm1 is the layer number and cell2d number for the two cells.  if the model uses the unstructured discretization (disu) input file, then cellidm1 is the node number for the cell."
tagged = false

[blocks.exchangedata.fields.exchangedata.item.fields.cellidm2]
name = "cellidm2"
longname = "cellid of second cell"
description = "is the cellid of the cell in model 2 as specified in the simulation name file. for a structured grid that uses the dis input file, cellidm2 is the layer, row, and column numbers of the cell.   for a grid that uses the disv input file, cellidm2 is the layer number and cell2d number for the two cells.  if the model uses the unstructured discretization (disu) input file, then cellidm2 is the node number for the cell."
tagged = false

[blocks.exchangedata.fields.exchangedata.item.fields.ihc]
name = "ihc"
longname = "integer flag for connection type"
description = "is an integer flag indicating the direction between node n and all of its m connections. if ihc = 0 then the connection is vertical.  if ihc = 1 then the connection is horizontal. if ihc = 2 then the connection is horizontal for a vertically staggered grid."
tagged = false

[blocks.exchangedata.fields.exchangedata.item.fields.cl1]
name = "cl1"
longname = "connection distance"
description = "is the distance between the center of cell 1 and the its shared face with cell 2."
tagged = false

[blocks.exchangedata.fields.exchangedata.item.fields.cl2]
name = "cl2"
longname = "connection distance"
description = "is the distance between the center of cell 2 and the its shared face with cell 1."
tagged = false

[blocks.exchangedata.fields.exchangedata.item.fields.hwva]
name = "hwva"
longname = "horizontal cell width or area for vertical flow"
description = "is the horizontal width of the flow connection between cell 1 and cell 2 if ihc $>$ 0, or it is the area perpendicular to flow of the vertical connection between cell 1 and cell 2 if ihc = 0."
tagged = false

[blocks.exchangedata.fields.exchangedata.item.fields.aux]
name = "aux"
longname = "auxiliary variables"
description = "represents the values of the auxiliary variables for each gwtgwt exchange. the values of auxiliary variables must be present for each exchange. the values must be specified in the order of the auxiliary variables specified in the options block."
optional = true
dtype = "double"
shape = [
    "auxiliary",
]

[blocks.exchangedata.fields.exchangedata.item.fields.boundname]
name = "boundname"
longname = "exchange boundname"
description = "name of the gwt exchange cell.  boundname is an ascii character variable that can contain as many as 40 characters.  if boundname contains spaces in it, then the entire name must be enclosed within single quotes."
optional = true
tagged = false

[dims.nexg]
field = "nexg"
scope = "component"

[dims.auxiliary]
field = "auxiliary"
scope = "component"
