name = "gwe-uze"
schema_version = "2"
multi = true
subtype = "stress"

[blocks.options]
name = "options"

[blocks.options.fields.flow_package_name]
name = "flow_package_name"
longname = "keyword to specify name of corresponding flow package"
description = "keyword to specify the name of the corresponding flow package.  if not specified, then the corresponding flow package must have the same name as this advanced transport package (the name associated with this package in the gwe name file)."
optional = true
tagged = false

[blocks.options.fields.auxiliary]
name = "auxiliary"
longname = "keyword to specify aux variables"
description = "defines an array of one or more auxiliary variable names.  there is no limit on the number of auxiliary variables that can be provided on this line; however, lists of information provided in subsequent blocks must have a column of data for each auxiliary variable name defined here.   the number of auxiliary variables detected on this line determines the value for naux.  comments cannot be provided anywhere on this line as they will be interpreted as auxiliary variable names.  auxiliary variables may not be used by the package, but they will be available for use by other parts of the program.  the program will terminate with an error if auxiliary variables are specified on more than one line in the options block."
optional = true
dtype = "string"

[blocks.options.fields.flow_package_auxiliary_name]
name = "flow_package_auxiliary_name"
longname = "keyword to specify name of concentration auxiliary variable in flow package"
description = "keyword to specify the name of an auxiliary variable in the corresponding flow package.  if specified, then the simulated temperatures from this advanced transport package will be copied into the auxiliary variable specified with this name.  note that the flow package must have an auxiliary variable with this name or the program will terminate with an error.  if the flows for this advanced transport package are read from a file, then this option will have no effect."
optional = true
tagged = false

[blocks.options.fields.boundnames]
name = "boundnames"
description = "keyword to indicate that boundary names may be provided with the list of unsaturated zone flow cells."
optional = true

[blocks.options.fields.print_input]
name = "print_input"
longname = "print input to listing file"
description = "keyword to indicate that the list of unsaturated zone flow information will be written to the listing file immediately after it is read."
optional = true

[blocks.options.fields.print_temperature]
name = "print_temperature"
longname = "print calculated temperatures to listing file"
description = "keyword to indicate that the list of uzf cell {#2} will be printed to the listing file for every stress period in which 'temperature print' is specified in output control.  if there is no output control option and print_{#3} is specified, then {#2} are printed for the last time step of each stress period."
optional = true

[blocks.options.fields.print_flows]
name = "print_flows"
longname = "print calculated flows to listing file"
description = "keyword to indicate that the list of unsaturated zone flow rates will be printed to the listing file for every stress period time step in which 'budget print' is specified in output control.  if there is no output control option and 'print_flows' is specified, then flow rates are printed for the last time step of each stress period."
optional = true

[blocks.options.fields.save_flows]
name = "save_flows"
longname = "save uze cell flows to budget file"
description = "keyword to indicate that unsaturated zone flow terms will be written to the file specified with 'budget fileout' in output control."
optional = true

[blocks.options.fields.temperature_filerecord]
name = "temperature_filerecord"
optional = true

[blocks.options.fields.temperature_filerecord.fields.temperature]
name = "temperature"
longname = "stage keyword"
description = "keyword to specify that record corresponds to temperature."

[blocks.options.fields.temperature_filerecord.fields.fileout]
name = "fileout"
longname = "file keyword"
description = "keyword to specify that an output filename is expected next."

[blocks.options.fields.temperature_filerecord.fields.tempfile]
name = "tempfile"
longname = "file keyword"
description = "name of the binary output file to write temperature information."
tagged = false
case_sensitive = true

[blocks.options.fields.budget_filerecord]
name = "budget_filerecord"
optional = true

[blocks.options.fields.budget_filerecord.fields.budget]
name = "budget"
longname = "budget keyword"
description = "keyword to specify that record corresponds to the budget."

[blocks.options.fields.budget_filerecord.fields.fileout]
name = "fileout"
longname = "file keyword"
description = "keyword to specify that an output filename is expected next."

[blocks.options.fields.budget_filerecord.fields.budgetfile]
name = "budgetfile"
longname = "file keyword"
description = "name of the binary output file to write budget information."
tagged = false
case_sensitive = true

[blocks.options.fields.budgetcsv_filerecord]
name = "budgetcsv_filerecord"
optional = true

[blocks.options.fields.budgetcsv_filerecord.fields.budgetcsv]
name = "budgetcsv"
longname = "budget keyword"
description = "keyword to specify that record corresponds to the budget csv."

[blocks.options.fields.budgetcsv_filerecord.fields.fileout]
name = "fileout"
longname = "file keyword"
description = "keyword to specify that an output filename is expected next."

[blocks.options.fields.budgetcsv_filerecord.fields.budgetcsvfile]
name = "budgetcsvfile"
longname = "file keyword"
description = "name of the comma-separated value (csv) output file to write budget summary information.  a budget summary record will be written to this file for each time step of the simulation."
tagged = false
case_sensitive = true

[blocks.options.fields.ts_filerecord]
name = "ts_filerecord"
optional = true

[blocks.options.fields.ts_filerecord.fields.ts6]
name = "ts6"
longname = "head keyword"
description = "keyword to specify that record corresponds to a time-series file."

[blocks.options.fields.ts_filerecord.fields.filein]
name = "filein"
longname = "file keyword"
description = "keyword to specify that an input filename is expected next."

[blocks.options.fields.ts_filerecord.fields.ts6_filename]
name = "ts6_filename"
longname = "file name of time series information"
description = "defines a time-series file defining time series that can be used to assign time-varying values. see the 'time-variable input' section for instructions on using the time-series capability."
tagged = false
case_sensitive = true

[blocks.options.fields.obs_filerecord]
name = "obs_filerecord"
optional = true

[blocks.options.fields.obs_filerecord.fields.obs6]
name = "obs6"
longname = "obs keyword"
description = "keyword to specify that record corresponds to an observations file."

[blocks.options.fields.obs_filerecord.fields.filein]
name = "filein"
longname = "file keyword"
description = "keyword to specify that an input filename is expected next."

[blocks.options.fields.obs_filerecord.fields.obs6_filename]
name = "obs6_filename"
longname = "obs6 input filename"
description = "name of input file to define observations for the uze package. see the 'observation utility' section for instructions for preparing observation input files. table {#2} lists observation type(s) supported by the uze package."
tagged = false
case_sensitive = true

[blocks.packagedata]
name = "packagedata"

[blocks.packagedata.fields.packagedata]
name = "packagedata"

[blocks.packagedata.fields.packagedata.item]
name = "packagedata"

[blocks.packagedata.fields.packagedata.item.fields.uzfno]
name = "uzfno"
longname = "uzf cell number for this entry"
description = "integer value that defines the uzf cell number associated with the specified packagedata data on the line. uzfno must be greater than zero and less than or equal to nuzfcells. unsaturated zone flow information must be specified for every uzf cell or the program will terminate with an error.  the program also will terminate with an error if information for a uzf cell is specified more than once."
tagged = false

[blocks.packagedata.fields.packagedata.item.fields.strt]
name = "strt"
longname = "starting uzf cell temperature"
description = "real value that defines the starting temperature for the unsaturated zone flow cell."
tagged = false

[blocks.packagedata.fields.packagedata.item.fields.aux]
name = "aux"
longname = "auxiliary variables"
description = "represents the values of the auxiliary variables for each unsaturated zone flow. the values of auxiliary variables must be present for each unsaturated zone flow. the values must be specified in the order of the auxiliary variables specified in the options block.  if the package supports time series and the options block includes a timeseriesfile entry (see the 'time-variable input' section), values can be obtained from a time series by entering the time-series name in place of a numeric value."
optional = true
dtype = "double"
shape = [
    "auxiliary",
]
time_series = true

[blocks.packagedata.fields.packagedata.item.fields.boundname]
name = "boundname"
longname = "uzf cell name"
description = "name of the unsaturated zone flow cell.  boundname is an ascii character variable that can contain as many as 40 characters.  if boundname contains spaces in it, then the entire name must be enclosed within single quotes."
optional = true
tagged = false

[blocks.period]
name = "period"

[blocks.period.fields.uzeperioddata]
name = "uzeperioddata"

[blocks.period.fields.uzeperioddata.item]
name = "uzeperioddata"

[blocks.period.fields.uzeperioddata.item.fields.uzfno]
name = "uzfno"
longname = "unsaturated zone flow cell number for this entry"
description = "integer value that defines the uzf cell number associated with the specified period data on the line. uzfno must be greater than zero and less than or equal to nuzfcells."
tagged = false

[blocks.period.fields.uzeperioddata.item.fields.uzesetting]
name = "uzesetting"
description = "line of information that is parsed into a keyword and values.  keyword values that can be used to start the uzesetting string include: status, temperature, infiltration, uzet, and auxiliary.  these settings are used to assign the temperature associated with the corresponding flow terms.  temperatures cannot be specified for all flow terms."

[blocks.period.fields.uzeperioddata.item.fields.uzesetting.arms.temperature]
name = "temperature"
longname = "unsaturated zone flow cell temperature"
description = "real or character value that defines the temperature for the unsaturated zone flow cell. the specified temperature is only applied if the unsaturated zone flow cell is a constant temperature cell. if the options block includes a timeseriesfile entry (see the 'time-variable input' section), values can be obtained from a time series by entering the time-series name in place of a numeric value."
time_series = true

[blocks.period.fields.uzeperioddata.item.fields.uzesetting.arms.status]
name = "status"
longname = "unsaturated zone flow cell temperature status"
description = "keyword option to define uzf cell status.  status can be active, inactive, or constant. by default, status is active, which means that temperature will be calculated for the uzf cell.  if a uzf cell is inactive, then there will be no energy fluxes into or out of the uzf cell and the inactive value will be written for the uzf cell temperature.  if a uzf cell is constant, then the temperature for the uzf cell will be fixed at the user specified value."

[blocks.period.fields.uzeperioddata.item.fields.uzesetting.arms.infiltration]
name = "infiltration"
longname = "infiltration temperature"
description = "real or character value that defines the temperature of the infiltration $(e.g.,:^{circ}c:or:^{circ}f)$ for the uzf cell. if the options block includes a timeseriesfile entry (see the 'time-variable input' section), values can be obtained from a time series by entering the time-series name in place of a numeric value."
time_series = true

[blocks.period.fields.uzeperioddata.item.fields.uzesetting.arms.uzet]
name = "uzet"
longname = "unsaturated zone et temperature"
description = "real or character value that states what fraction of the simulated unsaturated zone evapotranspiration is associated with evaporation.  the evaporative losses from the unsaturated zone moisture content will have an evaporative cooling effect on the gwe cell from which the evaporation originated. if this value is larger than 1, then it will be reset to 1.  if the options block includes a timeseriesfile entry (see the 'time-variable input' section), values can be obtained from a time series by entering the time-series name in place of a numeric value."
time_series = true

[blocks.period.fields.uzeperioddata.item.fields.uzesetting.arms.auxiliaryrecord]
name = "auxiliaryrecord"

[blocks.period.fields.uzeperioddata.item.fields.uzesetting.arms.auxiliaryrecord.fields.auxiliary]
name = "auxiliary"
description = "keyword for specifying auxiliary variable."

[blocks.period.fields.uzeperioddata.item.fields.uzesetting.arms.auxiliaryrecord.fields.auxname]
name = "auxname"
description = "name for the auxiliary variable to be assigned auxval.  auxname must match one of the auxiliary variable names defined in the options block. if auxname does not match one of the auxiliary variable names defined in the options block the data are ignored."
tagged = false

[blocks.period.fields.uzeperioddata.item.fields.uzesetting.arms.auxiliaryrecord.fields.auxval]
name = "auxval"
longname = "auxiliary variable value"
description = "value for the auxiliary variable. if the options block includes a timeseriesfile entry (see the 'time-variable input' section), values can be obtained from a time series by entering the time-series name in place of a numeric value."
tagged = false
time_series = true

[dims.auxiliary]
field = "auxiliary"
scope = "component"
