name = "gwe-est"
schema_version = "2"

[blocks.options]
name = "options"

[blocks.options.fields.save_flows]
name = "save_flows"
longname = "save calculated flows to budget file"
description = "keyword to indicate that est flow terms will be written to the file specified with 'budget fileout' in output control."
optional = true

[blocks.options.fields.zero_order_decay_water]
name = "zero_order_decay_water"
longname = "activate zero-order decay in aqueous phase"
description = "is a text keyword to indicate that zero-order decay will occur in the aqueous phase. that is, decay occurs in the water and is a rate per volume of water only, not per volume of aquifer (i.e., grid cell).  use of this keyword requires that decay_water is specified in the griddata block."
optional = true

[blocks.options.fields.zero_order_decay_solid]
name = "zero_order_decay_solid"
longname = "activate zero-order decay in solid phase"
description = "is a text keyword to indicate that zero-order decay will occur in the solid phase. that is, decay occurs in the solid and is a rate per mass (not volume) of solid only.  use of this keyword requires that decay_solid is specified in the griddata block."
optional = true

[blocks.options.fields.density_water]
name = "density_water"
longname = "density of water"
description = "density of water used by calculations related to heat storage and conduction.  this value is set to 1,000 kg/m3 if no overriding value is specified.  a user-specified value should be provided for models that use units other than kilograms and meters or if it is necessary to use a value other than the default."
optional = true
tagged = false

[blocks.options.fields.heat_capacity_water]
name = "heat_capacity_water"
longname = "heat capacity of water"
description = "heat capacity of water used by calculations related to heat storage and conduction.  this value is set to 4,184 j/kg/c if no overriding value is specified.  a user-specified value should be provided for models that use units other than kilograms, joules, and degrees celsius or it is necessary to use a value other than the default."
optional = true
tagged = false

[blocks.options.fields.latent_heat_vaporization]
name = "latent_heat_vaporization"
longname = "latent heat of vaporization"
description = "latent heat of vaporization is the amount of energy that is required to convert a given quantity of liquid into a gas and is associated with evaporative cooling.  while the est package does not simulate evaporation, multiple other packages in a gwe simulation may.  to avoid having to specify the latent heat of vaporization in multiple packages, it is specified in a single location and accessed wherever it is needed.  for example, evaporation may occur from the surface of streams or lakes and the energy consumed by the change in phase would be needed in both the sfe and lke packages.  this value is set to 2,453,500 j/kg if no overriding value is specified.  a user-specified value should be provided for models that use units other than joules and kilograms or if it is necessary to use a value other than the default."
optional = true
tagged = false

[blocks.griddata]
name = "griddata"

[blocks.griddata.fields.porosity]
name = "porosity"
longname = "porosity"
description = "is the mobile domain porosity, defined as the mobile domain pore volume per mobile domain volume.  the gwe model does not support the concept of an immobile domain in the context of heat transport."
dtype = "double"
shape = [
    "nodes",
]

[blocks.griddata.fields.decay_water]
name = "decay_water"
longname = "aqueous phase decay rate coefficient"
description = "is the rate coefficient for zero-order decay for the aqueous phase of the mobile domain.  a negative value indicates heat (energy) production.  the dimensions of zero-order decay in the aqueous phase are energy per length cubed (volume of water) per time.  zero-order decay in the aqueous phase will have no effect on simulation results unless zero_order_decay_water is specified in the options block."
optional = true
dtype = "double"
shape = [
    "nodes",
]

[blocks.griddata.fields.decay_solid]
name = "decay_solid"
longname = "solid phase decay rate coefficient"
description = "is the rate coefficient for zero-order decay for the solid phase.  a negative value indicates heat (energy) production. the dimensions of zero-order decay in the solid phase are energy per mass of solid per time. zero-order decay in the solid phase will have no effect on simulation results unless zero_order_decay_solid is specified in the options block."
optional = true
dtype = "double"
shape = [
    "nodes",
]

[blocks.griddata.fields.heat_capacity_solid]
name = "heat_capacity_solid"
longname = "heat capacity of the aquifer material"
description = "is the mass-based heat capacity of dry solids (aquifer material). for example, units of j/kg/c may be used (or equivalent)."
dtype = "double"
shape = [
    "nodes",
]

[blocks.griddata.fields.density_solid]
name = "density_solid"
longname = "density of aquifer material"
description = "is a user-specified value of the density of aquifer material not considering the voids. value will remain fixed for the entire simulation.  for example, if working in si units, values may be entered as kilograms per cubic meter."
dtype = "double"
shape = [
    "nodes",
]
