name = "gwe-nam"
schema_version = "2"

[blocks.options]
name = "options"

[blocks.options.fields.list]
name = "list"
longname = "name of listing file"
description = "is name of the listing file to create for this gwe model.  if not specified, then the name of the list file will be the basename of the gwe model name file and the '.lst' extension.  for example, if the gwe name file is called 'my.model.nam' then the list file will be called 'my.model.lst'."
optional = true
tagged = false
case_sensitive = true

[blocks.options.fields.print_input]
name = "print_input"
longname = "print input to listing file"
description = "keyword to indicate that the list of all model stress package information will be written to the listing file immediately after it is read."
optional = true

[blocks.options.fields.print_flows]
name = "print_flows"
longname = "print calculated flows to listing file"
description = "keyword to indicate that the list of all model package flow rates will be printed to the listing file for every stress period time step in which 'budget print' is specified in output control.  if there is no output control option and 'print_flows' is specified, then flow rates are printed for the last time step of each stress period."
optional = true

[blocks.options.fields.save_flows]
name = "save_flows"
longname = "save flows for all packages to budget file"
description = "keyword to indicate that all model package flow terms will be written to the file specified with 'budget fileout' in output control."
optional = true

[blocks.options.fields.dependent_variable_scaling]
name = "dependent_variable_scaling"
longname = "flag to scale x and rhs"
description = "flag to scale x and rhs to avoid very large positive or negative dependent variable values"
optional = true

[blocks.options.fields.nc_mesh2d_filerecord]
name = "nc_mesh2d_filerecord"
description = "netcdf layered mesh fileout record."
optional = true

[blocks.options.fields.nc_mesh2d_filerecord.fields.netcdf_mesh2d]
name = "netcdf_mesh2d"
longname = "budget keyword"
description = "keyword to specify that record corresponds to a layered mesh netcdf file."

[blocks.options.fields.nc_mesh2d_filerecord.fields.fileout]
name = "fileout"
longname = "file keyword"
description = "keyword to specify that an output filename is expected next."

[blocks.options.fields.nc_mesh2d_filerecord.fields.ncmesh2dfile]
name = "ncmesh2dfile"
longname = "file keyword"
description = "name of the netcdf ugrid layered mesh output file."
tagged = false
case_sensitive = true

[blocks.options.fields.nc_structured_filerecord]
name = "nc_structured_filerecord"
description = "netcdf structured fileout record."
optional = true

[blocks.options.fields.nc_structured_filerecord.fields.netcdf_structured]
name = "netcdf_structured"
longname = "budget keyword"
description = "keyword to specify that record corresponds to a structured netcdf file."

[blocks.options.fields.nc_structured_filerecord.fields.fileout]
name = "fileout"
longname = "file keyword"
description = "keyword to specify that an output filename is expected next."

[blocks.options.fields.nc_structured_filerecord.fields.ncstructfile]
name = "ncstructfile"
longname = "file keyword"
description = "name of the netcdf structured output file."
tagged = false
case_sensitive = true

[blocks.options.fields.nc_filerecord]
name = "nc_filerecord"
description = "netcdf filerecord"
optional = true

[blocks.options.fields.nc_filerecord.fields.netcdf]
name = "netcdf"
longname = "netcdf keyword"
description = "keyword to specify that record corresponds to a netcdf input file."

[blocks.options.fields.nc_filerecord.fields.filein]
name = "filein"
longname = "file keyword"
description = "keyword to specify that an input filename is expected next."

[blocks.options.fields.nc_filerecord.fields.netcdf_filename]
name = "netcdf_filename"
longname = "netcdf input filename"
description = "defines a netcdf input file."
tagged = false
case_sensitive = true

[blocks.packages]
name = "packages"

[blocks.packages.fields.packages]
name = "packages"
longname = "package list"

[blocks.packages.fields.packages.item]
name = "packages"

[blocks.packages.fields.packages.item.fields.ftype]
name = "ftype"
longname = "package type"
description = "is the file type, which must be one of the following character values shown in table~ref{table:ftype-gwe}. ftype may be entered in any combination of uppercase and lowercase."
tagged = false

[blocks.packages.fields.packages.item.fields.fname]
name = "fname"
longname = "file name"
description = "is the name of the file containing the package input.  the path to the file should be included if the file is not located in the folder where the program was run."
tagged = false
case_sensitive = true

[blocks.packages.fields.packages.item.fields.pname]
name = "pname"
longname = "user name for package"
description = "is the user-defined name for the package. pname is restricted to 16 characters.  no spaces are allowed in pname.  pname character values are read and stored by the program for stress packages only.  these names may be useful for labeling purposes when multiple stress packages of the same type are located within a single gwe model.  if pname is specified for a stress package, then pname will be used in the flow budget table in the listing file; it will also be used for the text entry in the cell-by-cell budget file.  pname is case insensitive and is stored in all upper case letters."
optional = true
tagged = false
