name = "gwe-ssm"
schema_version = "2"

[blocks.options]
name = "options"

[blocks.options.fields.print_flows]
name = "print_flows"
longname = "print calculated flows to listing file"
description = "keyword to indicate that the list of ssm flow rates will be printed to the listing file for every stress period time step in which 'budget print' is specified in output control.  if there is no output control option and 'print_flows' is specified, then flow rates are printed for the last time step of each stress period."
optional = true

[blocks.options.fields.save_flows]
name = "save_flows"
longname = "save calculated flows to budget file"
description = "keyword to indicate that ssm flow terms will be written to the file specified with 'budget fileout' in output control."
optional = true

[blocks.sources]
name = "sources"

[blocks.sources.fields.sources]
name = "sources"
longname = "package list"

[blocks.sources.fields.sources.item]
name = "sources"

[blocks.sources.fields.sources.item.fields.pname]
name = "pname"
longname = "package name"
description = "name of the flow package for which an auxiliary variable contains a source temperature.  if this flow package is represented using an advanced transport package (sfe, lke, mwe, or uze), then the advanced transport package will override ssm terms specified here."
tagged = false

[blocks.sources.fields.sources.item.fields.srctype]
name = "srctype"
longname = "source type"
description = "keyword indicating how temperature will be assigned for sources and sinks.  keyword must be specified as either aux or auxmixed.  for both options the user must provide an auxiliary variable in the corresponding flow package.  the auxiliary variable must have the same name as the auxname value that follows.  if the aux keyword is specified, then the auxiliary variable specified by the user will be assigned as the temperature value for groundwater sources (flows with a positive sign).  for negative flow rates (sinks), groundwater will be withdrawn from the cell at the simulated temperature of the cell.  the auxmixed option provides an alternative method for how to determine the temperature of sinks.  if the cell temperature is larger than the user-specified auxiliary temperature, then the temperature of groundwater withdrawn from the cell will be assigned as the user-specified temperature.  alternatively, if the user-specified auxiliary temperature is larger than the cell temperature, then groundwater will be withdrawn at the cell temperature.  thus, the auxmixed option is designed to work with the evapotranspiration (evt) and recharge (rch) packages where water may be withdrawn at a temperature that is less than the cell temperature."
tagged = false

[blocks.sources.fields.sources.item.fields.auxname]
name = "auxname"
longname = "auxiliary variable name"
description = "name of the auxiliary variable in the package pname.  this auxiliary variable must exist and be specified by the user in that package.  the values in this auxiliary variable will be used to set the temperature associated with the flows for that boundary package."
tagged = false

[blocks.fileinput]
name = "fileinput"

[blocks.fileinput.fields.fileinput]
name = "fileinput"
optional = true

[blocks.fileinput.fields.fileinput.item]
name = "fileinput"

[blocks.fileinput.fields.fileinput.item.fields.pname]
name = "pname"
longname = "package name"
description = "name of the flow package for which an auxiliary variable contains a source temperature.  if this flow package is represented using an advanced transport package (sfe, lke, mwe, or uze), then the advanced transport package will override ssm terms specified here."
tagged = false

[blocks.fileinput.fields.fileinput.item.fields.spc6]
name = "spc6"
longname = "head keyword"
description = "keyword to specify that record corresponds to a source sink mixing input file."

[blocks.fileinput.fields.fileinput.item.fields.filein]
name = "filein"
longname = "file keyword"
description = "keyword to specify that an input filename is expected next."

[blocks.fileinput.fields.fileinput.item.fields.spc6_filename]
name = "spc6_filename"
longname = "spc file name"
description = "character string that defines the path and filename for the file containing source and sink input data for the flow package. the spc6_filename file is a flexible input file that allows temperatures to be specified by stress period and with time series. instructions for creating the spc6_filename input file are provided in the next section on file input for boundary temperatures."
tagged = false
case_sensitive = true

[blocks.fileinput.fields.fileinput.item.fields.mixed]
name = "mixed"
longname = "mixed keyword"
description = "keyword to specify that these stress package boundaries will have the mixed condition.  the mixed condition is described in the sources block for auxmixed.  the mixed condition allows for water to be withdrawn at a temperature that is less than the cell temperature.  it is intended primarily for representing evapotranspiration."
optional = true
