name = "gwf-sto"
schema_version = "2"
subtype = "stress"

[blocks.options]
name = "options"

[blocks.options.fields.save_flows]
name = "save_flows"
longname = "keyword to save npf flows"
description = "keyword to indicate that cell-by-cell flow terms will be written to the file specified with 'budget save file' in output control."
optional = true

[blocks.options.fields.storagecoefficient]
name = "storagecoefficient"
longname = "keyword to indicate ss is read as storage coefficient"
description = "keyword to indicate that the ss array is read as storage coefficient rather than specific storage."
optional = true

[blocks.options.fields.ss_confined_only]
name = "ss_confined_only"
longname = "keyword to indicate specific storage only applied under confined conditions"
description = "keyword to indicate that compressible storage is only calculated for a convertible cell (iconvert>0) when the cell is under confined conditions (head greater than or equal to the top of the cell). this option has no effect on cells that are marked as being always confined (iconvert=0).  this option is identical to the approach used to calculate storage changes under confined conditions in modflow-2005."
optional = true

[blocks.options.fields.tvs_filerecord]
name = "tvs_filerecord"
optional = true

[blocks.options.fields.tvs_filerecord.fields.tvs6]
name = "tvs6"
longname = "tvs keyword"
description = "keyword to specify that record corresponds to a time-varying storage (tvs) file.  the behavior of tvs and a description of the input file is provided separately."

[blocks.options.fields.tvs_filerecord.fields.filein]
name = "filein"
longname = "file keyword"
description = "keyword to specify that an input filename is expected next."

[blocks.options.fields.tvs_filerecord.fields.tvs6_filename]
name = "tvs6_filename"
longname = "file name of tvs information"
description = "defines a time-varying storage (tvs) input file.  records in the tvs file can be used to change specific storage and specific yield properties at specified times or stress periods."
tagged = false
case_sensitive = true

[blocks.options.fields.export_array_ascii]
name = "export_array_ascii"
longname = "export array variables to layered ascii files."
description = "keyword that specifies input grid arrays, which already support the layered keyword, should be written to layered ascii output files."
optional = true

[blocks.options.fields.export_array_netcdf]
name = "export_array_netcdf"
longname = "export array variables to netcdf output files."
description = "keyword that specifies input gridded arrays should be written to the model output netcdf file with attributes that support using the generated file as a modflow 6 simulation input.  this option only has an effect when an output model netcdf file is configured and the simulation is run in validate mode, otherwise it is ignored."
optional = true

[blocks.options.fields.dev_original_specific_storage]
name = "dev_original_specific_storage"
longname = "development option for original specific storage"
description = "flag indicating the original storage specific storage formulation should be used"
optional = true

[blocks.options.fields.dev_oldstorageformulation]
name = "dev_oldstorageformulation"
longname = "development option flag for old storage formulation"
description = "development option flag for old storage formulation"
optional = true

[blocks.griddata]
name = "griddata"

[blocks.griddata.fields.iconvert]
name = "iconvert"
longname = "convertible indicator"
description = "is a flag for each cell that specifies whether or not a cell is convertible for the storage calculation. 0 indicates confined storage is used. $>$0 indicates confined storage is used when head is above cell top and a mixed formulation of unconfined and confined storage is used when head is below cell top."
netcdf = true
dtype = "integer"
shape = [
    "nodes",
]

[blocks.griddata.fields.ss]
name = "ss"
longname = "specific storage"
description = "is specific storage (or the storage coefficient if storagecoefficient is specified as an option). specific storage values must be greater than or equal to 0. if the csub package is included in the gwf model, specific storage must be zero for every cell."
netcdf = true
dtype = "double"
shape = [
    "nodes",
]

[blocks.griddata.fields.sy]
name = "sy"
longname = "specific yield"
description = "is specific yield. specific yield values must be greater than or equal to 0. specific yield does not have to be specified if there are no convertible cells (iconvert=0 in every cell)."
netcdf = true
dtype = "double"
shape = [
    "nodes",
]

[blocks.period]
name = "period"

[blocks.period.fields.steady-state]
name = "steady-state"
longname = "steady state indicator"
description = "keyword to indicate that stress period iper is steady-state. steady-state conditions will apply until the transient keyword is specified in a subsequent begin period block. if the csub package is included in the gwf model, only the first and last stress period can be steady-state."
optional = true

[blocks.period.fields.transient]
name = "transient"
longname = "transient indicator"
description = "keyword to indicate that stress period iper is transient. transient conditions will apply until the steady-state keyword is specified in a subsequent begin period block."
optional = true
