name = "gwf-npf"
schema_version = "2"

[blocks.options]
name = "options"

[blocks.options.fields.save_flows]
name = "save_flows"
longname = "keyword to save npf flows"
description = "keyword to indicate that budget flow terms will be written to the file specified with 'budget save file' in output control."
optional = true

[blocks.options.fields.print_flows]
name = "print_flows"
longname = "keyword to print npf flows to listing file"
description = "keyword to indicate that calculated flows between cells will be printed to the listing file for every stress period time step in which 'budget print' is specified in output control. if there is no output control option and 'print_flows' is specified, then flow rates are printed for the last time step of each stress period.  this option can produce extremely large list files because all cell-by-cell flows are printed.  it should only be used with the npf package for models that have a small number of cells."
optional = true

[blocks.options.fields.alternative_cell_averaging]
name = "alternative_cell_averaging"
longname = "conductance weighting option"
description = "is a text keyword to indicate that an alternative method will be used for calculating the conductance for horizontal cell connections.  the text value for alternative_cell_averaging can be 'logarithmic', 'amt-lmk', or 'amt-hmk'.  'amt-lmk' signifies that the conductance will be calculated using arithmetic-mean thickness and logarithmic-mean hydraulic conductivity.  'amt-hmk' signifies that the conductance will be calculated using arithmetic-mean thickness and harmonic-mean hydraulic conductivity. if the user does not specify a value for alternative_cell_averaging, then the harmonic-mean method will be used.  this option cannot be used if the xt3d option is invoked. the amt-hmk alternative_cell_averaging option, in combination with the dry_cell_saturation option, can be used to calculate the same horizontal conductance as modflow-usg when upstream weighting is used (laycon=4)."
optional = true
tagged = false
valid = [
    "l",
    "o",
    "g",
    "a",
    "r",
    "i",
    "t",
    "h",
    "m",
    "i",
    "c",
    " ",
    "a",
    "m",
    "t",
    "-",
    "l",
    "m",
    "k",
    " ",
    "a",
    "m",
    "t",
    "-",
    "h",
    "m",
    "k",
]

[blocks.options.fields.thickstrt]
name = "thickstrt"
longname = "keyword to activate thickstrt option"
description = "indicates that cells having a negative icelltype are confined, and their cell thickness for conductance calculations will be computed as strt-bot rather than top-bot.  this option should be used with caution as it only affects conductance calculations in the npf package."
optional = true

[blocks.options.fields.cvoptions]
name = "cvoptions"
longname = "vertical conductance options"
description = "none"
optional = true

[blocks.options.fields.cvoptions.fields.variablecv]
name = "variablecv"
longname = "keyword to activate variablecv option"
description = "keyword to indicate that the vertical conductance will be calculated using the saturated thickness and properties of the overlying cell and the thickness and properties of the underlying cell.  if the dewatered keyword is also specified, then the vertical conductance is calculated using only the saturated thickness and properties of the overlying cell if the head in the underlying cell is below its top.  if these keywords are not specified, then the default condition is to calculate the vertical conductance at the start of the simulation using the initial head and the cell properties.  the vertical conductance remains constant for the entire simulation."

[blocks.options.fields.cvoptions.fields.dewatered]
name = "dewatered"
longname = "keyword to activate dewatered option"
description = "if the dewatered keyword is specified, then the vertical conductance is calculated using only the saturated thickness and properties of the overlying cell if the head in the underlying cell is below its top."
optional = true

[blocks.options.fields.perched]
name = "perched"
longname = "keyword to activate perched option"
description = "keyword to indicate that when a cell is overlying a dewatered convertible cell, the head difference used in darcy's law is equal to the head in the overlying cell minus the bottom elevation of the overlying cell.  if not specified, then the default is to use the head difference between the two cells."
optional = true

[blocks.options.fields.rewet_record]
name = "rewet_record"
optional = true

[blocks.options.fields.rewet_record.fields.rewet]
name = "rewet"
longname = "keyword to activate rewetting"
description = "activates model rewetting.  rewetting is off by default."

[blocks.options.fields.rewet_record.fields.wetfct]
name = "wetfct"
longname = "wetting factor to use for rewetting"
description = "is a keyword and factor that is included in the calculation of the head that is initially established at a cell when that cell is converted from dry to wet."
tagged = false

[blocks.options.fields.rewet_record.fields.iwetit]
name = "iwetit"
longname = "interval to use for rewetting"
description = "is a keyword and iteration interval for attempting to wet cells. wetting is attempted every iwetit iteration. this applies to outer iterations and not inner iterations. if iwetit is specified as zero or less, then the value is changed to 1."
tagged = false

[blocks.options.fields.rewet_record.fields.ihdwet]
name = "ihdwet"
longname = "flag to determine wetting equation"
description = "is a keyword and integer flag that determines which equation is used to define the initial head at cells that become wet.  if ihdwet is 0, h = bot + wetfct (hm - bot). if ihdwet is not 0, h = bot + wetfct (thresh)."
tagged = false

[blocks.options.fields.xt3doptions]
name = "xt3doptions"
longname = "keyword to activate xt3d"
description = "none"
optional = true

[blocks.options.fields.xt3doptions.fields.xt3d]
name = "xt3d"
longname = "keyword to activate xt3d"
description = "keyword indicating that the xt3d formulation will be used.  if the rhs keyword is also included, then the xt3d additional terms will be added to the right-hand side.  if the rhs keyword is excluded, then the xt3d terms will be put into the coefficient matrix.  use of xt3d will substantially increase the computational effort, but will result in improved accuracy for anisotropic conductivity fields and for unstructured grids in which the cvfd requirement is violated.  xt3d requires additional information about the shapes of grid cells.  if xt3d is active and the disu package is used, then the user will need to provide in the disu package the angldegx array in the connectiondata block and the vertices and cell2d blocks."

[blocks.options.fields.xt3doptions.fields.rhs]
name = "rhs"
longname = "keyword to xt3d on right hand side"
description = "if the rhs keyword is also included, then the xt3d additional terms will be added to the right-hand side.  if the rhs keyword is excluded, then the xt3d terms will be put into the coefficient matrix."
optional = true

[blocks.options.fields.highest_cell_saturation]
name = "highest_cell_saturation"
longname = "keyword to activate highest_cell_saturation option"
description = "keyword indicating that the maximum cell bottom will be used to calculate the saturation used to calculate the horizontal conductance between cells. this option is intended to prevent flow from leaving a dry cell and is based on~cite{painter2008robust}. this option is only applied when the newton-raphson formulation is used, a warning will be issued if this option is specified and the newton-raphson formulation is not specified in the gwf name file. this option, in combination with the amt-hmk alternative_cell_averaging option, can be used to calculate the same horizontal conductance as modflow-usg when upstream weighting is used (laycon=4)."
optional = true

[blocks.options.fields.save_specific_discharge]
name = "save_specific_discharge"
longname = "keyword to save specific discharge"
description = "keyword to indicate that x, y, and z components of specific discharge will be calculated at cell centers and written to the budget file, which is specified with 'budget save file' in output control.  if this option is activated, then additional information may be required in the discretization packages and the gwf exchange package (if gwf models are coupled).  specifically, angldegx must be specified in the connectiondata block of the disu package; angldegx must also be specified for the gwf exchange as an auxiliary variable."
optional = true

[blocks.options.fields.save_saturation]
name = "save_saturation"
longname = "keyword to save saturation"
description = "keyword to indicate that cell saturation will be written to the budget file, which is specified with 'budget save file' in output control.  saturation will be saved to the budget file as an auxiliary variable saved with the data-sat text label.  saturation is a cell variable that ranges from zero to one and can be used by post processing programs to determine how much of a cell volume is saturated.  if icelltype is 0, then saturation is always one."
optional = true

[blocks.options.fields.k22overk]
name = "k22overk"
longname = "keyword to indicate that specified k22 is a ratio"
description = "keyword to indicate that specified k22 is a ratio of k22 divided by k.  if this option is specified, then the k22 array entered in the npf package will be multiplied by k after being read."
optional = true

[blocks.options.fields.k33overk]
name = "k33overk"
longname = "keyword to indicate that specified k33 is a ratio"
description = "keyword to indicate that specified k33 is a ratio of k33 divided by k.  if this option is specified, then the k33 array entered in the npf package will be multiplied by k after being read."
optional = true

[blocks.options.fields.tvk_filerecord]
name = "tvk_filerecord"
optional = true

[blocks.options.fields.tvk_filerecord.fields.tvk6]
name = "tvk6"
longname = "tvk keyword"
description = "keyword to specify that record corresponds to a time-varying hydraulic conductivity (tvk) file.  the behavior of tvk and a description of the input file is provided separately."

[blocks.options.fields.tvk_filerecord.fields.filein]
name = "filein"
longname = "file keyword"
description = "keyword to specify that an input filename is expected next."

[blocks.options.fields.tvk_filerecord.fields.tvk6_filename]
name = "tvk6_filename"
longname = "file name of tvk information"
description = "defines a time-varying hydraulic conductivity (tvk) input file.  records in the tvk file can be used to change hydraulic conductivity properties at specified times or stress periods."
tagged = false
case_sensitive = true

[blocks.options.fields.export_array_ascii]
name = "export_array_ascii"
longname = "export array variables to layered ascii files."
description = "keyword that specifies input griddata arrays should be written to layered ascii output files."
optional = true

[blocks.options.fields.export_array_netcdf]
name = "export_array_netcdf"
longname = "export array variables to netcdf output files."
description = "keyword that specifies input gridded arrays should be written to the model output netcdf file with attributes that support using the generated file as a modflow 6 simulation input.  this option only has an effect when an output model netcdf file is configured and the simulation is run in validate mode, otherwise it is ignored."
optional = true

[blocks.options.fields.dev_no_newton]
name = "dev_no_newton"
longname = "turn off newton for unconfined cells"
description = "turn off newton for unconfined cells"
optional = true

[blocks.options.fields.dev_omega]
name = "dev_omega"
longname = "set saturation omega value"
description = "set saturation omega value"
optional = true
tagged = false

[blocks.griddata]
name = "griddata"

[blocks.griddata.fields.icelltype]
name = "icelltype"
longname = "confined or convertible indicator"
description = "flag for each cell that specifies how saturated thickness is treated.  0 means saturated thickness is held constant;  $>$0 means saturated thickness varies with computed head when head is below the cell top; $<$0 means saturated thickness varies with computed head unless the thickstrt option is in effect.  when thickstrt is in effect, a negative value for icelltype indicates that the saturated thickness value used in conductance calculations in the npf package will be computed as strt-bot and held constant.  if the thickstrt option is not in effect, then negative values provided by the user for icelltype are automatically reassigned by the program to a value of one."
netcdf = true
dtype = "integer"
shape = [
    "nodes",
]

[blocks.griddata.fields.k]
name = "k"
longname = "hydraulic conductivity (l/t)"
description = "is the hydraulic conductivity.  for the common case in which the user would like to specify the horizontal hydraulic conductivity and the vertical hydraulic conductivity, then k should be assigned as the horizontal hydraulic conductivity, k33 should be assigned as the vertical hydraulic conductivity, and k22 and the three rotation angles should not be specified.  when more sophisticated anisotropy is required, then k corresponds to the k11 hydraulic conductivity axis.  all included cells (idomain $>$ 0) must have a k value greater than zero."
netcdf = true
dtype = "double"
shape = [
    "nodes",
]

[blocks.griddata.fields.k22]
name = "k22"
longname = "hydraulic conductivity of second ellipsoid axis"
description = "is the hydraulic conductivity of the second ellipsoid axis (or the ratio of k22/k if the k22overk option is specified); for an unrotated case this is the hydraulic conductivity in the y direction.  if k22 is not included in the griddata block, then k22 is set equal to k.  for a regular modflow grid (dis package is used) in which no rotation angles are specified, k22 is the hydraulic conductivity along columns in the y direction. for an unstructured disu grid, the user must assign principal x and y axes and provide the angle for each cell face relative to the assigned x direction.  all included cells (idomain $>$ 0) must have a k22 value greater than zero."
optional = true
netcdf = true
dtype = "double"
shape = [
    "nodes",
]

[blocks.griddata.fields.k33]
name = "k33"
longname = "hydraulic conductivity of third ellipsoid axis (l/t)"
description = "is the hydraulic conductivity of the third ellipsoid axis (or the ratio of k33/k if the k33overk option is specified); for an unrotated case, this is the vertical hydraulic conductivity.  when anisotropy is applied, k33 corresponds to the k33 tensor component.  all included cells (idomain $>$ 0) must have a k33 value greater than zero."
optional = true
netcdf = true
dtype = "double"
shape = [
    "nodes",
]

[blocks.griddata.fields.angle1]
name = "angle1"
longname = "first anisotropy rotation angle (degrees)"
description = "is a rotation angle of the hydraulic conductivity tensor in degrees. the angle represents the first of three sequential rotations of the hydraulic conductivity ellipsoid. with the k11, k22, and k33 axes of the ellipsoid initially aligned with the x, y, and z coordinate axes, respectively, angle1 rotates the ellipsoid about its k33 axis (within the x - y plane). a positive value represents counter-clockwise rotation when viewed from any point on the positive k33 axis, looking toward the center of the ellipsoid. a value of zero indicates that the k11 axis lies within the x - z plane. if angle1 is not specified, default values of zero are assigned to angle1, angle2, and angle3, in which case the k11, k22, and k33 axes are aligned with the x, y, and z axes, respectively."
optional = true
netcdf = true
dtype = "double"
shape = [
    "nodes",
]

[blocks.griddata.fields.angle2]
name = "angle2"
longname = "second anisotropy rotation angle (degrees)"
description = "is a rotation angle of the hydraulic conductivity tensor in degrees. the angle represents the second of three sequential rotations of the hydraulic conductivity ellipsoid. following the rotation by angle1 described above, angle2 rotates the ellipsoid about its k22 axis (out of the x - y plane). an array can be specified for angle2 only if angle1 is also specified. a positive value of angle2 represents clockwise rotation when viewed from any point on the positive k22 axis, looking toward the center of the ellipsoid. a value of zero indicates that the k11 axis lies within the x - y plane. if angle2 is not specified, default values of zero are assigned to angle2 and angle3; connections that are not user-designated as vertical are assumed to be strictly horizontal (that is, to have no z component to their orientation); and connection lengths are based on horizontal distances."
optional = true
netcdf = true
dtype = "double"
shape = [
    "nodes",
]

[blocks.griddata.fields.angle3]
name = "angle3"
longname = "third anisotropy rotation angle (degrees)"
description = "is a rotation angle of the hydraulic conductivity tensor in degrees. the angle represents the third of three sequential rotations of the hydraulic conductivity ellipsoid. following the rotations by angle1 and angle2 described above, angle3 rotates the ellipsoid about its k11 axis. an array can be specified for angle3 only if angle1 and angle2 are also specified. an array must be specified for angle3 if angle2 is specified. a positive value of angle3 represents clockwise rotation when viewed from any point on the positive k11 axis, looking toward the center of the ellipsoid. a value of zero indicates that the k22 axis lies within the x - y plane."
optional = true
netcdf = true
dtype = "double"
shape = [
    "nodes",
]

[blocks.griddata.fields.wetdry]
name = "wetdry"
longname = "wetdry threshold and factor"
description = "is a combination of the wetting threshold and a flag to indicate which neighboring cells can cause a cell to become wet. if wetdry $<$ 0, only a cell below a dry cell can cause the cell to become wet. if wetdry $>$ 0, the cell below a dry cell and horizontally adjacent cells can cause a cell to become wet. if wetdry is 0, the cell cannot be wetted. the absolute value of wetdry is the wetting threshold. when the sum of bot and the absolute value of wetdry at a dry cell is equaled or exceeded by the head at an adjacent cell, the cell is wetted.  wetdry must be specified if 'rewet' is specified in the options block.  if 'rewet' is not specified in the options block, then wetdry can be entered, and memory will be allocated for it, even though it is not used."
optional = true
netcdf = true
dtype = "double"
shape = [
    "nodes",
]
