name = "gwf-mvr"
parent = [
    "model",
    "package",
]
schema_version = "2"
subtype = "stress"

[blocks.options]
name = "options"

[blocks.options.fields.print_input]
name = "print_input"
longname = "print input to listing file"
description = "keyword to indicate that the list of mvr information will be written to the listing file immediately after it is read."
optional = true

[blocks.options.fields.print_flows]
name = "print_flows"
longname = "print calculated flows to listing file"
description = "keyword to indicate that the list of mvr flow rates will be printed to the listing file for every stress period time step in which 'budget print' is specified in output control.  if there is no output control option and 'print_flows' is specified, then flow rates are printed for the last time step of each stress period."
optional = true

[blocks.options.fields.modelnames]
name = "modelnames"
longname = "precede all package names with model names"
description = "keyword to indicate that all package names will be preceded by the model name for the package.  model names are required when the mover package is used with a gwf-gwf exchange.  the modelname keyword should not be used for a mover package that is for a single gwf model."
optional = true

[blocks.options.fields.budget_filerecord]
name = "budget_filerecord"
optional = true

[blocks.options.fields.budget_filerecord.fields.budget]
name = "budget"
longname = "budget keyword"
description = "keyword to specify that record corresponds to the budget."

[blocks.options.fields.budget_filerecord.fields.fileout]
name = "fileout"
longname = "file keyword"
description = "keyword to specify that an output filename is expected next."

[blocks.options.fields.budget_filerecord.fields.budgetfile]
name = "budgetfile"
longname = "file keyword"
description = "name of the output file to write budget information."
tagged = false
case_sensitive = true

[blocks.options.fields.budgetcsv_filerecord]
name = "budgetcsv_filerecord"
optional = true

[blocks.options.fields.budgetcsv_filerecord.fields.budgetcsv]
name = "budgetcsv"
longname = "budget keyword"
description = "keyword to specify that record corresponds to the budget csv."

[blocks.options.fields.budgetcsv_filerecord.fields.fileout]
name = "fileout"
longname = "file keyword"
description = "keyword to specify that an output filename is expected next."

[blocks.options.fields.budgetcsv_filerecord.fields.budgetcsvfile]
name = "budgetcsvfile"
longname = "file keyword"
description = "name of the comma-separated value (csv) output file to write budget summary information.  a budget summary record will be written to this file for each time step of the simulation."
tagged = false
case_sensitive = true

[blocks.dimensions]
name = "dimensions"

[blocks.dimensions.fields.maxmvr]
name = "maxmvr"
longname = "maximum number of movers"
description = "integer value specifying the maximum number of water mover entries that will specified for any stress period."
tagged = false

[blocks.dimensions.fields.maxpackages]
name = "maxpackages"
longname = "number of packages to be used with the mover"
description = "integer value specifying the number of unique packages that are included in this water mover input file."
tagged = false

[blocks.packages]
name = "packages"

[blocks.packages.fields.packages]
name = "packages"

[blocks.packages.fields.packages.item]
name = "packages"

[blocks.packages.fields.packages.item.fields.mname]
name = "mname"
description = "name of model containing the package.  model names are assigned by the user in the simulation name file."
optional = true
tagged = false

[blocks.packages.fields.packages.item.fields.pname]
name = "pname"
description = "is the name of a package that may be included in a subsequent stress period block.  the package name is assigned in the name file for the gwf model.  package names are optionally provided in the name file.  if they are not provided by the user, then packages are assigned a default value, which is the package acronym followed by a hyphen and the package number.  for example, the first drain package is named drn-1.  the second drain package is named drn-2, and so forth."
tagged = false

[blocks.period]
name = "period"

[blocks.period.fields.perioddata]
name = "perioddata"

[blocks.period.fields.perioddata.item]
name = "perioddata"

[blocks.period.fields.perioddata.item.fields.mname1]
name = "mname1"
description = "name of model containing the package, pname1."
optional = true
tagged = false

[blocks.period.fields.perioddata.item.fields.pname1]
name = "pname1"
longname = "provider package name"
description = "is the package name for the provider.  the package pname1 must be designated to provide water through the mvr package by specifying the keyword 'mover' in its options block."
tagged = false

[blocks.period.fields.perioddata.item.fields.id1]
name = "id1"
longname = "provider reach"
description = "is the identifier for the provider.  for the standard boundary packages, the provider identifier is the number of the boundary as it is listed in the package input file. (note that the order of these boundaries may change by stress period, which must be accounted for in the mover package.)  so the first well has an identifier of one.  the second is two, and so forth.  for the advanced packages, the identifier is the reach number (sfr package), well number (maw package), or uzf cell number.  for the lake package, id1 is the lake outlet number.  thus, outflows from a single lake can be routed to different streams, for example."
tagged = false

[blocks.period.fields.perioddata.item.fields.mname2]
name = "mname2"
description = "name of model containing the package, pname2."
optional = true
tagged = false

[blocks.period.fields.perioddata.item.fields.pname2]
name = "pname2"
longname = "receiver package name"
description = "is the package name for the receiver.  the package pname2 must be designated to receive water from the mvr package by specifying the keyword 'mover' in its options block."
tagged = false

[blocks.period.fields.perioddata.item.fields.id2]
name = "id2"
longname = "receiver reach"
description = "is the identifier for the receiver.  the receiver identifier is the reach number (sfr package), lake number (lak package), well number (maw package), or uzf cell number."
tagged = false

[blocks.period.fields.perioddata.item.fields.mvrtype]
name = "mvrtype"
longname = "mover type"
description = "is the character string signifying the method for determining how much water will be moved.  supported values are 'factor' 'excess' 'threshold' and 'upto'.  these four options determine how the receiver flow rate, $q_r$, is calculated.  these options mirror the options defined for the cprior variable in the sfr package, with the term 'factor' being functionally equivalent to the 'fraction' option for cprior."
tagged = false

[blocks.period.fields.perioddata.item.fields.value]
name = "value"
longname = "mover value"
description = "is the value to be used in the equation for calculating the amount of water to move.  for the 'factor' option, value is the $alpha$ factor.  for the remaining options, value is the specified flow rate, $q_s$."
tagged = false

[dims.maxmvr]
field = "maxmvr"
scope = "gwf"

[dims.maxpackages]
field = "maxpackages"
scope = "gwf"
