name = "gwf-chdg"
schema_version = "2"
multi = true
subtype = "stress"

[blocks.options]
name = "options"

[blocks.options.fields.readarraygrid]
name = "readarraygrid"
longname = "use array-based grid input"
description = "indicates that array-based grid input will be used for the constant head package.  this keyword must be specified to use array-based grid input.  when readarraygrid is specified, values must be provided for every cell within a model grid, even those cells that have an idomain value less than one.  values assigned to cells with idomain values less than one are not used and have no effect on simulation results. no data cells should contain the value dnodata (3.0e+30)."
developmode = true

[blocks.options.fields.auxiliary]
name = "auxiliary"
longname = "keyword to specify aux variables"
description = "defines an array of one or more auxiliary variable names.  there is no limit on the number of auxiliary variables that can be provided on this line; however, lists of information provided in subsequent blocks must have a column of data for each auxiliary variable name defined here.   the number of auxiliary variables detected on this line determines the value for naux.  comments cannot be provided anywhere on this line as they will be interpreted as auxiliary variable names.  auxiliary variables may not be used by the package, but they will be available for use by other parts of the program.  the program will terminate with an error if auxiliary variables are specified on more than one line in the options block."
optional = true
dtype = "string"

[blocks.options.fields.auxmultname]
name = "auxmultname"
longname = "name of auxiliary variable for multiplier"
description = "name of auxiliary variable to be used as multiplier of chd head value."
optional = true
tagged = false

[blocks.options.fields.print_input]
name = "print_input"
longname = "print input to listing file"
description = "keyword to indicate that the list of constant-head information will be written to the listing file immediately after it is read."
optional = true

[blocks.options.fields.print_flows]
name = "print_flows"
longname = "print chd flows to listing file"
description = "keyword to indicate that the list of constant-head flow rates will be printed to the listing file for every stress period time step in which 'budget print' is specified in output control.  if there is no output control option and 'print_flows' is specified, then flow rates are printed for the last time step of each stress period."
optional = true

[blocks.options.fields.save_flows]
name = "save_flows"
longname = "save chd flows to budget file"
description = "keyword to indicate that constant-head flow terms will be written to the file specified with 'budget fileout' in output control."
optional = true

[blocks.options.fields.obs_filerecord]
name = "obs_filerecord"
optional = true

[blocks.options.fields.obs_filerecord.fields.obs6]
name = "obs6"
longname = "obs keyword"
description = "keyword to specify that record corresponds to an observations file."

[blocks.options.fields.obs_filerecord.fields.filein]
name = "filein"
longname = "file keyword"
description = "keyword to specify that an input filename is expected next."

[blocks.options.fields.obs_filerecord.fields.obs6_filename]
name = "obs6_filename"
longname = "obs6 input filename"
description = "name of input file to define observations for the chd package. see the 'observation utility' section for instructions for preparing observation input files. table {#2} lists observation type(s) supported by the chd package."
tagged = false
case_sensitive = true

[blocks.options.fields.export_array_netcdf]
name = "export_array_netcdf"
longname = "export array variables to netcdf output files."
description = "keyword that specifies input gridded arrays should be written to the model output netcdf file with attributes that support using the generated file as a modflow 6 simulation input.  this option only has an effect when an output model netcdf file is configured and the simulation is run in validate mode, otherwise it is ignored."
optional = true

[blocks.options.fields.dev_no_newton]
name = "dev_no_newton"
longname = "turn off newton for unconfined cells"
description = "turn off newton for unconfined cells"
optional = true

[blocks.dimensions]
name = "dimensions"

[blocks.dimensions.fields.maxbound]
name = "maxbound"
longname = "maximum number of constant head cells in any stress period"
description = "integer value specifying the maximum number of constant-head cells that will be specified for use during any stress period."
optional = true
tagged = false

[blocks.period]
name = "period"

[blocks.period.fields.head]
name = "head"
longname = "head value assigned to constant head"
description = "is the head at the boundary."
netcdf = true
dtype = "double"
shape = [
    "nodes",
]

[blocks.period.fields.aux]
name = "aux"
longname = "constant head auxiliary variable iaux"
description = "is an array of values for auxiliary variable aux(iaux), where iaux is a value from 1 to naux, and aux(iaux) must be listed as part of the auxiliary variables.  a separate array can be specified for each auxiliary variable. if the value specified here for the auxiliary variable is the same as auxmultname, then the head array will be multiplied by this array."
optional = true
netcdf = true
dtype = "double"
shape = [
    "nodes",
]

[dims.maxbound]
field = "maxbound"
scope = "gwf"
