name = "gwt-sft"
schema_version = "2"
multi = true
subtype = "stress"

[blocks.options]
name = "options"

[blocks.options.fields.flow_package_name]
name = "flow_package_name"
longname = "keyword to specify name of corresponding flow package"
description = "keyword to specify the name of the corresponding flow package.  if not specified, then the corresponding flow package must have the same name as this advanced transport package (the name associated with this package in the gwt name file)."
optional = true
tagged = false

[blocks.options.fields.auxiliary]
name = "auxiliary"
longname = "keyword to specify aux variables"
description = "defines an array of one or more auxiliary variable names.  there is no limit on the number of auxiliary variables that can be provided on this line; however, lists of information provided in subsequent blocks must have a column of data for each auxiliary variable name defined here.   the number of auxiliary variables detected on this line determines the value for naux.  comments cannot be provided anywhere on this line as they will be interpreted as auxiliary variable names.  auxiliary variables may not be used by the package, but they will be available for use by other parts of the program.  the program will terminate with an error if auxiliary variables are specified on more than one line in the options block."
optional = true
dtype = "string"

[blocks.options.fields.flow_package_auxiliary_name]
name = "flow_package_auxiliary_name"
longname = "keyword to specify name of concentration auxiliary variable in flow package"
description = "keyword to specify the name of an auxiliary variable in the corresponding flow package.  if specified, then the simulated concentrations from this advanced transport package will be copied into the auxiliary variable specified with this name.  note that the flow package must have an auxiliary variable with this name or the program will terminate with an error.  if the flows for this advanced transport package are read from a file, then this option will have no effect."
optional = true
tagged = false

[blocks.options.fields.boundnames]
name = "boundnames"
description = "keyword to indicate that boundary names may be provided with the list of reach cells."
optional = true

[blocks.options.fields.print_input]
name = "print_input"
longname = "print input to listing file"
description = "keyword to indicate that the list of reach information will be written to the listing file immediately after it is read."
optional = true

[blocks.options.fields.print_concentration]
name = "print_concentration"
longname = "print calculated concentrations to listing file"
description = "keyword to indicate that the list of reach {#2} will be printed to the listing file for every stress period in which 'concentration print' is specified in output control.  if there is no output control option and print_{#3} is specified, then {#2} are printed for the last time step of each stress period."
optional = true

[blocks.options.fields.print_flows]
name = "print_flows"
longname = "print calculated flows to listing file"
description = "keyword to indicate that the list of reach flow rates will be printed to the listing file for every stress period time step in which 'budget print' is specified in output control.  if there is no output control option and 'print_flows' is specified, then flow rates are printed for the last time step of each stress period."
optional = true

[blocks.options.fields.save_flows]
name = "save_flows"
longname = "save reach flows to budget file"
description = "keyword to indicate that reach flow terms will be written to the file specified with 'budget fileout' in output control."
optional = true

[blocks.options.fields.concentration_filerecord]
name = "concentration_filerecord"
optional = true

[blocks.options.fields.concentration_filerecord.fields.concentration]
name = "concentration"
longname = "concentration keyword"
description = "keyword to specify that record corresponds to concentration."

[blocks.options.fields.concentration_filerecord.fields.fileout]
name = "fileout"
longname = "file keyword"
description = "keyword to specify that an output filename is expected next."

[blocks.options.fields.concentration_filerecord.fields.concfile]
name = "concfile"
longname = "file keyword"
description = "name of the binary output file to write concentration information."
tagged = false
case_sensitive = true

[blocks.options.fields.budget_filerecord]
name = "budget_filerecord"
optional = true

[blocks.options.fields.budget_filerecord.fields.budget]
name = "budget"
longname = "budget keyword"
description = "keyword to specify that record corresponds to the budget."

[blocks.options.fields.budget_filerecord.fields.fileout]
name = "fileout"
longname = "file keyword"
description = "keyword to specify that an output filename is expected next."

[blocks.options.fields.budget_filerecord.fields.budgetfile]
name = "budgetfile"
longname = "file keyword"
description = "name of the binary output file to write budget information."
tagged = false
case_sensitive = true

[blocks.options.fields.budgetcsv_filerecord]
name = "budgetcsv_filerecord"
optional = true

[blocks.options.fields.budgetcsv_filerecord.fields.budgetcsv]
name = "budgetcsv"
longname = "budget keyword"
description = "keyword to specify that record corresponds to the budget csv."

[blocks.options.fields.budgetcsv_filerecord.fields.fileout]
name = "fileout"
longname = "file keyword"
description = "keyword to specify that an output filename is expected next."

[blocks.options.fields.budgetcsv_filerecord.fields.budgetcsvfile]
name = "budgetcsvfile"
longname = "file keyword"
description = "name of the comma-separated value (csv) output file to write budget summary information.  a budget summary record will be written to this file for each time step of the simulation."
tagged = false
case_sensitive = true

[blocks.options.fields.ts_filerecord]
name = "ts_filerecord"
optional = true

[blocks.options.fields.ts_filerecord.fields.ts6]
name = "ts6"
longname = "head keyword"
description = "keyword to specify that record corresponds to a time-series file."

[blocks.options.fields.ts_filerecord.fields.filein]
name = "filein"
longname = "file keyword"
description = "keyword to specify that an input filename is expected next."

[blocks.options.fields.ts_filerecord.fields.ts6_filename]
name = "ts6_filename"
longname = "file name of time series information"
description = "defines a time-series file defining time series that can be used to assign time-varying values. see the 'time-variable input' section for instructions on using the time-series capability."
tagged = false
case_sensitive = true

[blocks.options.fields.obs_filerecord]
name = "obs_filerecord"
optional = true

[blocks.options.fields.obs_filerecord.fields.obs6]
name = "obs6"
longname = "obs keyword"
description = "keyword to specify that record corresponds to an observations file."

[blocks.options.fields.obs_filerecord.fields.filein]
name = "filein"
longname = "file keyword"
description = "keyword to specify that an input filename is expected next."

[blocks.options.fields.obs_filerecord.fields.obs6_filename]
name = "obs6_filename"
longname = "obs6 input filename"
description = "name of input file to define observations for the sft package. see the 'observation utility' section for instructions for preparing observation input files. table {#2} lists observation type(s) supported by the sft package."
tagged = false
case_sensitive = true

[blocks.packagedata]
name = "packagedata"

[blocks.packagedata.fields.packagedata]
name = "packagedata"

[blocks.packagedata.fields.packagedata.item]
name = "packagedata"

[blocks.packagedata.fields.packagedata.item.fields.ifno]
name = "ifno"
longname = "reach number for this entry"
description = "integer value that defines the feature (reach) number associated with the specified packagedata data on the line. ifno must be greater than zero and less than or equal to nreaches. reach information must be specified for every reach or the program will terminate with an error.  the program will also terminate with an error if information for a reach is specified more than once."
tagged = false

[blocks.packagedata.fields.packagedata.item.fields.strt]
name = "strt"
longname = "starting reach concentration"
description = "real value that defines the starting concentration for the reach."
tagged = false

[blocks.packagedata.fields.packagedata.item.fields.aux]
name = "aux"
longname = "auxiliary variables"
description = "represents the values of the auxiliary variables for each reach. the values of auxiliary variables must be present for each reach. the values must be specified in the order of the auxiliary variables specified in the options block.  if the package supports time series and the options block includes a timeseriesfile entry (see the 'time-variable input' section), values can be obtained from a time series by entering the time-series name in place of a numeric value."
optional = true
dtype = "double"
shape = [
    "auxiliary",
]
time_series = true

[blocks.packagedata.fields.packagedata.item.fields.boundname]
name = "boundname"
longname = "well name"
description = "name of the reach cell.  boundname is an ascii character variable that can contain as many as 40 characters.  if boundname contains spaces in it, then the entire name must be enclosed within single quotes."
optional = true
tagged = false

[blocks.period]
name = "period"

[blocks.period.fields.reachperioddata]
name = "reachperioddata"

[blocks.period.fields.reachperioddata.item]
name = "reachperioddata"

[blocks.period.fields.reachperioddata.item.fields.ifno]
name = "ifno"
longname = "reach number for this entry"
description = "integer value that defines the feature (reach) number associated with the specified period data on the line. ifno must be greater than zero and less than or equal to nreaches."
tagged = false

[blocks.period.fields.reachperioddata.item.fields.reachsetting]
name = "reachsetting"
description = "line of information that is parsed into a keyword and values.  keyword values that can be used to start the reachsetting string include: status, concentration, rainfall, evaporation, runoff, and auxiliary.  these settings are used to assign the concentration of associated with the corresponding flow terms.  concentrations cannot be specified for all flow terms.  for example, the streamflow package supports a 'diversion' flow term.  diversion water will be routed using the calculated concentration of the reach."

[blocks.period.fields.reachperioddata.item.fields.reachsetting.arms.concentration]
name = "concentration"
longname = "reach concentration"
description = "real or character value that defines the concentration for the reach. the specified concentration is only applied if the reach is a constant concentration reach. if the options block includes a timeseriesfile entry (see the 'time-variable input' section), values can be obtained from a time series by entering the time-series name in place of a numeric value."
time_series = true

[blocks.period.fields.reachperioddata.item.fields.reachsetting.arms.status]
name = "status"
longname = "reach concentration status"
description = "keyword option to define reach status.  status can be active, inactive, or constant. by default, status is active, which means that concentration will be calculated for the reach.  if a reach is inactive, then there will be no solute mass fluxes into or out of the reach and the inactive value will be written for the reach concentration.  if a reach is constant, then the concentration for the reach will be fixed at the user specified value."

[blocks.period.fields.reachperioddata.item.fields.reachsetting.arms.rainfall]
name = "rainfall"
longname = "rainfall concentration"
description = "real or character value that defines the rainfall solute concentration $(ml^{-3})$ for the reach. if the options block includes a timeseriesfile entry (see the 'time-variable input' section), values can be obtained from a time series by entering the time-series name in place of a numeric value."
time_series = true

[blocks.period.fields.reachperioddata.item.fields.reachsetting.arms.evaporation]
name = "evaporation"
longname = "evaporation concentration"
description = "real or character value that defines the concentration of evaporated water $(ml^{-3})$ for the reach. if this concentration value is larger than the simulated concentration in the reach, then the evaporated water will be removed at the same concentration as the reach.  if the options block includes a timeseriesfile entry (see the 'time-variable input' section), values can be obtained from a time series by entering the time-series name in place of a numeric value."
time_series = true

[blocks.period.fields.reachperioddata.item.fields.reachsetting.arms.runoff]
name = "runoff"
longname = "runoff concentration"
description = "real or character value that defines the concentration of runoff $(ml^{-3})$ for the reach. value must be greater than or equal to zero. if the options block includes a timeseriesfile entry (see the 'time-variable input' section), values can be obtained from a time series by entering the time-series name in place of a numeric value."
time_series = true

[blocks.period.fields.reachperioddata.item.fields.reachsetting.arms.inflow]
name = "inflow"
longname = "inflow concentration"
description = "real or character value that defines the concentration of inflow $(ml^{-3})$ for the reach. value must be greater than or equal to zero. if the options block includes a timeseriesfile entry (see the 'time-variable input' section), values can be obtained from a time series by entering the time-series name in place of a numeric value."
time_series = true

[blocks.period.fields.reachperioddata.item.fields.reachsetting.arms.auxiliaryrecord]
name = "auxiliaryrecord"

[blocks.period.fields.reachperioddata.item.fields.reachsetting.arms.auxiliaryrecord.fields.auxiliary]
name = "auxiliary"
description = "keyword for specifying auxiliary variable."

[blocks.period.fields.reachperioddata.item.fields.reachsetting.arms.auxiliaryrecord.fields.auxname]
name = "auxname"
description = "name for the auxiliary variable to be assigned auxval.  auxname must match one of the auxiliary variable names defined in the options block. if auxname does not match one of the auxiliary variable names defined in the options block the data are ignored."
tagged = false

[blocks.period.fields.reachperioddata.item.fields.reachsetting.arms.auxiliaryrecord.fields.auxval]
name = "auxval"
longname = "auxiliary variable value"
description = "value for the auxiliary variable. if the options block includes a timeseriesfile entry (see the 'time-variable input' section), values can be obtained from a time series by entering the time-series name in place of a numeric value."
tagged = false
time_series = true

[dims.auxiliary]
field = "auxiliary"
scope = "component"
