name = "gwt-dsp"
schema_version = "2"

[blocks.options]
name = "options"

[blocks.options.fields.xt3d_off]
name = "xt3d_off"
longname = "deactivate xt3d"
description = "deactivate the xt3d method and use the faster and less accurate approximation.  this option may provide a fast and accurate solution under some circumstances, such as when flow aligns with the model grid, there is no mechanical dispersion, or when the longitudinal and transverse dispersivities are equal.  this option may also be used to assess the computational demand of the xt3d approach by noting the run time differences with and without this option on."
optional = true

[blocks.options.fields.xt3d_rhs]
name = "xt3d_rhs"
longname = "xt3d on right-hand side"
description = "add xt3d terms to right-hand side, when possible.  this option uses less memory, but may require more iterations."
optional = true

[blocks.options.fields.export_array_ascii]
name = "export_array_ascii"
longname = "export array variables to layered ascii files."
description = "keyword that specifies input griddata arrays should be written to layered ascii output files."
optional = true

[blocks.options.fields.export_array_netcdf]
name = "export_array_netcdf"
longname = "export array variables to netcdf output files."
description = "keyword that specifies input gridded arrays should be written to the model output netcdf file with attributes that support using the generated file as a modflow 6 simulation input.  this option only has an effect when an output model netcdf file is configured and the simulation is run in validate mode, otherwise it is ignored."
optional = true

[blocks.griddata]
name = "griddata"

[blocks.griddata.fields.diffc]
name = "diffc"
longname = "effective molecular diffusion coefficient"
description = "effective molecular diffusion coefficient."
optional = true
netcdf = true
dtype = "double"
shape = [
    "nodes",
]

[blocks.griddata.fields.alh]
name = "alh"
longname = "longitudinal dispersivity in horizontal direction"
description = "longitudinal dispersivity in horizontal direction.  if flow is strictly horizontal, then this is the longitudinal dispersivity that will be used.  if flow is not strictly horizontal or strictly vertical, then the longitudinal dispersivity is a function of both alh and alv.  if mechanical dispersion is represented (by specifying any dispersivity values) then this array is required."
optional = true
netcdf = true
dtype = "double"
shape = [
    "nodes",
]

[blocks.griddata.fields.alv]
name = "alv"
longname = "longitudinal dispersivity in vertical direction"
description = "longitudinal dispersivity in vertical direction.  if flow is strictly vertical, then this is the longitudinal dispsersivity value that will be used.  if flow is not strictly horizontal or strictly vertical, then the longitudinal dispersivity is a function of both alh and alv.  if this value is not specified and mechanical dispersion is represented, then this array is set equal to alh."
optional = true
netcdf = true
dtype = "double"
shape = [
    "nodes",
]

[blocks.griddata.fields.ath1]
name = "ath1"
longname = "transverse dispersivity in horizontal direction"
description = "transverse dispersivity in horizontal direction.  this is the transverse dispersivity value for the second ellipsoid axis.  if flow is strictly horizontal and directed in the x direction (along a row for a regular grid), then this value controls spreading in the y direction.  if mechanical dispersion is represented (by specifying any dispersivity values) then this array is required."
optional = true
netcdf = true
dtype = "double"
shape = [
    "nodes",
]

[blocks.griddata.fields.ath2]
name = "ath2"
longname = "transverse dispersivity in horizontal direction"
description = "transverse dispersivity in horizontal direction.  this is the transverse dispersivity value for the third ellipsoid axis.  if flow is strictly horizontal and directed in the x direction (along a row for a regular grid), then this value controls spreading in the z direction.  if this value is not specified and mechanical dispersion is represented, then this array is set equal to ath1."
optional = true
netcdf = true
dtype = "double"
shape = [
    "nodes",
]

[blocks.griddata.fields.atv]
name = "atv"
longname = "transverse dispersivity when flow is in vertical direction"
description = "transverse dispersivity when flow is in vertical direction.  if flow is strictly vertical and directed in the z direction, then this value controls spreading in the x and y directions.  if this value is not specified and mechanical dispersion is represented, then this array is set equal to ath2."
optional = true
netcdf = true
dtype = "double"
shape = [
    "nodes",
]
