name = "gwt-adv"
schema_version = "2"

[blocks.options]
name = "options"

[blocks.options.fields.scheme]
name = "scheme"
longname = "advective scheme"
description = "scheme used to solve the advection term.  can be upstream, central, tvd or utvd.  if not specified, upstream weighting is the default weighting scheme."
optional = true
tagged = false
valid = [
    "c",
    "e",
    "n",
    "t",
    "r",
    "a",
    "l",
    " ",
    "u",
    "p",
    "s",
    "t",
    "r",
    "e",
    "a",
    "m",
    " ",
    "t",
    "v",
    "d",
    " ",
    "u",
    "t",
    "v",
    "d",
]

[blocks.options.fields.ats_percel]
name = "ats_percel"
longname = "fractional cell distance used for time step calculation"
description = "fractional cell distance submitted by the adv package to the adaptive time stepping (ats) package.  if ats_percel is specified and the ats package is active, a time step calculation will be made for each cell based on flow through the cell and cell properties.  the largest time step will be calculated such that the advective fractional cell distance (ats_percel) is not exceeded for any active cell in the grid.  this time-step constraint will be submitted to the ats package, perhaps with constraints submitted by other packages, in the calculation of the time step.  ats_percel must be greater than zero.  if a value of zero is specified for ats_percel the program will automatically reset it to an internal no data value to indicate that time steps should not be subject to this constraint."
optional = true
tagged = false
