name = "olf-disv2d"
schema_version = "2"

[blocks.options]
name = "options"

[blocks.options.fields.length_units]
name = "length_units"
longname = "model length units"
description = "is the length units used for this model.  values can be 'feet', 'meters', or 'centimeters'.  if not specified, the default is 'unknown'."
optional = true
tagged = false

[blocks.options.fields.nogrb]
name = "nogrb"
longname = "do not write binary grid file"
description = "keyword to deactivate writing of the binary grid file."
optional = true

[blocks.options.fields.grb_filerecord]
name = "grb_filerecord"
optional = true

[blocks.options.fields.grb_filerecord.fields.grb6]
name = "grb6"
longname = "grb keyword"
description = "keyword to specify that record corresponds to a binary grid file."

[blocks.options.fields.grb_filerecord.fields.fileout]
name = "fileout"
longname = "file keyword"
description = "keyword to specify that an output filename is expected next."

[blocks.options.fields.grb_filerecord.fields.grb6_filename]
name = "grb6_filename"
longname = "file name of grb information"
description = "defines a binary grid output file. if this option is not provided, the output file will have the same name as the discretization input file, plus extension '.grb'."
tagged = false
case_sensitive = true

[blocks.options.fields.xorigin]
name = "xorigin"
longname = "x-position of the model grid origin"
description = "x-position of the lower-left corner of the model grid.  a default value of zero is assigned if not specified.  the value for xorigin does not affect the model simulation, but it is written to the binary grid file so that postprocessors can locate the grid in space."
optional = true
tagged = false

[blocks.options.fields.yorigin]
name = "yorigin"
longname = "y-position of the model grid origin"
description = "y-position of the lower-left corner of the model grid.  if not specified, then a default value equal to zero is used.  the value for yorigin does not affect the model simulation, but it is written to the binary grid file so that postprocessors can locate the grid in space."
optional = true
tagged = false

[blocks.options.fields.angrot]
name = "angrot"
longname = "rotation angle"
description = "counter-clockwise rotation angle (in degrees) of the lower-left corner of the model grid.  if not specified, then a default value of 0.0 is assigned.  the value for angrot does not affect the model simulation, but it is written to the binary grid file so that postprocessors can locate the grid in space."
optional = true
tagged = false

[blocks.options.fields.export_array_ascii]
name = "export_array_ascii"
longname = "export array variables to layered ascii files."
description = "keyword that specifies input griddata arrays should be written to layered ascii output files."
optional = true

[blocks.options.fields.crs]
name = "crs"
longname = "crs user input string"
description = "is a real-world coordinate reference system (crs) for the model, for example, an epsg integer code (e.g. 26915), authority string (i.e. epsg:26915), or open geospatial consortium well-known text (wkt) specification. limited to 5000 characters. the entry for crs does not affect the model simulation, but it is written to the binary grid file so that postprocessors can locate the grid in space."
optional = true
developmode = true
dtype = "string"

[blocks.dimensions]
name = "dimensions"

[blocks.dimensions.fields.nodes]
name = "nodes"
longname = "number of cells per layer"
description = "is the number of cells per layer.  this is a constant value for the grid and it applies to all layers."
tagged = false

[blocks.dimensions.fields.nvert]
name = "nvert"
longname = "number of columns"
description = "is the total number of (x, y) vertex pairs used to characterize the horizontal configuration of the model grid."
tagged = false

[blocks.griddata]
name = "griddata"

[blocks.griddata.fields.bottom]
name = "bottom"
longname = "model bottom elevation"
description = "is the bottom elevation for each cell."
dtype = "double"
shape = [
    "nodes",
]

[blocks.griddata.fields.idomain]
name = "idomain"
longname = "idomain existence array"
description = "is an optional array that characterizes the existence status of a cell.  if the idomain array is not specified, then all model cells exist within the solution.  if the idomain value for a cell is 0, the cell does not exist in the simulation.  input and output values will be read and written for the cell, but internal to the program, the cell is excluded from the solution.  if the idomain value for a cell is 1 or greater, the cell exists in the simulation.  if the idomain value for a cell is -1, the cell does not exist in the simulation.  furthermore, the first existing cell above will be connected to the first existing cell below.  this type of cell is referred to as a 'vertical pass through' cell."
optional = true
dtype = "integer"
shape = [
    "nodes",
]

[blocks.vertices]
name = "vertices"

[blocks.vertices.fields.vertices]
name = "vertices"
longname = "vertices data"

[blocks.vertices.fields.vertices.item]
name = "vertices"

[blocks.vertices.fields.vertices.item.fields.iv]
name = "iv"
longname = "vertex number"
description = "is the vertex number.  records in the vertices block must be listed in consecutive order from 1 to nvert."
tagged = false

[blocks.vertices.fields.vertices.item.fields.xv]
name = "xv"
longname = "x-coordinate for vertex"
description = "is the x-coordinate for the vertex."
tagged = false

[blocks.vertices.fields.vertices.item.fields.yv]
name = "yv"
longname = "y-coordinate for vertex"
description = "is the y-coordinate for the vertex."
tagged = false

[blocks.cell2d]
name = "cell2d"

[blocks.cell2d.fields.cell2d]
name = "cell2d"
longname = "cell2d data"

[blocks.cell2d.fields.cell2d.item]
name = "cell2d"

[blocks.cell2d.fields.cell2d.item.fields.icell2d]
name = "icell2d"
longname = "cell2d number"
description = "is the cell2d number.  records in the cell2d block must be listed in consecutive order from the first to the last."
tagged = false

[blocks.cell2d.fields.cell2d.item.fields.xc]
name = "xc"
longname = "x-coordinate for cell center"
description = "is the x-coordinate for the cell center."
tagged = false

[blocks.cell2d.fields.cell2d.item.fields.yc]
name = "yc"
longname = "y-coordinate for cell center"
description = "is the y-coordinate for the cell center."
tagged = false

[blocks.cell2d.fields.cell2d.item.fields.ncvert]
name = "ncvert"
longname = "number of cell vertices"
description = "is the number of vertices required to define the cell.  there may be a different number of vertices for each cell."
tagged = false

[blocks.cell2d.fields.cell2d.item.fields.icvert]
name = "icvert"
longname = "array of vertex numbers"
description = "is an array of integer values containing vertex numbers (in the vertices block) used to define the cell.  vertices must be listed in clockwise order.  cells that are connected must share vertices."
dtype = "integer"
shape = [
    "ncvert",
]

[dims.nodes]
field = "nodes"
scope = "olf"

[dims.nvert]
field = "nvert"
scope = "olf"

[dims.ncelldim]
expr = "1"
scope = "olf"
