name = "prt-oc"
schema_version = "2"
subtype = "stress"

[blocks.options]
name = "options"

[blocks.options.fields.budget_filerecord]
name = "budget_filerecord"
optional = true

[blocks.options.fields.budget_filerecord.fields.budget]
name = "budget"
longname = "budget keyword"
description = "keyword to specify that record corresponds to the budget."

[blocks.options.fields.budget_filerecord.fields.fileout]
name = "fileout"
longname = "file keyword"
description = "keyword to specify that an output filename is expected next."

[blocks.options.fields.budget_filerecord.fields.budgetfile]
name = "budgetfile"
longname = "file keyword"
description = "name of the output file to write budget information."
tagged = false
case_sensitive = true

[blocks.options.fields.budgetcsv_filerecord]
name = "budgetcsv_filerecord"
optional = true

[blocks.options.fields.budgetcsv_filerecord.fields.budgetcsv]
name = "budgetcsv"
longname = "budget keyword"
description = "keyword to specify that record corresponds to the budget csv."

[blocks.options.fields.budgetcsv_filerecord.fields.fileout]
name = "fileout"
longname = "file keyword"
description = "keyword to specify that an output filename is expected next."

[blocks.options.fields.budgetcsv_filerecord.fields.budgetcsvfile]
name = "budgetcsvfile"
longname = "file keyword"
description = "name of the comma-separated value (csv) output file to write budget summary information.  a budget summary record will be written to this file for each time step of the simulation."
tagged = false
case_sensitive = true

[blocks.options.fields.track_filerecord]
name = "track_filerecord"
optional = true

[blocks.options.fields.track_filerecord.fields.track]
name = "track"
longname = "track keyword"
description = "keyword to specify that record corresponds to a binary track file.  each prt model's oc package may have only one binary track output file."

[blocks.options.fields.track_filerecord.fields.fileout]
name = "fileout"
longname = "file keyword"
description = "keyword to specify that an output filename is expected next."

[blocks.options.fields.track_filerecord.fields.trackfile]
name = "trackfile"
longname = "file keyword"
description = "name of the binary output file to write tracking information."
tagged = false
case_sensitive = true

[blocks.options.fields.trackcsv_filerecord]
name = "trackcsv_filerecord"
optional = true

[blocks.options.fields.trackcsv_filerecord.fields.trackcsv]
name = "trackcsv"
longname = "track keyword"
description = "keyword to specify that record corresponds to a csv track file.  each prt model's oc package may have only one csv track file."

[blocks.options.fields.trackcsv_filerecord.fields.fileout]
name = "fileout"
longname = "file keyword"
description = "keyword to specify that an output filename is expected next."

[blocks.options.fields.trackcsv_filerecord.fields.trackcsvfile]
name = "trackcsvfile"
longname = "file keyword"
description = "name of the comma-separated value (csv) file to write tracking information."
tagged = false
case_sensitive = true

[blocks.options.fields.track_release]
name = "track_release"
longname = "track release"
description = "keyword to indicate that particle tracking output is to be written when a particle is released"
optional = true

[blocks.options.fields.track_exit]
name = "track_exit"
longname = "track domain exits"
description = "keyword to indicate that particle tracking output is to be written when a particle exits a grid feature (e.g. model, cell)"
optional = true

[blocks.options.fields.track_subfeature_exit]
name = "track_subfeature_exit"
longname = "track cell exits"
description = "keyword to indicate that particle tracking output is to be written when a particle exits a sub-grid-scale feature. such features are considered implementation details of the tracking algorithm employed for particular grid types, and reporting for exit events from such features is disabled by default."
optional = true

[blocks.options.fields.track_timestep]
name = "track_timestep"
longname = "track timestep ends"
description = "keyword to indicate that particle tracking output is to be written at the end of each time step"
optional = true

[blocks.options.fields.track_terminate]
name = "track_terminate"
longname = "track termination"
description = "keyword to indicate that particle tracking output is to be written when a particle terminates for any reason"
optional = true

[blocks.options.fields.track_weaksink]
name = "track_weaksink"
longname = "track weaksink exits"
description = "keyword to indicate that particle tracking output is to be written when a particle exits a weak sink (a cell which removes some but not all inflow from adjacent cells)"
optional = true

[blocks.options.fields.track_usertime]
name = "track_usertime"
longname = "track user-specified times"
description = "keyword to indicate that particle tracking output is to be written at user-specified times, provided as double precision values in the tracktimes block."
optional = true

[blocks.options.fields.track_dropped]
name = "track_dropped"
longname = "track drops to water table"
description = "keyword to indicate that particle tracking output is to be written when a particle is dropped to the water table via dry_tracking_method drop."
optional = true

[blocks.options.fields.track_timesrecord]
name = "track_timesrecord"
optional = true

[blocks.options.fields.track_timesrecord.fields.track_times]
name = "track_times"
description = "keyword indicating tracking times will follow"

[blocks.options.fields.track_timesrecord.fields.times]
name = "times"
longname = "tracking times"
description = "times to track, relative to the beginning of the simulation."
dtype = "double"

[blocks.options.fields.track_timesfilerecord]
name = "track_timesfilerecord"
optional = true

[blocks.options.fields.track_timesfilerecord.fields.track_timesfile]
name = "track_timesfile"
description = "keyword indicating tracking times file name will follow"

[blocks.options.fields.track_timesfilerecord.fields.timesfile]
name = "timesfile"
longname = "file keyword"
description = "name of the tracking times file"
tagged = false
case_sensitive = true

[blocks.options.fields.dev_dump_event_trace]
name = "dev_dump_event_trace"
longname = "print particle tracking events"
description = "print a verbose particle tracking event trace to standard output"
optional = true

[blocks.dimensions]
name = "dimensions"

[blocks.dimensions.fields.ntracktimes]
name = "ntracktimes"
longname = "number of particle tracking times"
description = "is the number of user-specified particle tracking times in the tracktimes block."
optional = true
tagged = false

[blocks.tracktimes]
name = "tracktimes"

[blocks.tracktimes.fields.tracktimes]
name = "tracktimes"
optional = true

[blocks.tracktimes.fields.tracktimes.item]
name = "tracktimes"

[blocks.tracktimes.fields.tracktimes.item.fields.time]
name = "time"
longname = "release time"
description = "real value that defines the tracking time with respect to the simulation start time."
tagged = false

[blocks.period]
name = "period"

[blocks.period.fields.saverecord]
name = "saverecord"
optional = true

[blocks.period.fields.saverecord.fields.save]
name = "save"
longname = "keyword to save"
description = "keyword to indicate that information will be saved this stress period."

[blocks.period.fields.saverecord.fields.rtype]
name = "rtype"
longname = "record type"
description = "type of information to save or print.  can only be budget."
tagged = false

[blocks.period.fields.saverecord.fields.ocsetting]
name = "ocsetting"
description = "specifies the steps for which the data will be saved."

[blocks.period.fields.saverecord.fields.ocsetting.arms.all]
name = "all"
description = "keyword to indicate save for all time steps in period."

[blocks.period.fields.saverecord.fields.ocsetting.arms.first]
name = "first"
description = "keyword to indicate save for first step in period. this keyword may be used in conjunction with other keywords to print or save results for multiple time steps."

[blocks.period.fields.saverecord.fields.ocsetting.arms.last]
name = "last"
description = "keyword to indicate save for last step in period. this keyword may be used in conjunction with other keywords to print or save results for multiple time steps."

[blocks.period.fields.saverecord.fields.ocsetting.arms.frequency]
name = "frequency"
description = "save at the specified time step frequency. this keyword may be used in conjunction with other keywords to print or save results for multiple time steps."

[blocks.period.fields.saverecord.fields.ocsetting.arms.steps]
name = "steps"
description = "save for each step specified in steps. this keyword may be used in conjunction with other keywords to print or save results for multiple time steps."
dtype = "integer"

[blocks.period.fields.printrecord]
name = "printrecord"
optional = true

[blocks.period.fields.printrecord.fields.print]
name = "print"
longname = "keyword to save"
description = "keyword to indicate that information will be printed this stress period."

[blocks.period.fields.printrecord.fields.rtype]
name = "rtype"
longname = "record type"
description = "type of information to save or print.  can only be budget."
tagged = false

[blocks.period.fields.printrecord.fields.ocsetting]
name = "ocsetting"
description = "specifies the steps for which the data will be saved."

[blocks.period.fields.printrecord.fields.ocsetting.arms.all]
name = "all"
description = "keyword to indicate save for all time steps in period."

[blocks.period.fields.printrecord.fields.ocsetting.arms.first]
name = "first"
description = "keyword to indicate save for first step in period. this keyword may be used in conjunction with other keywords to print or save results for multiple time steps."

[blocks.period.fields.printrecord.fields.ocsetting.arms.last]
name = "last"
description = "keyword to indicate save for last step in period. this keyword may be used in conjunction with other keywords to print or save results for multiple time steps."

[blocks.period.fields.printrecord.fields.ocsetting.arms.frequency]
name = "frequency"
description = "save at the specified time step frequency. this keyword may be used in conjunction with other keywords to print or save results for multiple time steps."

[blocks.period.fields.printrecord.fields.ocsetting.arms.steps]
name = "steps"
description = "save for each step specified in steps. this keyword may be used in conjunction with other keywords to print or save results for multiple time steps."
dtype = "integer"

[dims.ntracktimes]
field = "ntracktimes"
scope = "prt"
