name = "sim-nam"
schema_version = "2"

[blocks.options]
name = "options"

[blocks.options.fields.continue]
name = "continue"
longname = "continue if not converged"
description = "keyword flag to indicate that the simulation should continue even if one or more solutions do not converge."
optional = true

[blocks.options.fields.nocheck]
name = "nocheck"
longname = "turn off checking"
description = "keyword flag to indicate that the model input check routines should not be called prior to each time step. checks are performed by default."
optional = true

[blocks.options.fields.memory_print_option]
name = "memory_print_option"
longname = "memory print option"
description = "is a flag that controls printing of detailed memory manager usage to the end of the simulation list file.  none means do not print detailed information. summary means print only the total memory for each simulation component. all means print information for each variable stored in the memory manager. none is default if memory_print_option is not specified."
optional = true
tagged = false

[blocks.options.fields.profile_option]
name = "profile_option"
longname = "profiling option"
description = "is a flag that controls performance profiling and reporting.  none disables profiling. summary means to measure and print a coarse performance profile. detail means collect and print information with the highest resolution available. none is default if profile_option is not specified."
optional = true
tagged = false

[blocks.options.fields.maxerrors]
name = "maxerrors"
longname = "maximum number of errors"
description = "maximum number of errors that will be stored and printed."
optional = true
tagged = false

[blocks.options.fields.print_input]
name = "print_input"
longname = "print input to listing file"
description = "keyword to activate printing of simulation input summaries to the simulation list file (mfsim.lst). with this keyword, input summaries will be written for those packages that support newer input data model routines.  not all packages are supported yet by the newer input data model routines."
optional = true

[blocks.options.fields.hpc_filerecord]
name = "hpc_filerecord"
description = "hpc record"
optional = true

[blocks.options.fields.hpc_filerecord.fields.hpc6]
name = "hpc6"
longname = "head keyword"
description = "keyword to specify that record corresponds to a hpc file."

[blocks.options.fields.hpc_filerecord.fields.filein]
name = "filein"
longname = "file keyword"
description = "keyword to specify that an input filename is expected next."

[blocks.options.fields.hpc_filerecord.fields.hpc6_filename]
name = "hpc6_filename"
longname = "file name of time series information"
description = "name of input file to define hpc file settings for the hpc package. see the 'hpc file' section for instructions for preparing hpc input files."
tagged = false
case_sensitive = true

[blocks.timing]
name = "timing"

[blocks.timing.fields.tdis6]
name = "tdis6"
longname = "name of tdis input file"
description = "is the name of the temporal discretization (tdis) input file."
tagged = false
case_sensitive = true

[blocks.models]
name = "models"

[blocks.models.fields.models]
name = "models"
longname = "list of models"
description = "is the list of model types, model name files, and model names."

[blocks.models.fields.models.item]
name = "models"
description = "is the record of model types, model name files, and model names."

[blocks.models.fields.models.item.fields.mtype]
name = "mtype"
longname = "model type"
description = "is the type of model to add to simulation."
tagged = false

[blocks.models.fields.models.item.fields.mfname]
name = "mfname"
longname = "file name for model name file"
description = "is the file name of the model name file."
tagged = false
case_sensitive = true

[blocks.models.fields.models.item.fields.mname]
name = "mname"
longname = "name of model"
description = "is the user-assigned name of the model.  the model name cannot exceed 16 characters and must not have blanks within the name.  the model name is case insensitive; any lowercase letters are converted and stored as upper case letters."
tagged = false

[blocks.exchanges]
name = "exchanges"

[blocks.exchanges.fields.exchanges]
name = "exchanges"
longname = "list of exchanges"
description = "is the list of exchange types, exchange files, and model names."

[blocks.exchanges.fields.exchanges.item]
name = "exchanges"
description = "is the record of exchange types, exchange files, and model names."

[blocks.exchanges.fields.exchanges.item.fields.exgtype]
name = "exgtype"
longname = "exchange type"
description = "is the exchange type."
tagged = false

[blocks.exchanges.fields.exchanges.item.fields.exgfile]
name = "exgfile"
longname = "input file for exchange"
description = "is the input file for the exchange."
tagged = false
case_sensitive = true

[blocks.exchanges.fields.exchanges.item.fields.exgmnamea]
name = "exgmnamea"
longname = "name of model a"
description = "is the name of the first model that is part of this exchange."
tagged = false

[blocks.exchanges.fields.exchanges.item.fields.exgmnameb]
name = "exgmnameb"
longname = "name of model b"
description = "is the name of the second model that is part of this exchange."
tagged = false

[blocks.solutiongroup]
name = "solutiongroup"

[blocks.solutiongroup.fields.mxiter]
name = "mxiter"
longname = "maximum solution group iterations"
description = "is the maximum number of outer iterations for this solution group.  the default value is 1.  if there is only one solution in the solution group, then mxiter must be 1."
optional = true
tagged = false

[blocks.solutiongroup.fields.solutiongroup]
name = "solutiongroup"
longname = "solution type and models in the solution"
description = "is the list of solution types and models in the solution."

[blocks.solutiongroup.fields.solutiongroup.item]
name = "solutiongroup"
description = "is the record of solution types and models in the solution."

[blocks.solutiongroup.fields.solutiongroup.item.fields.slntype]
name = "slntype"
longname = "type of solution"
description = "is the type of solution.  the integrated model solution (ims6) and explicit model solution (ems6) are the only supported options in this version."
tagged = false
valid = [
    "i",
    "m",
    "s",
    "6",
    " ",
    "e",
    "m",
    "s",
    "6",
]

[blocks.solutiongroup.fields.solutiongroup.item.fields.slnfname]
name = "slnfname"
longname = "file name for solution input"
description = "name of file containing solution input."
tagged = false
case_sensitive = true

[blocks.solutiongroup.fields.solutiongroup.item.fields.slnmnames]
name = "slnmnames"
longname = "array of model names in this solution"
description = "is the array of model names to add to this solution.  the number of model names is determined by the number of model names the user provides on this line."
dtype = "string"
