name = "sim-tdis"
schema_version = "2"
subtype = "stress"

[blocks.options]
name = "options"

[blocks.options.fields.time_units]
name = "time_units"
longname = "time unit"
description = "is the time units of the simulation.  this is a text string that is used as a label within model output files.  values for time_units may be 'unknown',  'seconds', 'minutes', 'hours', 'days', or 'years'.  the default time unit is 'unknown'."
optional = true
tagged = false

[blocks.options.fields.start_date_time]
name = "start_date_time"
longname = "starting date and time"
description = "is the starting date and time of the simulation.  this is a text string that is used as a label within the simulation list file.  the value has no effect on the simulation.  the recommended format for the starting date and time is described at https://www.w3.org/tr/note-datetime."
optional = true
tagged = false

[blocks.options.fields.ats_filerecord]
name = "ats_filerecord"
optional = true

[blocks.options.fields.ats_filerecord.fields.ats6]
name = "ats6"
longname = "ats keyword"
description = "keyword to specify that record corresponds to an adaptive time step (ats) input file.  the behavior of ats and a description of the input file is provided separately."

[blocks.options.fields.ats_filerecord.fields.filein]
name = "filein"
longname = "file keyword"
description = "keyword to specify that an input filename is expected next."

[blocks.options.fields.ats_filerecord.fields.ats6_filename]
name = "ats6_filename"
longname = "file name of adaptive time series information"
description = "defines an adaptive time step (ats) input file defining ats controls.  records in the ats file can be used to override the time step behavior for selected stress periods."
tagged = false
case_sensitive = true

[blocks.dimensions]
name = "dimensions"

[blocks.dimensions.fields.nper]
name = "nper"
longname = "number of stress periods"
description = "is the number of stress periods for the simulation."
tagged = false

[blocks.perioddata]
name = "perioddata"

[blocks.perioddata.fields.perioddata]
name = "perioddata"
longname = "stress period time information"

[blocks.perioddata.fields.perioddata.item]
name = "perioddata"

[blocks.perioddata.fields.perioddata.item.fields.perlen]
name = "perlen"
longname = "length of stress period"
description = "is the length of a stress period."
tagged = false

[blocks.perioddata.fields.perioddata.item.fields.nstp]
name = "nstp"
longname = "number of time steps"
description = "is the number of time steps in a stress period."
tagged = false

[blocks.perioddata.fields.perioddata.item.fields.tsmult]
name = "tsmult"
longname = "number of time steps"
description = "is the multiplier for the length of successive time steps. the length of a time step is calculated by multiplying the length of the previous time step by tsmult. the length of the first time step, $delta t_1$, is related to perlen, nstp, and tsmult by the relation $delta t_1= perlen frac{tsmult - 1}{tsmult^{nstp}-1}$."
tagged = false

[dims.nper]
field = "nper"
scope = "simulation"
