name = "swf-ic"
schema_version = "2"

[blocks.options]
name = "options"

[blocks.options.fields.export_array_ascii]
name = "export_array_ascii"
longname = "export array variables to layered ascii files."
description = "keyword that specifies input griddata arrays should be written to layered ascii output files."
optional = true

[blocks.griddata]
name = "griddata"

[blocks.griddata.fields.strt]
name = "strt"
longname = "starting concentration"
description = "is the initial (starting) stage---that is, stage at the beginning of the swf model simulation.  strt must be specified for all swf model simulations. one value is read for every model reach."
dtype = "double"
shape = [
    "nodes",
]
