name = "swf-dfw"
schema_version = "2"

[blocks.options]
name = "options"

[blocks.options.fields.central_in_space]
name = "central_in_space"
longname = "use central in space weighting"
description = "keyword to indicate conductance should be calculated using central-in-space weighting instead of the default upstream weighting approach.  this option should be used with caution as it does not work well unless all of the stream reaches are saturated.  with this option, there is no way for water to flow into a dry reach from connected reaches."
optional = true

[blocks.options.fields.length_conversion]
name = "length_conversion"
longname = "length conversion factor"
description = "real value that is used to convert user-specified manning's roughness coefficients from meters to model length units. length_conversion should be set to 3.28081, 1.0, and 100.0 when using length units (length_units) of feet, meters, or centimeters in the simulation, respectively. length_conversion does not need to be specified if length_units are meters."
optional = true
tagged = false

[blocks.options.fields.time_conversion]
name = "time_conversion"
longname = "time conversion factor"
description = "real value that is used to convert user-specified manning's roughness coefficients from seconds to model time units. time_conversion should be set to 1.0, 60.0, 3,600.0, 86,400.0, and 31,557,600.0 when using time units (time_units) of seconds, minutes, hours, days, or years in the simulation, respectively. time_conversion does not need to be specified if time_units are seconds."
optional = true
tagged = false

[blocks.options.fields.save_flows]
name = "save_flows"
longname = "keyword to save dfw flows"
description = "keyword to indicate that budget flow terms will be written to the file specified with 'budget save file' in output control."
optional = true

[blocks.options.fields.print_flows]
name = "print_flows"
longname = "keyword to print dfw flows to listing file"
description = "keyword to indicate that calculated flows between cells will be printed to the listing file for every stress period time step in which 'budget print' is specified in output control. if there is no output control option and 'print_flows' is specified, then flow rates are printed for the last time step of each stress period.  this option can produce extremely large list files because all cell-by-cell flows are printed.  it should only be used with the dfw package for models that have a small number of cells."
optional = true

[blocks.options.fields.save_velocity]
name = "save_velocity"
longname = "keyword to save velocity"
description = "keyword to indicate that x, y, and z components of velocity will be calculated at cell centers and written to the budget file, which is specified with 'budget save file' in output control.  if this option is activated, then additional information may be required in the discretization packages and the gwf exchange package (if gwf models are coupled).  specifically, angldegx must be specified in the connectiondata block of the disu package; angldegx must also be specified for the gwf exchange as an auxiliary variable."
optional = true

[blocks.options.fields.obs_filerecord]
name = "obs_filerecord"
optional = true

[blocks.options.fields.obs_filerecord.fields.obs6]
name = "obs6"
longname = "obs keyword"
description = "keyword to specify that record corresponds to an observations file."

[blocks.options.fields.obs_filerecord.fields.filein]
name = "filein"
longname = "file keyword"
description = "keyword to specify that an input filename is expected next."

[blocks.options.fields.obs_filerecord.fields.obs6_filename]
name = "obs6_filename"
longname = "obs6 input filename"
description = "name of input file to define observations for the dfw package. see the 'observation utility' section for instructions for preparing observation input files. table {#2} lists observation type(s) supported by the dfw package."
tagged = false
case_sensitive = true

[blocks.options.fields.export_array_ascii]
name = "export_array_ascii"
longname = "export array variables to layered ascii files."
description = "keyword that specifies input griddata arrays should be written to layered ascii output files."
optional = true

[blocks.options.fields.dev_swr_conductance]
name = "dev_swr_conductance"
longname = "use swr conductance formulation"
description = "use the conductance formulation in the surface water routing (swr) process for modflow-2005."
optional = true

[blocks.griddata]
name = "griddata"

[blocks.griddata.fields.manningsn]
name = "manningsn"
longname = "mannings roughness coefficient"
description = "mannings roughness coefficient"
dtype = "double"
shape = [
    "nodes",
]

[blocks.griddata.fields.idcxs]
name = "idcxs"
longname = "cross section number"
description = "integer value indication the cross section identifier in the cross section package that applies to the reach.  if not provided then reach will be treated as hydraulically wide."
optional = true
dtype = "integer"
shape = [
    "nodes",
]
