name = "utl-spca"
schema_version = "2"
multi = true
subtype = "utility"

[blocks.options]
name = "options"

[blocks.options.fields.readasarrays]
name = "readasarrays"
longname = "use array-based input"
description = "indicates that array-based input will be used for the spc package.  this keyword must be specified to use array-based input.  when readasarrays is specified, values must be provided for every cell within a model layer, even those cells that have an idomain value less than one.  values assigned to cells with idomain values less than one are not used and have no effect on simulation results."

[blocks.options.fields.print_input]
name = "print_input"
longname = "print input to listing file"
description = "keyword to indicate that the list of spc information will be written to the listing file immediately after it is read."
optional = true

[blocks.options.fields.tas_filerecord]
name = "tas_filerecord"
optional = true

[blocks.options.fields.tas_filerecord.fields.tas6]
name = "tas6"
longname = "head keyword"
description = "keyword to specify that record corresponds to a time-array-series file."

[blocks.options.fields.tas_filerecord.fields.filein]
name = "filein"
longname = "file keyword"
description = "keyword to specify that an input filename is expected next."

[blocks.options.fields.tas_filerecord.fields.tas6_filename]
name = "tas6_filename"
longname = "file name of time series information"
description = "defines a time-array-series file defining a time-array series that can be used to assign time-varying values. see the time-variable input section for instructions on using the time-array series capability."
tagged = false
case_sensitive = true

[blocks.period]
name = "period"

[blocks.period.fields.concentration]
name = "concentration"
longname = "concentration"
description = "is the concentration of the associated recharge or evapotranspiration stress package.  the concentration array may be defined by a time-array series (see the \"using time-array series in a package\" section)."
optional = true
dtype = "double"
shape = [
    "ncpl",
]
time_series = true

[blocks.period.fields.temperature]
name = "temperature"
longname = "temperature"
description = "is the temperature of the associated recharge or evapotranspiration stress package.  the temperature array may be defined by a time-array series (see the \"using time-array series in a package\" section)."
optional = true
dtype = "double"
shape = [
    "ncpl",
]
time_series = true
