name = "utl-tas"
parent = "package"
schema_version = "2"
multi = true
subtype = "utility"

[blocks.attributes]
name = "attributes"

[blocks.attributes.fields.time_series_namerecord]
name = "time_series_namerecord"
description = "xxx"

[blocks.attributes.fields.time_series_namerecord.fields.name]
name = "name"
description = "xxx"

[blocks.attributes.fields.time_series_namerecord.fields.time_series_name]
name = "time_series_name"
description = "name by which a package references a particular time-array series. the name must be unique among all time-array series used in a package."
dtype = "string"

[blocks.attributes.fields.interpolation_methodrecord]
name = "interpolation_methodrecord"
description = "xxx"
optional = true

[blocks.attributes.fields.interpolation_methodrecord.fields.method]
name = "method"
description = " xxx"

[blocks.attributes.fields.interpolation_methodrecord.fields.interpolation_method]
name = "interpolation_method"
description = "interpolation method, which is either stepwise or linear."
tagged = false
valid = [
    "s",
    "t",
    "e",
    "p",
    "w",
    "i",
    "s",
    "e",
    " ",
    "l",
    "i",
    "n",
    "e",
    "a",
    "r",
    " ",
    "l",
    "i",
    "n",
    "e",
    "a",
    "r",
    "e",
    "n",
    "d",
]

[blocks.attributes.fields.sfacrecord]
name = "sfacrecord"
description = "xxx"
optional = true

[blocks.attributes.fields.sfacrecord.fields.sfac]
name = "sfac"
description = " xxx"

[blocks.attributes.fields.sfacrecord.fields.sfacval]
name = "sfacval"
description = "scale factor, which will multiply all array values in time series. sfac is an optional attribute; if omitted, sfac = 1.0."
dtype = "double"
shape = [
    "time_series_name",
]

[blocks.time]
name = "time"

[blocks.time.fields.tas_array]
name = "tas_array"
description = "an array of numeric, floating-point values, or a constant value, readable by the u2drel array-reading utility."
dtype = "double"

[dims.time_series_name]
field = "time_series_name"
scope = "component"
