name = "utl-laktab"
schema_version = "2"
multi = true
subtype = "utility"

[blocks.dimensions]
name = "dimensions"

[blocks.dimensions.fields.nrow]
name = "nrow"
longname = "number of table rows"
description = "integer value specifying the number of rows in the lake table. there must be nrow rows of data in the table block."
tagged = false

[blocks.dimensions.fields.ncol]
name = "ncol"
longname = "number of table columns"
description = "integer value specifying the number of columns in the lake table. there must be ncol columns of data in the table block. for lakes with horizontal and/or vertical ctype connections, ncol must be equal to 3. for lakes with embeddedh or embeddedv ctype connections, ncol must be equal to 4."
tagged = false

[blocks.table]
name = "table"

[blocks.table.fields.table]
name = "table"

[blocks.table.fields.table.item]
name = "table"

[blocks.table.fields.table.item.fields.stage]
name = "stage"
longname = "lake stage"
description = "real value that defines the stage corresponding to the remaining data on the line."
tagged = false

[blocks.table.fields.table.item.fields.volume]
name = "volume"
longname = "lake volume"
description = "real value that defines the lake volume corresponding to the stage specified on the line."
tagged = false

[blocks.table.fields.table.item.fields.sarea]
name = "sarea"
longname = "lake surface area"
description = "real value that defines the lake surface area corresponding to the stage specified on the line."
tagged = false

[blocks.table.fields.table.item.fields.barea]
name = "barea"
longname = "lake-gwf exchange area"
description = "real value that defines the lake-gwf exchange area corresponding to the stage specified on the line. barea is only specified if the claktype for the lake is embeddedh or embeddedv."
optional = true
tagged = false

[dims.nrow]
field = "nrow"
scope = "component"

[dims.ncol]
field = "ncol"
scope = "component"
