type = "package"
schema_version = "2.0.0.dev2"
name = "gwf-oc"
parent = "gwf-nam"

[blocks.options.fields.budget_filerecord]
type = "record"
optional = true

[blocks.options.fields.budget_filerecord.fields.budget]
type = "keyword"
longname = "budget keyword"
description = "keyword to specify that record corresponds to the budget."

[blocks.options.fields.budget_filerecord.fields.budgetfile]
type = "file"
longname = "file keyword"
description = "name of the output file to write budget information."
tagged = false
direction = "out"

[blocks.options.fields.budgetcsv_filerecord]
type = "record"
optional = true

[blocks.options.fields.budgetcsv_filerecord.fields.budgetcsv]
type = "keyword"
longname = "budget keyword"
description = "keyword to specify that record corresponds to the budget CSV."

[blocks.options.fields.budgetcsv_filerecord.fields.budgetcsvfile]
type = "file"
longname = "file keyword"
description = "name of the comma-separated value (CSV) output file to write budget summary information.  A budget summary record will be written to this file for each time step of the simulation."
tagged = false
direction = "out"

[blocks.options.fields.head_filerecord]
type = "record"
optional = true

[blocks.options.fields.head_filerecord.fields.head]
type = "keyword"
longname = "head keyword"
description = "keyword to specify that record corresponds to head."

[blocks.options.fields.head_filerecord.fields.headfile]
type = "file"
longname = "file keyword"
description = "name of the output file to write head information."
tagged = false
direction = "out"

[blocks.options.fields.headprintrecord]
type = "record"
optional = true

[blocks.options.fields.headprintrecord.fields.head]
type = "keyword"
longname = "head keyword"
description = "keyword to specify that record corresponds to head."

[blocks.options.fields.headprintrecord.fields.print_format]
type = "keyword"
longname = "keyword to indicate that a print format follows"
description = "keyword to specify format for printing to the listing file."

[blocks.options.fields.headprintrecord.fields.formatrecord]
type = "record"

[blocks.options.fields.headprintrecord.fields.formatrecord.fields.columns]
type = "integer"
longname = "number of columns"
description = "number of columns for writing data."

[blocks.options.fields.headprintrecord.fields.formatrecord.fields.width]
type = "integer"
longname = "width for each number"
description = "width for writing each number."

[blocks.options.fields.headprintrecord.fields.formatrecord.fields.digits]
type = "integer"
longname = "number of digits"
description = "number of digits to use for writing a number."

[blocks.options.fields.headprintrecord.fields.formatrecord.fields.format]
type = "string"
longname = "write format"
description = "write format can be EXPONENTIAL, FIXED, GENERAL, or SCIENTIFIC."
tagged = false

[blocks.period.fields.output]
type = "list"
optional = true

[blocks.period.fields.output.item]
type = "union"

[blocks.period.fields.output.item.arms.saverecord]
type = "record"
optional = true

[blocks.period.fields.output.item.arms.saverecord.fields.save]
type = "keyword"
longname = "keyword to save"
description = "keyword to indicate that information will be saved this stress period."

[blocks.period.fields.output.item.arms.saverecord.fields.rtype]
type = "string"
longname = "record type"
description = "type of information to save or print.  Can be BUDGET or HEAD."
tagged = false
valid = [
    "HEAD",
    "BUDGET",
]

[blocks.period.fields.output.item.arms.saverecord.fields.ocsetting]
type = "union"
description = "specifies the steps for which the data will be saved."

[blocks.period.fields.output.item.arms.saverecord.fields.ocsetting.arms.all]
type = "keyword"
description = "keyword to indicate save for all time steps in period."

[blocks.period.fields.output.item.arms.saverecord.fields.ocsetting.arms.first]
type = "keyword"
description = "keyword to indicate save for first step in period. This keyword may be used in conjunction with other keywords to print or save results for multiple time steps."

[blocks.period.fields.output.item.arms.saverecord.fields.ocsetting.arms.last]
type = "keyword"
description = "keyword to indicate save for last step in period. This keyword may be used in conjunction with other keywords to print or save results for multiple time steps."

[blocks.period.fields.output.item.arms.saverecord.fields.ocsetting.arms.frequency]
type = "integer"
description = "save at the specified time step frequency. This keyword may be used in conjunction with other keywords to print or save results for multiple time steps."

[blocks.period.fields.output.item.arms.saverecord.fields.ocsetting.arms.steps]
type = "array"
description = "save for each step specified in STEPS. This keyword may be used in conjunction with other keywords to print or save results for multiple time steps."
dtype = "integer"

[blocks.period.fields.output.item.arms.printrecord]
type = "record"
optional = true

[blocks.period.fields.output.item.arms.printrecord.fields.print]
type = "keyword"
longname = "keyword to save"
description = "keyword to indicate that information will be printed this stress period."

[blocks.period.fields.output.item.arms.printrecord.fields.rtype]
type = "string"
longname = "record type"
description = "type of information to save or print.  Can be BUDGET or HEAD."
tagged = false
valid = [
    "HEAD",
    "BUDGET",
]

[blocks.period.fields.output.item.arms.printrecord.fields.ocsetting]
type = "union"
description = "specifies the steps for which the data will be saved."

[blocks.period.fields.output.item.arms.printrecord.fields.ocsetting.arms.all]
type = "keyword"
description = "keyword to indicate save for all time steps in period."

[blocks.period.fields.output.item.arms.printrecord.fields.ocsetting.arms.first]
type = "keyword"
description = "keyword to indicate save for first step in period. This keyword may be used in conjunction with other keywords to print or save results for multiple time steps."

[blocks.period.fields.output.item.arms.printrecord.fields.ocsetting.arms.last]
type = "keyword"
description = "keyword to indicate save for last step in period. This keyword may be used in conjunction with other keywords to print or save results for multiple time steps."

[blocks.period.fields.output.item.arms.printrecord.fields.ocsetting.arms.frequency]
type = "integer"
description = "save at the specified time step frequency. This keyword may be used in conjunction with other keywords to print or save results for multiple time steps."

[blocks.period.fields.output.item.arms.printrecord.fields.ocsetting.arms.steps]
type = "array"
description = "save for each step specified in STEPS. This keyword may be used in conjunction with other keywords to print or save results for multiple time steps."
dtype = "integer"

[blocks.period.header]
name = "iper"
type = "integer"
longname = "stress period number"
description = "integer value specifying the starting stress period number for which the data specified in the PERIOD block apply.  IPER must be less than or equal to NPER in the TDIS Package and greater than zero.  The IPER value assigned to a stress period block must be greater than the IPER value assigned for the previous PERIOD block.  The information specified in the PERIOD block will continue to apply for all subsequent stress periods, unless the program encounters another PERIOD block."
tagged = false
