name = "gwf-vsc"
advanced = false
multi = false
schema_version = "2.0.0.dev0"

[options.viscref]
block = "options"
type = "double precision"
default = 1.0
reader = "urword"
optional = true
longname = "reference viscosity"
description = "fluid reference viscosity used in the equation of state.  This value is set to 1.0 if not specified as an option."

[options.temperature_species_name]
block = "options"
type = "string"
reader = "urword"
optional = true
longname = "auxspeciesname that corresponds to temperature"
description = "string used to identify the auxspeciesname in PACKAGEDATA that corresponds to the temperature species.  There can be only one occurrence of this temperature species name in the PACKAGEDATA block or the program will terminate with an error.  This value has no effect if viscosity does not depend on temperature."
mf6internal = "temp_specname"

[options.thermal_formulation]
block = "options"
type = "string"
reader = "urword"
optional = true
longname = "keyword to specify viscosity formulation for the temperature species"
description = "may be used for specifying which viscosity formulation to use for the temperature species. Can be either LINEAR or NONLINEAR. The LINEAR viscosity formulation is the default."
valid = "linear nonlinear"
mf6internal = "thermal_form"

[options.thermal_a2]
block = "options"
type = "double precision"
default = 10.0
reader = "urword"
optional = true
longname = "coefficient used in nonlinear viscosity function"
description = "is an empirical parameter specified by the user for calculating viscosity using a nonlinear formulation.  If A2 is not specified, a default value of 10.0 is assigned (Voss, 1984)."

[options.thermal_a3]
block = "options"
type = "double precision"
default = 248.37
reader = "urword"
optional = true
longname = "coefficient used in nonlinear viscosity function"
description = "is an empirical parameter specified by the user for calculating viscosity using a nonlinear formulation.  If A3 is not specified, a default value of 248.37 is assigned (Voss, 1984)."

[options.thermal_a4]
block = "options"
type = "double precision"
default = 133.15
reader = "urword"
optional = true
longname = "coefficient used in nonlinear viscosity function"
description = "is an empirical parameter specified by the user for calculating viscosity using a nonlinear formulation.  If A4 is not specified, a default value of 133.15 is assigned (Voss, 1984)."

[options.viscosity_filerecord]
block = "options"
type = "record"
reader = "urword"
optional = true
tagged = true
mf6internal = "viscosity_fr"

[options.viscosity_filerecord.fields.viscosity]
block = "options"
type = "keyword"
reader = "urword"
optional = false
longname = "viscosity keyword"
description = "keyword to specify that record corresponds to viscosity."
in_record = true
tagged = true

[options.viscosity_filerecord.fields.fileout]
block = "options"
type = "keyword"
reader = "urword"
optional = false
longname = "file keyword"
description = "keyword to specify that an output filename is expected next."
in_record = true
tagged = true

[options.viscosity_filerecord.fields.viscosityfile]
block = "options"
type = "string"
reader = "urword"
optional = false
longname = "file keyword"
description = "name of the binary output file to write viscosity information.  The viscosity file has the same format as the head file.  Viscosity values will be written to the viscosity file whenever heads are written to the binary head file.  The settings for controlling head output are contained in the Output Control option."
preserve_case = true
in_record = true
tagged = false

[dimensions.nviscspecies]
block = "dimensions"
type = "integer"
reader = "urword"
optional = false
longname = "number of species used in viscosity equation of state"
description = "number of species used in the viscosity equation of state.  If either concentrations or temperature (or both) are used to update viscosity then nviscspecies needs to be at least one."

[packagedata.packagedata]
block = "packagedata"
type = "recarray"
shape = "(nviscspecies)"
reader = "urword"

[packagedata.packagedata.item]
type = "record"
block = "packagedata"
reader = "urword"

[packagedata.packagedata.item.fields.iviscspec]
block = "packagedata"
type = "integer"
reader = "urword"
longname = "species number for this entry"
description = "integer value that defines the species number associated with the specified PACKAGEDATA data entered on each line. IVISCSPECIES must be greater than zero and less than or equal to NVISCSPECIES. Information must be specified for each of the NVISCSPECIES species or the program will terminate with an error.  The program will also terminate with an error if information for a species is specified more than once."
tagged = false
in_record = true
numeric_index = true

[packagedata.packagedata.item.fields.dviscdc]
block = "packagedata"
type = "double precision"
reader = "urword"
longname = "slope of the line that defines the linear relationship between viscosity and temperature or between viscosity and concentration, depending on the type of species entered on each line."
description = "real value that defines the slope of the line defining the linear relationship between viscosity and temperature or between viscosity and concentration, depending on the type of species entered on each line.  If the value of AUXSPECIESNAME entered on a line corresponds to TEMPERATURE_SPECIES_NAME (in the OPTIONS block), this value will be used when VISCOSITY_FUNC is equal to LINEAR (the default) in the OPTIONS block.  When VISCOSITY_FUNC is set to NONLINEAR, a value for DVISCDC must be specified though it is not used."
tagged = false
in_record = true

[packagedata.packagedata.item.fields.cviscref]
block = "packagedata"
type = "double precision"
reader = "urword"
longname = "reference temperature value or reference concentration value"
description = "real value that defines the reference temperature or reference concentration value used for this species in the viscosity equation of state.  If AUXSPECIESNAME entered on a line corresponds to TEMPERATURE_SPECIES_NAME (in the OPTIONS block), then CVISCREF refers to a reference temperature, otherwise it refers to a reference concentration."
tagged = false
in_record = true

[packagedata.packagedata.item.fields.modelname]
block = "packagedata"
type = "string"
reader = "urword"
longname = "modelname"
description = "name of a GWT or GWE model used to simulate a species that will be used in the viscosity equation of state.  This name will have no effect if the simulation does not include a GWT or GWE model that corresponds to this GWF model."
in_record = true
tagged = false

[packagedata.packagedata.item.fields.auxspeciesname]
block = "packagedata"
type = "string"
reader = "urword"
longname = "auxspeciesname"
description = "name of an auxiliary variable in a GWF stress package that will be used for this species to calculate the viscosity values.  If a viscosity value is needed by the Viscosity Package then it will use the temperature or concentration values associated with this AUXSPECIESNAME in the viscosity equation of state.  For advanced stress packages (LAK, SFR, MAW, and UZF) that have an associated advanced transport package (LKT, SFT, MWT, and UZT), the FLOW_PACKAGE_AUXILIARY_NAME option in the advanced transport package can be used to transfer simulated temperature or concentration(s) into the flow package auxiliary variable.  In this manner, the Viscosity Package can calculate viscosity values for lakes, streams, multi-aquifer wells, and unsaturated zone flow cells using simulated concentrations."
in_record = true
tagged = false
