name = "gwt-fmi"
advanced = false
multi = false
schema_version = "2.0.0.dev0"

[options.save_flows]
block = "options"
type = "keyword"
reader = "urword"
optional = true
longname = "save calculated flow imbalance correction to budget file"
description = "keyword to indicate that FMI flow terms will be written to the file specified with 'BUDGET FILEOUT' in Output Control."

[options.flow_imbalance_correction]
block = "options"
type = "keyword"
reader = "urword"
optional = true
longname = "correct for flow imbalance"
description = "correct for an imbalance in flows by assuming that any residual flow error comes in or leaves at the concentration of the cell.  When this option is activated, the GWT Model budget written to the listing file will contain two additional entries: FLOW-ERROR and FLOW-CORRECTION.  These two entries will be equal but opposite in sign.  The FLOW-CORRECTION term is a mass flow that is added to offset the error caused by an imprecise flow balance.  If these terms are not relatively small, the flow model should be rerun with stricter convergence tolerances."
mf6internal = "imbalancecorrect"

[packagedata.packagedata]
block = "packagedata"
type = "recarray"
reader = "urword"
optional = true
longname = "flowtype list"

[packagedata.packagedata.item]
type = "record"
block = "packagedata"
reader = "urword"
optional = true
longname = "flowtype list"

[packagedata.packagedata.item.fields.flowtype]
block = "packagedata"
type = "string"
reader = "urword"
longname = "flow type"
description = "is the word GWFBUDGET, GWFHEAD, GWFMOVER or the name of an advanced GWF stress package.  If GWFBUDGET is specified, then the corresponding file must be a budget file. If GWFHEAD is specified, the file must be a head file.  If GWFGRID is specified, the file must be a binary grid file.  If an advanced GWF stress package name appears then the corresponding file must be the budget file saved by a LAK, SFR, MAW or UZF Package."
in_record = true
tagged = false

[packagedata.packagedata.item.fields.filein]
block = "packagedata"
type = "keyword"
reader = "urword"
optional = false
longname = "file keyword"
description = "keyword to specify that an input filename is expected next."
in_record = true
tagged = true

[packagedata.packagedata.item.fields.fname]
block = "packagedata"
type = "string"
reader = "urword"
longname = "file name"
description = "is the name of the file containing flows.  The path to the file should be included if the file is not located in the folder where the program was run."
in_record = true
preserve_case = true
tagged = false
