name = "olf-dfw"
advanced = false
multi = false
schema_version = "2.0.0.dev0"

[fkeys.obs_filerecord]
parent = "parent_model_or_package"
key = "obs_filerecord"
val = "observations"
abbr = "obs"
param = "continuous"

[options.central_in_space]
block = "options"
type = "keyword"
reader = "urword"
optional = true
longname = "use central in space weighting"
description = "keyword to indicate conductance should be calculated using central-in-space weighting instead of the default upstream weighting approach.  This option should be used with caution as it does not work well unless all of the stream reaches are saturated.  With this option, there is no way for water to flow into a dry reach from connected reaches."
mf6internal = "icentral"

[options.length_conversion]
block = "options"
type = "double precision"
reader = "urword"
optional = true
longname = "length conversion factor"
description = "real value that is used to convert user-specified Manning's roughness coefficients from meters to model length units. LENGTH_CONVERSION should be set to 3.28081, 1.0, and 100.0 when using length units (LENGTH_UNITS) of feet, meters, or centimeters in the simulation, respectively. LENGTH_CONVERSION does not need to be specified if LENGTH_UNITS are meters."
mf6internal = "lengthconv"

[options.time_conversion]
block = "options"
type = "double precision"
reader = "urword"
optional = true
longname = "time conversion factor"
description = "real value that is used to convert user-specified Manning's roughness coefficients from seconds to model time units. TIME_CONVERSION should be set to 1.0, 60.0, 3,600.0, 86,400.0, and 31,557,600.0 when using time units (TIME_UNITS) of seconds, minutes, hours, days, or years in the simulation, respectively. TIME_CONVERSION does not need to be specified if TIME_UNITS are seconds."
mf6internal = "timeconv"

[options.save_flows]
block = "options"
type = "keyword"
reader = "urword"
optional = true
longname = "keyword to save DFW flows"
description = "keyword to indicate that budget flow terms will be written to the file specified with 'BUDGET SAVE FILE' in Output Control."
mf6internal = "ipakcb"

[options.print_flows]
block = "options"
type = "keyword"
reader = "urword"
optional = true
longname = "keyword to print DFW flows to listing file"
description = "keyword to indicate that calculated flows between cells will be printed to the listing file for every stress period time step in which 'BUDGET PRINT' is specified in Output Control. If there is no Output Control option and 'PRINT_FLOWS' is specified, then flow rates are printed for the last time step of each stress period.  This option can produce extremely large list files because all cell-by-cell flows are printed.  It should only be used with the DFW Package for models that have a small number of cells."
mf6internal = "iprflow"

[options.save_velocity]
block = "options"
type = "keyword"
reader = "urword"
optional = true
longname = "keyword to save velocity"
description = "keyword to indicate that x, y, and z components of velocity will be calculated at cell centers and written to the budget file, which is specified with 'BUDGET SAVE FILE' in Output Control.  If this option is activated, then additional information may be required in the discretization packages and the GWF Exchange package (if GWF models are coupled).  Specifically, ANGLDEGX must be specified in the CONNECTIONDATA block of the DISU Package; ANGLDEGX must also be specified for the GWF Exchange as an auxiliary variable."
mf6internal = "isavvelocity"

[options.observations]
block = "options"
type = "record obs6 filein obs6_filename"
reader = "urword"
optional = true
description = "Contains data for the obs package. Data can be passed as a dictionary to the obs package with variable names as keys and package data as values. Data for the observations variable is also acceptable. See obs package documentation for more information."
tagged = true

[options.observations.ref]
parent = "parent_model_or_package"
key = "obs_filerecord"
val = "observations"
abbr = "obs"
param = "continuous"

[options.export_array_ascii]
block = "options"
type = "keyword"
reader = "urword"
optional = true
longname = "export array variables to layered ascii files."
description = "keyword that specifies input griddata arrays should be written to layered ascii output files."
mf6internal = "export_ascii"

[options.dev_swr_conductance]
block = "options"
type = "keyword"
reader = "urword"
optional = true
longname = "use SWR conductance formulation"
description = "use the conductance formulation in the Surface Water Routing (SWR) Process for MODFLOW-2005."
mf6internal = "iswrcond"

[griddata.manningsn]
block = "griddata"
type = "double precision"
shape = "(nodes)"
reader = "readarray"
longname = "mannings roughness coefficient"
description = "mannings roughness coefficient"
layered = false

[griddata.idcxs]
block = "griddata"
type = "integer"
shape = "(nodes)"
reader = "readarray"
optional = true
longname = "cross section number"
description = "integer value indication the cross section identifier in the Cross Section Package that applies to the reach.  If not provided then reach will be treated as hydraulically wide."
layered = false
numeric_index = true
