name = "olf-nam"
advanced = false
multi = false
schema_version = "2.0.0.dev0"

[options.list]
block = "options"
type = "string"
reader = "urword"
optional = true
longname = "name of listing file"
description = "is name of the listing file to create for this OLF model.  If not specified, then the name of the list file will be the basename of the OLF model name file and the '.lst' extension.  For example, if the OLF name file is called 'my.model.nam' then the list file will be called 'my.model.lst'."
preserve_case = true

[options.print_input]
block = "options"
type = "keyword"
reader = "urword"
optional = true
longname = "print input to listing file"
description = "keyword to indicate that the list of all model stress package information will be written to the listing file immediately after it is read."

[options.print_flows]
block = "options"
type = "keyword"
reader = "urword"
optional = true
longname = "print calculated flows to listing file"
description = "keyword to indicate that the list of all model package flow rates will be printed to the listing file for every stress period time step in which 'BUDGET PRINT' is specified in Output Control.  If there is no Output Control option and 'PRINT_FLOWS' is specified, then flow rates are printed for the last time step of each stress period."

[options.save_flows]
block = "options"
type = "keyword"
reader = "urword"
optional = true
longname = "save flows for all packages to budget file"
description = "keyword to indicate that all model package flow terms will be written to the file specified with 'BUDGET FILEOUT' in Output Control."

[options.newtonoptions]
block = "options"
type = "record newton under_relaxation"
reader = "urword"
optional = true
longname = "newton keyword and options"
description = "none"

[packages.packages]
block = "packages"
type = "recarray"
reader = "urword"
optional = false
longname = "package list"

[packages.packages.item]
type = "record"
block = "packages"
reader = "urword"
optional = false
longname = "package list"

[packages.packages.item.fields.ftype]
block = "packages"
type = "string"
reader = "urword"
longname = "package type"
description = "is the file type, which must be one of the following character values shown in table~ref{table:ftype-olf}. Ftype may be entered in any combination of uppercase and lowercase."
in_record = true
tagged = false

[packages.packages.item.fields.fname]
block = "packages"
type = "string"
reader = "urword"
longname = "file name"
description = "is the name of the file containing the package input.  The path to the file should be included if the file is not located in the folder where the program was run."
in_record = true
preserve_case = true
tagged = false

[packages.packages.item.fields.pname]
block = "packages"
type = "string"
reader = "urword"
optional = true
longname = "user name for package"
description = "is the user-defined name for the package. PNAME is restricted to 16 characters.  No spaces are allowed in PNAME.  PNAME character values are read and stored by the program for stress packages only.  These names may be useful for labeling purposes when multiple stress packages of the same type are located within a single OLF Model.  If PNAME is specified for a stress package, then PNAME will be used in the flow budget table in the listing file; it will also be used for the text entry in the cell-by-cell budget file.  PNAME is case insensitive and is stored in all upper case letters."
in_record = true
tagged = false
