name = "prt-oc"
advanced = false
multi = false
schema_version = "2.0.0.dev0"

[options.budget_filerecord]
block = "options"
type = "record"
reader = "urword"
optional = true
tagged = true
mf6internal = "budfilerec"

[options.budget_filerecord.fields.budget]
block = "options"
type = "keyword"
reader = "urword"
optional = false
longname = "budget keyword"
description = "keyword to specify that record corresponds to the budget."
in_record = true
tagged = true

[options.budget_filerecord.fields.fileout]
block = "options"
type = "keyword"
reader = "urword"
optional = false
longname = "file keyword"
description = "keyword to specify that an output filename is expected next."
in_record = true
tagged = true

[options.budget_filerecord.fields.budgetfile]
block = "options"
type = "string"
reader = "urword"
optional = false
longname = "file keyword"
description = "name of the output file to write budget information."
preserve_case = true
in_record = true
tagged = false

[options.budgetcsv_filerecord]
block = "options"
type = "record"
reader = "urword"
optional = true
tagged = true
mf6internal = "budcsvfilerec"

[options.budgetcsv_filerecord.fields.fileout]
block = "options"
type = "keyword"
reader = "urword"
optional = false
longname = "file keyword"
description = "keyword to specify that an output filename is expected next."
in_record = true
tagged = true

[options.budgetcsv_filerecord.fields.budgetcsv]
block = "options"
type = "keyword"
reader = "urword"
optional = false
longname = "budget keyword"
description = "keyword to specify that record corresponds to the budget CSV."
in_record = true
tagged = true

[options.budgetcsv_filerecord.fields.budgetcsvfile]
block = "options"
type = "string"
reader = "urword"
optional = false
longname = "file keyword"
description = "name of the comma-separated value (CSV) output file to write budget summary information.  A budget summary record will be written to this file for each time step of the simulation."
preserve_case = true
in_record = true
tagged = false

[options.track_filerecord]
block = "options"
type = "record"
reader = "urword"
optional = true
tagged = true
mf6internal = "trackfilerec"

[options.track_filerecord.fields.fileout]
block = "options"
type = "keyword"
reader = "urword"
optional = false
longname = "file keyword"
description = "keyword to specify that an output filename is expected next."
in_record = true
tagged = true

[options.track_filerecord.fields.track]
block = "options"
type = "keyword"
reader = "urword"
optional = false
longname = "track keyword"
description = "keyword to specify that record corresponds to a binary track file.  Each PRT Model's OC Package may have only one binary track output file."
in_record = true
tagged = true

[options.track_filerecord.fields.trackfile]
block = "options"
type = "string"
reader = "urword"
optional = false
longname = "file keyword"
description = "name of the binary output file to write tracking information."
preserve_case = true
in_record = true
tagged = false

[options.trackcsv_filerecord]
block = "options"
type = "record"
reader = "urword"
optional = true
tagged = true
mf6internal = "trackcsvfilerec"

[options.trackcsv_filerecord.fields.fileout]
block = "options"
type = "keyword"
reader = "urword"
optional = false
longname = "file keyword"
description = "keyword to specify that an output filename is expected next."
in_record = true
tagged = true

[options.trackcsv_filerecord.fields.trackcsv]
block = "options"
type = "keyword"
reader = "urword"
optional = false
longname = "track keyword"
description = "keyword to specify that record corresponds to a CSV track file.  Each PRT Model's OC Package may have only one CSV track file."
in_record = true
tagged = true

[options.trackcsv_filerecord.fields.trackcsvfile]
block = "options"
type = "string"
reader = "urword"
optional = false
longname = "file keyword"
description = "name of the comma-separated value (CSV) file to write tracking information."
preserve_case = true
in_record = true
tagged = false

[options.track_release]
block = "options"
type = "keyword"
reader = "urword"
optional = true
longname = "track release"
description = "keyword to indicate that particle tracking output is to be written when a particle is released"

[options.track_exit]
block = "options"
type = "keyword"
reader = "urword"
optional = true
longname = "track domain exits"
description = "keyword to indicate that particle tracking output is to be written when a particle exits a grid feature (e.g. model, cell)"

[options.track_subfeature_exit]
block = "options"
type = "keyword"
reader = "urword"
optional = true
longname = "track cell exits"
description = "keyword to indicate that particle tracking output is to be written when a particle exits a sub-grid-scale feature. Such features are considered implementation details of the tracking algorithm employed for particular grid types, and reporting for exit events from such features is disabled by default."
mf6internal = "track_subf_exit"

[options.track_timestep]
block = "options"
type = "keyword"
reader = "urword"
optional = true
longname = "track timestep ends"
description = "keyword to indicate that particle tracking output is to be written at the end of each time step"

[options.track_terminate]
block = "options"
type = "keyword"
reader = "urword"
optional = true
longname = "track termination"
description = "keyword to indicate that particle tracking output is to be written when a particle terminates for any reason"

[options.track_weaksink]
block = "options"
type = "keyword"
reader = "urword"
optional = true
longname = "track weaksink exits"
description = "keyword to indicate that particle tracking output is to be written when a particle exits a weak sink (a cell which removes some but not all inflow from adjacent cells)"

[options.track_usertime]
block = "options"
type = "keyword"
reader = "urword"
optional = true
longname = "track user-specified times"
description = "keyword to indicate that particle tracking output is to be written at user-specified times, provided as double precision values in the TRACKTIMES block."

[options.track_dropped]
block = "options"
type = "keyword"
reader = "urword"
optional = true
longname = "track drops to water table"
description = "keyword to indicate that particle tracking output is to be written when a particle is dropped to the water table via DRY_TRACKING_METHOD DROP."

[options.track_timesrecord]
block = "options"
type = "record"
reader = "urword"
optional = true
tagged = true
mf6internal = "ttimesrec"
removed = "6.6.0"

[options.track_timesrecord.fields.track_times]
block = "options"
type = "keyword"
reader = "urword"
description = "keyword indicating tracking times will follow"
in_record = true
tagged = true
removed = "6.6.0"

[options.track_timesrecord.fields.times]
block = "options"
type = "double precision"
shape = "(any1d)"
reader = "urword"
longname = "tracking times"
description = "times to track, relative to the beginning of the simulation."
in_record = true
tagged = false
repeating = true
removed = "6.6.0"

[options.track_timesfilerecord]
block = "options"
type = "record"
reader = "urword"
optional = true
tagged = true
mf6internal = "ttimesfilerec"
removed = "6.6.0"

[options.track_timesfilerecord.fields.track_timesfile]
block = "options"
type = "keyword"
reader = "urword"
description = "keyword indicating tracking times file name will follow"
in_record = true
tagged = true
removed = "6.6.0"

[options.track_timesfilerecord.fields.timesfile]
block = "options"
type = "string"
reader = "urword"
optional = false
longname = "file keyword"
description = "name of the tracking times file"
preserve_case = true
in_record = true
tagged = false
removed = "6.6.0"

[options.dev_dump_event_trace]
block = "options"
type = "keyword"
reader = "urword"
optional = true
longname = "print particle tracking events"
description = "print a verbose particle tracking event trace to standard output"
mf6internal = "dev_dump_evtrace"

[dimensions.ntracktimes]
block = "dimensions"
type = "integer"
reader = "urword"
optional = true
longname = "number of particle tracking times"
description = "is the number of user-specified particle tracking times in the TRACKTIMES block."

[tracktimes.tracktimes]
block = "tracktimes"
type = "recarray"
shape = "(ntracktimes)"
reader = "urword"
optional = true

[tracktimes.tracktimes.item]
type = "record"
block = "tracktimes"
reader = "urword"
optional = true

[tracktimes.tracktimes.item.fields.time]
block = "tracktimes"
type = "double precision"
reader = "urword"
optional = false
longname = "release time"
description = "real value that defines the tracking time with respect to the simulation start time."
tagged = false
in_record = true

[period]
transient_block = true

[period.saverecord]
block = "period"
type = "record"
reader = "urword"
optional = true
tagged = false

[period.saverecord.fields.save]
block = "period"
type = "keyword"
reader = "urword"
optional = false
longname = "keyword to save"
description = "keyword to indicate that information will be saved this stress period."
in_record = true
tagged = true

[period.saverecord.fields.rtype]
block = "period"
type = "string"
reader = "urword"
optional = false
longname = "record type"
description = "type of information to save or print.  Can only be BUDGET."
in_record = true
tagged = false

[period.saverecord.fields.ocsetting]
block = "period"
type = "keystring"
reader = "urword"
description = "specifies the steps for which the data will be saved."
tagged = false
in_record = true

[period.saverecord.fields.ocsetting.choices.all]
block = "period"
type = "keyword"
reader = "urword"
description = "keyword to indicate save for all time steps in period."
in_record = true

[period.saverecord.fields.ocsetting.choices.first]
block = "period"
type = "keyword"
reader = "urword"
description = "keyword to indicate save for first step in period. This keyword may be used in conjunction with other keywords to print or save results for multiple time steps."
in_record = true

[period.saverecord.fields.ocsetting.choices.last]
block = "period"
type = "keyword"
reader = "urword"
description = "keyword to indicate save for last step in period. This keyword may be used in conjunction with other keywords to print or save results for multiple time steps."
in_record = true

[period.saverecord.fields.ocsetting.choices.frequency]
block = "period"
type = "integer"
reader = "urword"
description = "save at the specified time step frequency. This keyword may be used in conjunction with other keywords to print or save results for multiple time steps."
tagged = true
in_record = true

[period.saverecord.fields.ocsetting.choices.steps]
block = "period"
type = "integer"
shape = "(<nstp)"
reader = "urword"
description = "save for each step specified in STEPS. This keyword may be used in conjunction with other keywords to print or save results for multiple time steps."
tagged = true
in_record = true

[period.printrecord]
block = "period"
type = "record"
reader = "urword"
optional = true
tagged = false

[period.printrecord.fields.print]
block = "period"
type = "keyword"
reader = "urword"
optional = false
longname = "keyword to save"
description = "keyword to indicate that information will be printed this stress period."
in_record = true
tagged = true

[period.printrecord.fields.rtype]
block = "period"
type = "string"
reader = "urword"
optional = false
longname = "record type"
description = "type of information to save or print.  Can only be BUDGET."
in_record = true
tagged = false

[period.printrecord.fields.ocsetting]
block = "period"
type = "keystring"
reader = "urword"
description = "specifies the steps for which the data will be saved."
tagged = false
in_record = true

[period.printrecord.fields.ocsetting.choices.all]
block = "period"
type = "keyword"
reader = "urword"
description = "keyword to indicate save for all time steps in period."
in_record = true

[period.printrecord.fields.ocsetting.choices.first]
block = "period"
type = "keyword"
reader = "urword"
description = "keyword to indicate save for first step in period. This keyword may be used in conjunction with other keywords to print or save results for multiple time steps."
in_record = true

[period.printrecord.fields.ocsetting.choices.last]
block = "period"
type = "keyword"
reader = "urword"
description = "keyword to indicate save for last step in period. This keyword may be used in conjunction with other keywords to print or save results for multiple time steps."
in_record = true

[period.printrecord.fields.ocsetting.choices.frequency]
block = "period"
type = "integer"
reader = "urword"
description = "save at the specified time step frequency. This keyword may be used in conjunction with other keywords to print or save results for multiple time steps."
tagged = true
in_record = true

[period.printrecord.fields.ocsetting.choices.steps]
block = "period"
type = "integer"
shape = "(<nstp)"
reader = "urword"
description = "save for each step specified in STEPS. This keyword may be used in conjunction with other keywords to print or save results for multiple time steps."
tagged = true
in_record = true
