# This file tells modflow-devtools where to find DFN releases.
# Users can override or extend this with a config file at:
#   - Linux/macOS: ~/.config/modflow-devtools/dfns.toml
#   - Windows: %APPDATA%/modflow-devtools/dfns.toml

releases = [
    # "MODFLOW-ORG/modflow6@latest",
    "MODFLOW-ORG/modflow6-nightly-build@latest"
]
