name: Release
on:
  push:
    tags:
      - v*
jobs:
  release:
    name: Release & publish
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.7

      - name: Install Python packages
        run: |
          pip install --upgrade pip
          pip install build twine
          pip install .

      - name: Print version
        run: |
          python -c "import modflow_devtools; print(modflow_devtools.__version__)"

      - name: Build package
        run: |
          python -m build
      
      - name: Check distribution
        run: |
          twine check --strict dist/*

      - name: Publish package
        if: ${{ env.TWINE_USERNAME != '' }}
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          twine upload dist/*

      - name: Create release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          prerelease: true
          repo_token: ${{ github.token }}